; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2

; RUN: llc -mtriple=riscv64-codasip-linux-gnu -mattr=+zcheripurecap,+cap-mode,+cheri-bounded-vararg,+cheri-bounded-memarg-callee,+f,+d -target-abi l64pc128d  %s -o - | FileCheck %s
target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "riscv64-codasip-linux-gnu"

define i32 @foo(i32 %x, i32 %y, i32 %z, i32 %u, i32 %v, i32 %w, i32 %t1, i32 %t2, i32 %t3, ptr addrspace(200) %t4) addrspace(200) nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -48
; CHECK-NEXT:    sc cra, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs0, 16(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs1, 0(csp) # 16-byte Folded Spill
; CHECK-NEXT:    lc cs0, 16(ct1)
; CHECK-NEXT:    ld a0, 0(ct1)
; CHECK-NEXT:    call bar
; CHECK-NEXT:    mv s1, a0
; CHECK-NEXT:    cmv ca0, cs0
; CHECK-NEXT:    call baz
; CHECK-NEXT:    addw a0, a0, s1
; CHECK-NEXT:    lc cra, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs0, 16(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs1, 0(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 48
; CHECK-NEXT:    ret
  entry:
    %call = call i32 @bar(i32 %t3)
    %call1 = call i32 @baz(ptr addrspace(200) %t4)
    %add = add nsw i32 %call1, %call
    ret i32 %add
}

declare i32 @bar(i32) addrspace(200)

define internal i32 @baz(ptr addrspace(200)) addrspace(200) nounwind {
; CHECK-LABEL: baz:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
  ret i32 0
}

define i32 @baf(i32 %z, i32 %u, i32 %v, i32 %w, i32 %t1, i32 %t2, i32 %t3, ptr addrspace(200) %t4, ...) addrspace(200) nounwind {
; CHECK-LABEL: baf:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -80
; CHECK-NEXT:    sc cra, 64(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs0, 48(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs1, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    caddi ca0, csp, 16
; CHECK-NEXT:    scbndsi ca0, ca0, 16
; CHECK-NEXT:    lui a1, 1048544
; CHECK-NEXT:    addiw a1, a1, -2
; CHECK-NEXT:    acperm ca1, ct1, a1
; CHECK-NEXT:    sc ca1, 0(ca0)
; CHECK-NEXT:    lc ca0, 16(csp)
; CHECK-NEXT:    cmv cs0, ca7
; CHECK-NEXT:    mv s1, a6
; CHECK-NEXT:    sc ct1, 0(csp)
; CHECK-NEXT:    call try
; CHECK-NEXT:    mv a0, s1
; CHECK-NEXT:    call bar
; CHECK-NEXT:    mv s1, a0
; CHECK-NEXT:    cmv ca0, cs0
; CHECK-NEXT:    call baz
; CHECK-NEXT:    addw a0, a0, s1
; CHECK-NEXT:    lc cra, 64(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs0, 48(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs1, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 80
; CHECK-NEXT:    ret
entry:
  %va = alloca ptr addrspace(200), align 16, addrspace(200)
  call void @llvm.lifetime.start.p200(i64 16, i8 addrspace(200)* nonnull %va)
  call void @llvm.va_start.p200(i8 addrspace(200)* nonnull %va)
  %0 = load ptr addrspace(200), ptr addrspace(200) %va, align 16
  call void @try(ptr addrspace(200) %0)
  %call = call i32 @bar(i32 %t3)
  %call2 = call i32 @baz(ptr addrspace(200) %t4)
  %add = add nsw i32 %call2, %call
  call void @llvm.lifetime.end.p200(i64 16, ptr addrspace(200) nonnull %va)
  ret i32 %add
}



declare void @llvm.lifetime.start.p200(i64 immarg, ptr addrspace(200) nocapture) addrspace(200)
declare void @llvm.lifetime.end.p200(i64 immarg, ptr addrspace(200) nocapture) addrspace(200)
declare void @llvm.va_start.p200(ptr addrspace(200)) addrspace(200)
declare void @try(ptr addrspace(200)) local_unnamed_addr addrspace(200)

define i32 @bb([4 x float] %f1.coerce, [4 x float] %f2.coerce, [4 x float] %f3.coerce, ...) addrspace(200) nounwind {
; CHECK-LABEL: bb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -32
; CHECK-NEXT:    caddi ca2, csp, 16
; CHECK-NEXT:    scbndsi ca2, ca2, 16
; CHECK-NEXT:    lui a4, 1048544
; CHECK-NEXT:    addiw a4, a4, -2
; CHECK-NEXT:    acperm ca4, ct1, a4
; CHECK-NEXT:    sc ca4, 0(ca2)
; CHECK-NEXT:    sc ct1, 0(csp)
; CHECK-NEXT:    lc ca2, 16(csp)
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    fmv.w.x fa4, a0
; CHECK-NEXT:    fadd.s fa5, fa4, fa5
; CHECK-NEXT:    caddi ca0, ca2, 16
; CHECK-NEXT:    sc ca0, 16(csp)
; CHECK-NEXT:    fld fa4, 0(ca2)
; CHECK-NEXT:    fmv.w.x fa3, a3
; CHECK-NEXT:    fadd.s fa5, fa3, fa5
; CHECK-NEXT:    fadd.s fa5, fa7, fa5
; CHECK-NEXT:    fcvt.s.d fa4, fa4
; CHECK-NEXT:    fadd.s fa5, fa5, fa4
; CHECK-NEXT:    fcvt.w.s a0, fa5, rtz
; CHECK-NEXT:    caddi csp, csp, 32
; CHECK-NEXT:    ret
entry:
  %va = alloca ptr addrspace(200), align 16, addrspace(200)
  %f2.coerce.fca.3.extract = extractvalue [4 x float] %f2.coerce, 3
  %f3.coerce.fca.0.extract = extractvalue [4 x float] %f3.coerce, 0
  %f3.coerce.fca.1.extract = extractvalue [4 x float] %f3.coerce, 1
  %f3.coerce.fca.3.extract = extractvalue [4 x float] %f3.coerce, 3
  %add = fadd float %f3.coerce.fca.0.extract, %f3.coerce.fca.1.extract
  %add3 = fadd float %f3.coerce.fca.3.extract, %add
  %add5 = fadd float %f2.coerce.fca.3.extract, %add3
  call void @llvm.lifetime.start.p200(i64 16, ptr addrspace(200) nonnull %va)
  call void @llvm.va_start.p200(ptr addrspace(200) nonnull %va)
  %stack = load ptr addrspace(200), ptr addrspace(200) %va, align 16
  %new_stack = getelementptr inbounds i8, ptr addrspace(200) %stack, i64 16
  store ptr addrspace(200) %new_stack, ptr addrspace(200) %va, align 16
  %0 = load double, ptr addrspace(200) %stack, align 16
  %conv = fptrunc double %0 to float
  %add7 = fadd float %add5, %conv
  %conv8 = fptosi float %add7 to i32
  call void @llvm.lifetime.end.p200(i64 16, ptr addrspace(200) nonnull %va)
  ret i32 %conv8
}


define i32 @biz() local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: biz:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -64
; CHECK-NEXT:    sc cra, 48(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs0, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    sd a0, 16(csp)
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    scbndsr ca1, csp, a1
; CHECK-NEXT:    lui a2, 1048544
; CHECK-NEXT:    addiw a2, a2, -2
; CHECK-NEXT:    acperm ct1, ca1, a2
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a3, 3
; CHECK-NEXT:    li a4, 4
; CHECK-NEXT:    li a5, 5
; CHECK-NEXT:    li a6, 6
; CHECK-NEXT:    sd a0, 0(csp)
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    cmv ca7, cnull
; CHECK-NEXT:    call fiz
; CHECK-NEXT:    mv s0, a0
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a3, 3
; CHECK-NEXT:    li a4, 4
; CHECK-NEXT:    li a5, 5
; CHECK-NEXT:    li a6, 6
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    cmv ca7, cnull
; CHECK-NEXT:    cmv ct1, cnull
; CHECK-NEXT:    call fiz
; CHECK-NEXT:    addw a0, a0, s0
; CHECK-NEXT:    lc cra, 48(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs0, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 64
; CHECK-NEXT:    ret
entry:
  %call = call i32 (i32, i32, i32, i32, i32, i32, i32, ptr addrspace(200), ...) @fiz(i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, ptr addrspace(200) null, i32 1, i32 1)
  %call1 = call i32 (i32, i32, i32, i32, i32, i32, i32, ptr addrspace(200), ...) @fiz(i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, ptr addrspace(200) null)
  %add = add nsw i32 %call1, %call
  ret i32 %add
}

declare i32 @fiz(i32, i32, i32, i32, i32, i32, i32, ptr addrspace(200), ...) addrspace(200)

