; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64-codasip-linux-gnu -mattr=+zcheripurecap,+cap-mode,+cheri-bounded-vararg,+cheri-bounded-memarg-caller,+cheri-bounded-memarg-callee,+f,+d -target-abi l64pc128d  %s -o - | FileCheck %s
target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "riscv64-codasip-linux-gnu"

; Function Attrs: nounwind
define dso_local signext i32 @foo(i32 noundef signext %a, i32 noundef signext %b, i32 noundef signext %c, i32 noundef signext %d, i32 noundef signext %e, i32 noundef signext %f, i32 noundef signext %g, i32 noundef signext %h, i32 noundef signext %i, ptr addrspace(200) noundef %j) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -48
; CHECK-NEXT:    sc cra, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs0, 16(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs1, 0(csp) # 16-byte Folded Spill
; CHECK-NEXT:    lc cs0, 16(ct1)
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    call bar
; CHECK-NEXT:    mv s1, a0
; CHECK-NEXT:    cmv ca0, cs0
; CHECK-NEXT:    call baz
; CHECK-NEXT:    addw a0, a0, s1
; CHECK-NEXT:    lc cra, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs0, 16(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs1, 0(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 48
; CHECK-NEXT:    ret
entry:
  %call = call signext i32 @bar(i32 noundef signext %b) #5
  %call1 = call signext i32 @baz(ptr addrspace(200) noundef %j) #5
  %add = add nsw i32 %call1, %call
  ret i32 %add
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p200(i64 immarg, ptr addrspace(200) nocapture) addrspace(200) #1

declare signext i32 @bar(i32 noundef signext) local_unnamed_addr addrspace(200) #2

declare signext i32 @baz(ptr addrspace(200) noundef) local_unnamed_addr addrspace(200) #2

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p200(i64 immarg, ptr addrspace(200) nocapture) addrspace(200) #1

; Function Attrs: nounwind
define dso_local signext i32 @baf(i32 noundef signext %a, i32 noundef signext %b, i32 noundef signext %c, i32 noundef signext %d, i32 noundef signext %e, i32 noundef signext %f, i32 noundef signext %g, i32 noundef signext %h, i32 noundef signext %i, ptr addrspace(200) noundef %j, ...) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: baf:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -80
; CHECK-NEXT:    sc cra, 64(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs0, 48(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs1, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    caddi ca0, ct1, 32
; CHECK-NEXT:    sc ca0, 0(csp)
; CHECK-NEXT:    lc cs0, 16(ct1)
; CHECK-NEXT:    ld s1, 0(ct1)
; CHECK-NEXT:    caddi ca1, csp, 16
; CHECK-NEXT:    scbndsi ca1, ca1, 16
; CHECK-NEXT:    lui a2, 1048544
; CHECK-NEXT:    addiw a2, a2, -2
; CHECK-NEXT:    acperm ca0, ca0, a2
; CHECK-NEXT:    sc ca0, 0(ca1)
; CHECK-NEXT:    lc ca0, 16(csp)
; CHECK-NEXT:    caddi ca1, ca0, 16
; CHECK-NEXT:    sc ca1, 16(csp)
; CHECK-NEXT:    lc ca0, 0(ca0)
; CHECK-NEXT:    call try
; CHECK-NEXT:    mv a0, s1
; CHECK-NEXT:    call bar
; CHECK-NEXT:    mv s1, a0
; CHECK-NEXT:    cmv ca0, cs0
; CHECK-NEXT:    call baz
; CHECK-NEXT:    addw a0, a0, s1
; CHECK-NEXT:    lc cra, 64(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs0, 48(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs1, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 80
; CHECK-NEXT:    ret
entry:
  %args = alloca ptr addrspace(200), align 16, addrspace(200)
  call void @llvm.lifetime.start.p200(i64 16, ptr addrspace(200) nonnull %args) #5
  call void @llvm.va_start.p200(ptr addrspace(200) nonnull %args)
  %argp.cur = load ptr addrspace(200), ptr addrspace(200) %args, align 16
  %argp.next = getelementptr inbounds i8, ptr addrspace(200) %argp.cur, i64 16
  store ptr addrspace(200) %argp.next, ptr addrspace(200) %args, align 16
  %0 = load ptr addrspace(200), ptr addrspace(200) %argp.cur, align 16
  call void @try(ptr addrspace(200) noundef %0) #5
  %call = call signext i32 @bar(i32 noundef signext %i) #5
  %call1 = call signext i32 @baz(ptr addrspace(200) noundef %j) #5
  call void @llvm.va_end.p200(ptr addrspace(200) nonnull %args)
  %add = add nsw i32 %call1, %call
  call void @llvm.lifetime.end.p200(i64 16, ptr addrspace(200) nonnull %args) #5
  ret i32 %add
}

define i32 @bb([4 x float] %f1.coerce, [4 x float] %f2.coerce, [4 x float] %f3.coerce, ...) addrspace(200) {
; CHECK-LABEL: bb:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    caddi ca2, csp, 16
; CHECK-NEXT:    scbndsi ca2, ca2, 16
; CHECK-NEXT:    lui a4, 1048544
; CHECK-NEXT:    addiw a4, a4, -2
; CHECK-NEXT:    acperm ca4, ct1, a4
; CHECK-NEXT:    sc ca4, 0(ca2)
; CHECK-NEXT:    sc ct1, 0(csp)
; CHECK-NEXT:    lc ca2, 16(csp)
; CHECK-NEXT:    fmv.w.x fa5, a1
; CHECK-NEXT:    fmv.w.x fa4, a0
; CHECK-NEXT:    fadd.s fa5, fa4, fa5
; CHECK-NEXT:    caddi ca0, ca2, 16
; CHECK-NEXT:    sc ca0, 16(csp)
; CHECK-NEXT:    fld fa4, 0(ca2)
; CHECK-NEXT:    fmv.w.x fa3, a3
; CHECK-NEXT:    fadd.s fa5, fa3, fa5
; CHECK-NEXT:    fadd.s fa5, fa7, fa5
; CHECK-NEXT:    fcvt.s.d fa4, fa4
; CHECK-NEXT:    fadd.s fa5, fa5, fa4
; CHECK-NEXT:    fcvt.w.s a0, fa5, rtz
; CHECK-NEXT:    caddi csp, csp, 32
; CHECK-NEXT:    ret
entry:
  %va = alloca ptr addrspace(200), align 16, addrspace(200)
  %f2.coerce.fca.3.extract = extractvalue [4 x float] %f2.coerce, 3
  %f3.coerce.fca.0.extract = extractvalue [4 x float] %f3.coerce, 0
  %f3.coerce.fca.1.extract = extractvalue [4 x float] %f3.coerce, 1
  %f3.coerce.fca.3.extract = extractvalue [4 x float] %f3.coerce, 3
  %add = fadd float %f3.coerce.fca.0.extract, %f3.coerce.fca.1.extract
  %add3 = fadd float %f3.coerce.fca.3.extract, %add
  %add5 = fadd float %f2.coerce.fca.3.extract, %add3
  call void @llvm.lifetime.start.p200(i64 16, ptr addrspace(200) nonnull %va)
  call void @llvm.va_start.p200(ptr addrspace(200) nonnull %va)
  %stack = load ptr addrspace(200), ptr addrspace(200) %va, align 16
  %new_stack = getelementptr inbounds i8, ptr addrspace(200) %stack, i64 16
  store ptr addrspace(200) %new_stack, ptr addrspace(200) %va, align 16
  %0 = load double, ptr addrspace(200) %stack, align 16
  %conv = fptrunc double %0 to float
  %add7 = fadd float %add5, %conv
  %conv8 = fptosi float %add7 to i32
  call void @llvm.lifetime.end.p200(i64 16, ptr addrspace(200) nonnull %va)
  ret i32 %conv8
}

define i32 @biz() local_unnamed_addr addrspace(200) {
; CHECK-LABEL: biz:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -112
; CHECK-NEXT:    .cfi_def_cfa_offset 112
; CHECK-NEXT:    sc cra, 96(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs0, 80(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs1, 64(csp) # 16-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -16
; CHECK-NEXT:    .cfi_offset s0, -32
; CHECK-NEXT:    .cfi_offset s1, -48
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    sd a0, 48(csp)
; CHECK-NEXT:    sd a0, 32(csp)
; CHECK-NEXT:    sc cnull, 16(csp)
; CHECK-NEXT:    li s1, 8
; CHECK-NEXT:    li a0, 64
; CHECK-NEXT:    scbndsr ct1, csp, a0
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a3, 3
; CHECK-NEXT:    li a4, 4
; CHECK-NEXT:    li a5, 5
; CHECK-NEXT:    li a6, 6
; CHECK-NEXT:    li a7, 7
; CHECK-NEXT:    sd s1, 0(csp)
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    call fiz
; CHECK-NEXT:    mv s0, a0
; CHECK-NEXT:    sc cnull, 16(csp)
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    scbndsr ct1, csp, a0
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a3, 3
; CHECK-NEXT:    li a4, 4
; CHECK-NEXT:    li a5, 5
; CHECK-NEXT:    li a6, 6
; CHECK-NEXT:    li a7, 7
; CHECK-NEXT:    sd s1, 0(csp)
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    call fiz
; CHECK-NEXT:    addw a0, a0, s0
; CHECK-NEXT:    lc cra, 96(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs0, 80(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs1, 64(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 112
; CHECK-NEXT:    ret
entry:
  %call = call i32 (i32, i32, i32, i32, i32, i32, i32, i32, i32, ptr addrspace(200), ...) @fiz(i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, ptr addrspace(200) null, i32 1, i32 1)
  %call1 = call i32 (i32, i32, i32, i32, i32, i32, i32, i32, i32, ptr addrspace(200), ...) @fiz(i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, ptr addrspace(200) null)
  %add = add nsw i32 %call1, %call
  ret i32 %add
}

declare i32 @fiz(i32, i32, i32, i32, i32, i32, i32, i32, i32, ptr addrspace(200), ...) addrspace(200)

define i32 @f(i32 %0, i32 %1, i32 %2, i32 %3, i32 %4, i32 %5, i32 %6, i32 %7, i32 %8, ...) local_unnamed_addr addrspace(200) {
; CHECK-LABEL: f:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    caddi ca0, ct1, 16
; CHECK-NEXT:    sc ca0, 0(csp)
; CHECK-NEXT:    lw a1, 0(ct1)
; CHECK-NEXT:    caddi ca2, csp, 16
; CHECK-NEXT:    scbndsi ca2, ca2, 16
; CHECK-NEXT:    lui a3, 1048544
; CHECK-NEXT:    addiw a3, a3, -2
; CHECK-NEXT:    acperm ca0, ca0, a3
; CHECK-NEXT:    sc ca0, 0(ca2)
; CHECK-NEXT:    lc ca0, 16(csp)
; CHECK-NEXT:    caddi ca2, ca0, 16
; CHECK-NEXT:    sc ca2, 16(csp)
; CHECK-NEXT:    lw a0, 0(ca0)
; CHECK-NEXT:    addw a0, a0, a1
; CHECK-NEXT:    caddi csp, csp, 32
; CHECK-NEXT:    ret
entry:
  %va = alloca ptr addrspace(200), align 16, addrspace(200)
  call void @llvm.lifetime.start.p200(i64 16, ptr addrspace(200) %va)
  call void @llvm.va_start.p200(ptr addrspace(200) %va)
  %stack = load ptr addrspace(200), ptr addrspace(200) %va, align 16
  %stack.next = getelementptr inbounds i8, ptr addrspace(200) %stack, i64 16
  store ptr addrspace(200) %stack.next, ptr addrspace(200) %va, align 16
  %val = load i32, ptr addrspace(200) %stack, align 16
  call void @llvm.va_end.p200(ptr addrspace(200) %va)
  %add = add nsw i32 %val, %8
  call void @llvm.lifetime.end.p200(i64 16, ptr addrspace(200) nonnull %va)
  ret i32 %add
}

define i32 @callargs() {
; CHECK-LABEL: callargs:
; CHECK:       # %bb.0:
; CHECK-NEXT:    caddi csp, csp, -96
; CHECK-NEXT:    .cfi_def_cfa_offset 96
; CHECK-NEXT:    sc cra, 80(csp) # 16-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -16
; CHECK-NEXT:    li a0, 104
; CHECK-NEXT:    sd a0, 64(csp)
; CHECK-NEXT:    li a0, 103
; CHECK-NEXT:    sd a0, 48(csp)
; CHECK-NEXT:    li a0, 102
; CHECK-NEXT:    sd a0, 40(csp)
; CHECK-NEXT:    li a0, 101
; CHECK-NEXT:    sd a0, 32(csp)
; CHECK-NEXT:    li a0, 100
; CHECK-NEXT:    sd a0, 0(csp)
; CHECK-NEXT:    li a0, 80
; CHECK-NEXT:    scbndsr ct1, csp, a0
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    li a1, 2
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    li a3, 4
; CHECK-NEXT:    li a4, 5
; CHECK-NEXT:    li a5, 6
; CHECK-NEXT:    li a6, 7
; CHECK-NEXT:    li a7, 8
; CHECK-NEXT:    sc cnull, 16(csp)
; CHECK-NEXT:    call readmemargs
; CHECK-NEXT:    lc cra, 80(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 96
; CHECK-NEXT:    ret
  %1 = call i32 (i32, i32, i32, i32, i32, i32, i32, i32, i32, ptr addrspace(200), i32, i32, ...) @readmemargs(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 100, ptr addrspace(200) null, i32 101, i32 102, i32 103, i32 104)
  ret i32 %1
}

define i32 @readmemargs(i32, i32, i32, i32, i32, i32, i32, i32, i32 %memarg1, ptr addrspace(200) %memarg2, i32 %memarg3, i32 %memarg4, ...){
; CHECK-LABEL: readmemargs:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    caddi ca0, ct1, 48
; CHECK-NEXT:    sc ca0, 0(csp)
; CHECK-NEXT:    lc ca0, 16(ct1)
; CHECK-NEXT:    lw a1, 32(ct1)
; CHECK-NEXT:    lw a2, 0(ct1)
; CHECK-NEXT:    lw a0, 0(ca0)
; CHECK-NEXT:    lw a3, 40(ct1)
; CHECK-NEXT:    add a1, a2, a1
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    addw a0, a0, a3
; CHECK-NEXT:    caddi csp, csp, 16
; CHECK-NEXT:    ret
entry:
  %ptr.val = load i32, ptr addrspace(200) %memarg2, align 16
  %add.0 = add nsw i32 %ptr.val, %memarg1
  %add.1 = add nsw i32 %add.0, %memarg3
  %add.2 = add nsw i32 %add.1, %memarg4
  ret i32 %add.2
}

define i32 @calltyhitassert() {
; CHECK-LABEL: calltyhitassert:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    sc cra, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -16
; CHECK-NEXT:    li a0, 201
; CHECK-NEXT:    sd a0, 16(csp)
; CHECK-NEXT:    li t0, 101
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    scbndsr ct1, csp, a0
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    li a1, 2
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    li a3, 4
; CHECK-NEXT:    li a4, 5
; CHECK-NEXT:    li a5, 6
; CHECK-NEXT:    li a6, 7
; CHECK-NEXT:    li a7, 8
; CHECK-NEXT:    sd t0, 0(csp)
; CHECK-NEXT:    call tryhitassert
; CHECK-NEXT:    lc cra, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 48
; CHECK-NEXT:    ret
entry:
 %val = call i32 (i32, i32, i32, i32, i32, i32, i32, i32, i32 , ...) @tryhitassert(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 101, i32 201)
 ret i32 %val
}

define i32 @tryhitassert(i32, i32, i32, i32, i32, i32, i32, i32, i32 %memarg, ...) {
; CHECK-LABEL: tryhitassert:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    caddi ca0, ct1, 16
; CHECK-NEXT:    sc ca0, 0(csp)
; CHECK-NEXT:    lw a1, 0(ct1)
; CHECK-NEXT:    caddi ca2, csp, 16
; CHECK-NEXT:    scbndsi ca2, ca2, 16
; CHECK-NEXT:    lui a3, 1048544
; CHECK-NEXT:    addiw a3, a3, -2
; CHECK-NEXT:    acperm ca0, ca0, a3
; CHECK-NEXT:    sc ca0, 0(ca2)
; CHECK-NEXT:    lc ca0, 16(csp)
; CHECK-NEXT:    caddi ca2, ca0, 16
; CHECK-NEXT:    sc ca2, 16(csp)
; CHECK-NEXT:    lw a0, 0(ca0)
; CHECK-NEXT:    addw a0, a1, a0
; CHECK-NEXT:    caddi csp, csp, 32
; CHECK-NEXT:    ret
entry:
  %va = alloca ptr addrspace(200), align 16, addrspace(200)
  call void @llvm.lifetime.start.p200(i64 16, ptr addrspace(200) %va)
  call void @llvm.va_start.p200(ptr addrspace(200) %va)
  %stack = load ptr addrspace(200), ptr addrspace(200) %va, align 16
  %stack.next = getelementptr inbounds i8, ptr addrspace(200) %stack, i64 16
  store ptr addrspace(200) %stack.next, ptr addrspace(200) %va, align 16
  %va_arg = load i32, ptr addrspace(200) %stack, align 16
  call void @llvm.va_end.p200(ptr addrspace(200) %va)
  %add.res = add nsw i32 %memarg, %va_arg
  ret i32 %add.res
}

%struct.agg = type { i32, i32, i8, i8, i32 }
define i32 @aggregate(i32, i32, i32, i32, i32, i32, %struct.agg %arg, ...) {
; CHECK-LABEL: aggregate:
; CHECK:       # %bb.0:
; CHECK-NEXT:    caddi csp, csp, -16
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    caddi ca0, ct1, 32
; CHECK-NEXT:    sc ca0, 0(csp)
; CHECK-NEXT:    lb a0, 0(ct1)
; CHECK-NEXT:    lb a1, 8(ct1)
; CHECK-NEXT:    add a6, a6, a7
; CHECK-NEXT:    add a0, a6, a0
; CHECK-NEXT:    addw a0, a0, a1
; CHECK-NEXT:    caddi csp, csp, 16
; CHECK-NEXT:    ret
  %a = extractvalue %struct.agg %arg, 0
  %b = extractvalue %struct.agg %arg, 1
  %c = extractvalue %struct.agg %arg, 2
  %c.32 = sext i8 %c to i32
  %d = extractvalue %struct.agg %arg, 3
  %d.32 = sext i8 %d to i32
  %add.0 = add nsw i32 %a, %b
  %add.1 = add nsw i32 %add.0, %c.32
  %add.2 = add nsw i32 %add.1, %d.32
  ret i32 %add.2
}

define i32 @callAggr() {
; CHECK-LABEL: callAggr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    caddi csp, csp, -80
; CHECK-NEXT:    .cfi_def_cfa_offset 80
; CHECK-NEXT:    sc cra, 64(csp) # 16-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -16
; CHECK-NEXT:    li a0, 200
; CHECK-NEXT:    sw a0, 60(csp)
; CHECK-NEXT:    li a0, 13
; CHECK-NEXT:    sb a0, 57(csp)
; CHECK-NEXT:    li a0, 12
; CHECK-NEXT:    sb a0, 56(csp)
; CHECK-NEXT:    li a0, 101
; CHECK-NEXT:    sw a0, 52(csp)
; CHECK-NEXT:    li a0, 100
; CHECK-NEXT:    sw a0, 48(csp)
; CHECK-NEXT:    lw a7, 52(csp)
; CHECK-NEXT:    lw a6, 48(csp)
; CHECK-NEXT:    lb t0, 56(csp)
; CHECK-NEXT:    lb a0, 57(csp)
; CHECK-NEXT:    lw a1, 60(csp)
; CHECK-NEXT:    li a2, 300
; CHECK-NEXT:    sd a2, 32(csp)
; CHECK-NEXT:    sd a1, 16(csp)
; CHECK-NEXT:    sd a0, 8(csp)
; CHECK-NEXT:    li a0, 48
; CHECK-NEXT:    scbndsr ct1, csp, a0
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    li a1, 2
; CHECK-NEXT:    li a2, 3
; CHECK-NEXT:    li a3, 4
; CHECK-NEXT:    li a4, 5
; CHECK-NEXT:    li a5, 6
; CHECK-NEXT:    sd t0, 0(csp)
; CHECK-NEXT:    call aggregate
; CHECK-NEXT:    lc cra, 64(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 80
; CHECK-NEXT:    ret
  %struct = alloca %struct.agg, addrspace(200)
  store %struct.agg { i32 100, i32 101, i8 12, i8 13, i32 200}, ptr addrspace(200) %struct
  %struct.val = load %struct.agg, ptr addrspace(200) %struct
  %ret = call i32 (i32, i32, i32, i32, i32, i32, %struct.agg, ...) @aggregate(i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, %struct.agg %struct.val, i32 300)
  ret i32 %ret
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.va_start.p200(ptr addrspace(200)) addrspace(200) #3

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare ptr addrspace(200) @llvm.ptrmask.p200.i64(ptr addrspace(200), i64) addrspace(200) #4

declare void @try(ptr addrspace(200) noundef) local_unnamed_addr addrspace(200) #2

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn
declare void @llvm.va_end.p200(ptr addrspace(200)) addrspace(200) #3

attributes #0 = { nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+64bit,+zcheripurecap" }
attributes #1 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+64bit,+zcheripurecap" }
attributes #3 = { mustprogress nocallback nofree nosync nounwind willreturn }
attributes #4 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #5 = { nounwind }
