; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple riscv64 -mattr=+zcheripurecap,+zcherihybrid,+cap-mode,+cheri-bounded-vararg,+cheri-bounded-memarg-callee,+cheri-bounded-memarg-caller -target-abi l64pc128d %s -o - | FileCheck %s

define dso_local i32 @g() addrspace(200) {
; CHECK-LABEL: g:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    sc cra, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -16
; CHECK-NEXT:    li a0, 200
; CHECK-NEXT:    sd a0, 24(csp)
; CHECK-NEXT:    li a0, 100
; CHECK-NEXT:    sd a0, 16(csp)
; CHECK-NEXT:    li a0, 8
; CHECK-NEXT:    li a1, 32
; CHECK-NEXT:    scbndsr ct1, csp, a1
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    li a2, 2
; CHECK-NEXT:    li a3, 3
; CHECK-NEXT:    li a4, 4
; CHECK-NEXT:    li a5, 5
; CHECK-NEXT:    li a6, 6
; CHECK-NEXT:    li a7, 7
; CHECK-NEXT:    sd a0, 0(csp)
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    call f
; CHECK-NEXT:    lc cra, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 48
; CHECK-NEXT:    ret
entry:
  %call = tail call signext i32 (i32, i32, i32, i32, i32, i32, i32, i32, i32, ...) @f(i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, [2 x i64] [i64 100, i64 200])
  ret i32 %call
}

declare i32 @f(i32, i32, i32, i32, i32, i32, i32, i32, i32, ...) addrspace(200)

define dso_local i128 @foo() addrspace(200) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -48
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    sc cra, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -16
; CHECK-NEXT:    sd zero, 24(csp)
; CHECK-NEXT:    li a0, 789
; CHECK-NEXT:    sd a0, 16(csp)
; CHECK-NEXT:    sd zero, 8(csp)
; CHECK-NEXT:    li a1, 456
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    scbndsr ct1, csp, a0
; CHECK-NEXT:    caddi ca0, cnull, 1
; CHECK-NEXT:    li a5, 123
; CHECK-NEXT:    sd a1, 0(csp)
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    li a4, 0
; CHECK-NEXT:    li a6, 0
; CHECK-NEXT:    call bar
; CHECK-NEXT:    lc cra, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 48
; CHECK-NEXT:    ret
entry:
  %call = call i128 (ptr addrspace(200), i128, i128, i128, ...) @bar(ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 1), i128 0, i128 0, i128 123, i128 456, i128 789)
  ret i128 %call
}

declare i128 @bar(ptr addrspace(200), i128, i128, i128, ...) addrspace(200)

