; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/dagcombine-ptradd-deleted-regression.ll
; This would previously crash DAGCombiner::visitPTRADD since the PTRADD
; corresponding to the second GEP would be collapsed to a no-op when
; reassociated and delete the synthesised PTRADD node, not just the ADD, which
; the folding code was not prepared for.
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+cap-mode,+f,+d %s -o - | FileCheck %s --check-prefix=PURECAP

declare i32 @bar(ptr addrspace(200))

define internal i32 @foo(ptr addrspace(200) %a, ptr addrspace(200) %b) nounwind {
; HYBRID-LABEL: foo:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    addi sp, sp, -32
; HYBRID-NEXT:    sd ra, 24(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    cincoffset ca0, ca0, 4
; HYBRID-NEXT:    sc ca0, 0(sp) # 16-byte Folded Spill
; HYBRID-NEXT:  .LBB0_1: # %loop
; HYBRID-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-NEXT:    lc ca0, 0(sp) # 16-byte Folded Reload
; HYBRID-NEXT:    call bar@plt
; HYBRID-NEXT:    j .LBB0_1
;
; PURECAP-LABEL: foo:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset csp, csp, -32
; PURECAP-NEXT:    sc cra, 16(csp) # 16-byte Folded Spill
; PURECAP-NEXT:    sc cs0, 0(csp) # 16-byte Folded Spill
; PURECAP-NEXT:    cincoffset cs0, ca0, 4
; PURECAP-NEXT:  .LBB0_1: # %loop
; PURECAP-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-NEXT:    cmove ca0, cs0
; PURECAP-NEXT:    ccall bar
; PURECAP-NEXT:    j .LBB0_1
entry:
  br label %loop

loop:
  %0 = getelementptr inbounds i32, ptr addrspace(200) %a, i64 1
  %1 = load i64, ptr addrspace(200) %b, align 16
  %2 = mul i64 0, %1
  %3 = getelementptr inbounds i32, ptr addrspace(200) %0, i64 %2
  %4 = call i32 @bar(ptr addrspace(200) %3)
  br label %loop
}
