; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/intrinsics.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+cap-mode,+f,+d %s -o - < %s | FileCheck %s --check-prefix=PURECAP
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d -o - < %s | FileCheck %s --check-prefix=HYBRID
; Check that the target-independent CHERI intrinsics are support for all architectures
; The grouping/ordering in this test is based on the RISC-V instruction listing
; in the CHERI ISA specification (Appendix C.1 in ISAv7).

; Capability-Inspection Instructions

declare i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200))
declare i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200))
declare i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200))
declare i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200))
declare i1 @llvm.cheri.cap.tag.get(ptr addrspace(200))
declare i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200))
declare i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200))
declare i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200))
declare i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200))
declare i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200))

define i64 @perms_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: perms_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgetperm a0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: perms_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgetperm a0, ca0
; HYBRID-NEXT:    ret
  %perms = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) %cap)
  ret i64 %perms
}

define i64 @type_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: type_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgettype a0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: type_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgettype a0, ca0
; HYBRID-NEXT:    ret
  %type = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) %cap)
  ret i64 %type
}

define i64 @base_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: base_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgetbase a0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: base_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgetbase a0, ca0
; HYBRID-NEXT:    ret
  %base = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) %cap)
  ret i64 %base
}

define i64 @length_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: length_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgetlen a0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: length_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgetlen a0, ca0
; HYBRID-NEXT:    ret
  %length = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) %cap)
  ret i64 %length
}

define i64 @tag_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: tag_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgettag a0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: tag_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgettag a0, ca0
; HYBRID-NEXT:    ret
  %tag = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) %cap)
  %tag.zext = zext i1 %tag to i64
  ret i64 %tag.zext
}

define i64 @sealed_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: sealed_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgetsealed a0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: sealed_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgetsealed a0, ca0
; HYBRID-NEXT:    ret
  %sealed = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) %cap)
  %sealed.zext = zext i1 %sealed to i64
  ret i64 %sealed.zext
}

define i64 @offset_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: offset_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgetoffset a0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: offset_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgetoffset a0, ca0
; HYBRID-NEXT:    ret
  %offset = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) %cap)
  ret i64 %offset
}

define i64 @flags_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: flags_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgetflags a0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: flags_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgetflags a0, ca0
; HYBRID-NEXT:    ret
  %flags = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) %cap)
  ret i64 %flags
}

define i64 @address_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: address_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    mv a0, a0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: address_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    mv a0, a0
; HYBRID-NEXT:    ret
  %address = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) %cap)
  ret i64 %address
}

define i64 @high_get(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: high_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgethigh a0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: high_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgethigh a0, ca0
; HYBRID-NEXT:    ret
  %high = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) %cap)
  ret i64 %high
}

; Capability-Modification Instructions

declare ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200), ptr addrspace(200))
declare ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200), ptr addrspace(200))
declare ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200), i64)
declare ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200), i64)
declare ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200), i64)
declare ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200), i64)
declare ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200), i64)
declare ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200), i64)
declare ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200), i64)
declare ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200))
declare ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200), ptr addrspace(200))
declare ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200), ptr addrspace(200))
declare ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200), ptr addrspace(200))
declare ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200))

define ptr addrspace(200) @seal(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2) nounwind {
; PURECAP-LABEL: seal:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cseal ca0, ca0, ca1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: seal:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cseal ca0, ca0, ca1
; HYBRID-NEXT:    ret
  %sealed = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)
  ret ptr addrspace(200) %sealed
}

define ptr addrspace(200) @unseal(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2) nounwind {
; PURECAP-LABEL: unseal:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cunseal ca0, ca0, ca1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: unseal:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cunseal ca0, ca0, ca1
; HYBRID-NEXT:    ret
  %unsealed = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)
  ret ptr addrspace(200) %unsealed
}

define ptr addrspace(200) @perms_and(ptr addrspace(200) %cap, i64 %perms) nounwind {
; PURECAP-LABEL: perms_and:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    candperm ca0, ca0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: perms_and:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    candperm ca0, ca0, a1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) %cap, i64 %perms)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @flags_set(ptr addrspace(200) %cap, i64 %flags) nounwind {
; PURECAP-LABEL: flags_set:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    csetflags ca0, ca0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: flags_set:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    csetflags ca0, ca0, a1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) %cap, i64 %flags)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @offset_set(ptr addrspace(200) %cap, i64 %offset) nounwind {
; PURECAP-LABEL: offset_set:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    csetoffset ca0, ca0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: offset_set:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    csetoffset ca0, ca0, a1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) %cap, i64 %offset)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @address_set(ptr addrspace(200) %cap, i64 %address) nounwind {
; PURECAP-LABEL: address_set:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    csetaddr ca0, ca0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: address_set:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    csetaddr ca0, ca0, a1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) %cap, i64 %address)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @bounds_set(ptr addrspace(200) %cap, i64 %bounds) nounwind {
; PURECAP-LABEL: bounds_set:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    csetbounds ca0, ca0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: bounds_set:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    csetbounds ca0, ca0, a1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %cap, i64 %bounds)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @bounds_set_exact(ptr addrspace(200) %cap, i64 %bounds) nounwind {
; PURECAP-LABEL: bounds_set_exact:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    csetboundsexact ca0, ca0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: bounds_set_exact:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    csetboundsexact ca0, ca0, a1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) %cap, i64 %bounds)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @high_set(ptr addrspace(200) %cap, i64 %high) nounwind {
; PURECAP-LABEL: high_set:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    csethigh ca0, ca0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: high_set:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    csethigh ca0, ca0, a1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) %cap, i64 %high)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @bounds_set_immediate(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: bounds_set_immediate:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    csetbounds ca0, ca0, 42
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: bounds_set_immediate:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    csetbounds ca0, ca0, 42
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) %cap, i64 42)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @tag_clear(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: tag_clear:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    ccleartag ca0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: tag_clear:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    ccleartag ca0, ca0
; HYBRID-NEXT:    ret
  %untagged = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) %cap)
  ret ptr addrspace(200) %untagged
}

define ptr addrspace(200) @build(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2) nounwind {
; PURECAP-LABEL: build:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cbuildcap ca0, ca0, ca1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: build:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cbuildcap ca0, ca0, ca1
; HYBRID-NEXT:    ret
  %built = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)
  ret ptr addrspace(200) %built
}

define ptr addrspace(200) @type_copy(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2) nounwind {
; PURECAP-LABEL: type_copy:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    ccopytype ca0, ca0, ca1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: type_copy:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    ccopytype ca0, ca0, ca1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @conditional_seal(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2) nounwind {
; PURECAP-LABEL: conditional_seal:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    ccseal ca0, ca0, ca1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: conditional_seal:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    ccseal ca0, ca0, ca1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @seal_entry(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: seal_entry:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    csealentry ca0, ca0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: seal_entry:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    csealentry ca0, ca0
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) %cap)
  ret ptr addrspace(200) %newcap
}

; Pointer-Arithmetic Instructions

declare i64 @llvm.cheri.cap.to.pointer(ptr addrspace(200), ptr addrspace(200))
declare ptr addrspace(200) @llvm.cheri.cap.from.pointer(ptr addrspace(200), i64)
declare i64 @llvm.cheri.cap.diff(ptr addrspace(200), ptr addrspace(200))
declare ptr addrspace(200) @llvm.cheri.ddc.get()
declare ptr addrspace(200) @llvm.cheri.pcc.get()

define i64 @to_pointer(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2) nounwind {
; PURECAP-LABEL: to_pointer:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgettag a0, ca1
; PURECAP-NEXT:    neg a0, a0
; PURECAP-NEXT:    and a0, a1, a0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: to_pointer:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgettag a0, ca1
; HYBRID-NEXT:    neg a0, a0
; HYBRID-NEXT:    and a0, a1, a0
; HYBRID-NEXT:    ret
  %ptr = call i64 @llvm.cheri.cap.to.pointer(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)
  ret i64 %ptr
}

define i64 @to_pointer_ddc_relative(ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: to_pointer_ddc_relative:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cgettag a1, ca0
; PURECAP-NEXT:    neg a1, a1
; PURECAP-NEXT:    and a0, a0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: to_pointer_ddc_relative:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cgettag a1, ca0
; HYBRID-NEXT:    neg a1, a1
; HYBRID-NEXT:    and a0, a0, a1
; HYBRID-NEXT:    ret
  %ddc = call ptr addrspace(200) @llvm.cheri.ddc.get()
  %ptr = call i64 @llvm.cheri.cap.to.pointer(ptr addrspace(200) %ddc, ptr addrspace(200) %cap)
  ret i64 %ptr
}

define ptr addrspace(200) @from_pointer(ptr addrspace(200) %cap, i64 %ptr) nounwind {
; PURECAP-LABEL: from_pointer:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    bnez a1, .LBB27_2
; PURECAP-NEXT:  # %bb.1:
; PURECAP-NEXT:    cmove ca0, cnull
; PURECAP-NEXT:    ret
; PURECAP-NEXT:  .LBB27_2:
; PURECAP-NEXT:    csetaddr ca0, ca0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: from_pointer:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    bnez a1, .LBB27_2
; HYBRID-NEXT:  # %bb.1:
; HYBRID-NEXT:    cmove ca0, cnull
; HYBRID-NEXT:    ret
; HYBRID-NEXT:  .LBB27_2:
; HYBRID-NEXT:    csetaddr ca0, ca0, a1
; HYBRID-NEXT:    ret
  %newcap = call ptr addrspace(200) @llvm.cheri.cap.from.pointer(ptr addrspace(200) %cap, i64 %ptr)
  ret ptr addrspace(200) %newcap
}

define ptr addrspace(200) @from_ddc(i64 %ptr) nounwind {
; PURECAP-LABEL: from_ddc:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cspecialr ca1, ddc
; PURECAP-NEXT:    bnez a0, .LBB28_2
; PURECAP-NEXT:  # %bb.1:
; PURECAP-NEXT:    cmove ca0, cnull
; PURECAP-NEXT:    ret
; PURECAP-NEXT:  .LBB28_2:
; PURECAP-NEXT:    csetaddr ca0, ca1, a0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: from_ddc:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cspecialr ca1, ddc
; HYBRID-NEXT:    bnez a0, .LBB28_2
; HYBRID-NEXT:  # %bb.1:
; HYBRID-NEXT:    cmove ca0, cnull
; HYBRID-NEXT:    ret
; HYBRID-NEXT:  .LBB28_2:
; HYBRID-NEXT:    csetaddr ca0, ca1, a0
; HYBRID-NEXT:    ret
  %ddc = call ptr addrspace(200) @llvm.cheri.ddc.get()
  %cap = call ptr addrspace(200) @llvm.cheri.cap.from.pointer(ptr addrspace(200) %ddc, i64 %ptr)
  ret ptr addrspace(200) %cap
}

define i64 @diff(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2) nounwind {
; PURECAP-LABEL: diff:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    sub a0, a0, a1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: diff:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    sub a0, a0, a1
; HYBRID-NEXT:    ret
  %diff = call i64 @llvm.cheri.cap.diff(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)
  ret i64 %diff
}

define ptr addrspace(200) @ddc_get() nounwind {
; PURECAP-LABEL: ddc_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cspecialr ca0, ddc
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: ddc_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cspecialr ca0, ddc
; HYBRID-NEXT:    ret
  %cap = call ptr addrspace(200) @llvm.cheri.ddc.get()
  ret ptr addrspace(200) %cap
}

define ptr addrspace(200) @pcc_get() nounwind {
; PURECAP-LABEL: pcc_get:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    auipcc ca0, 0
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: pcc_get:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cspecialr ca0, pcc
; HYBRID-NEXT:    ret
  %cap = call ptr addrspace(200) @llvm.cheri.pcc.get()
  ret ptr addrspace(200) %cap
}

; Assertion Instructions

declare i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)

define i64 @subset_test(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2) nounwind {
; PURECAP-LABEL: subset_test:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    ctestsubset a0, ca0, ca1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: subset_test:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    ctestsubset a0, ca0, ca1
; HYBRID-NEXT:    ret
  %subset = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)
  %subset.zext = zext i1 %subset to i64
  ret i64 %subset.zext
}

declare i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)

define i64 @equal_exact(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2) nounwind {
; PURECAP-LABEL: equal_exact:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cseqx a0, ca0, ca1
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: equal_exact:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cseqx a0, ca0, ca1
; HYBRID-NEXT:    ret
  %eqex = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) %cap1, ptr addrspace(200) %cap2)
  %eqex.zext = zext i1 %eqex to i64
  ret i64 %eqex.zext
}
