; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/machinelicm-hoist-csetbounds.ll
; Previously LLVM would hoist CSetBounds instructions out of if conditions/loops
; even if the source pointer could be NULL. On MIPS and RISC-V this results in a
; tag violation so we must ensure that the CSetBounds happens after the NULL check.

; Note: Opt correctly hoists the condition+csetbounds into a preheader, and LLC
; used to unconditionally hoist the csetbounds.
; RUN: opt -data-layout="e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n64-S128-A200-P200-G200" -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+cap-mode,+f,+d "-passes=default<O3>" -S < %s | FileCheck %s --check-prefix=HOIST-OPT
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+cap-mode,+f,+d -O3 < %s | FileCheck %s

; Generated from the following C code (with subobject bounds):
; struct foo {
;     int src;
;     int dst;
; };
;
; void call(int* src, int* dst);
;
; void hoist_csetbounds(int cond, struct foo* f) {
;     for (int i = 0; i < 100; i++) {
;         if (f) {
;             call(&f->src, &f->dst);
;         }
;     }
; }

%struct.foo = type { i32, i32 }
declare dso_local void @call(ptr addrspace(200), ptr addrspace(200)) local_unnamed_addr addrspace(200) nounwind
declare ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200), i64) addrspace(200) nounwind readnone willreturn

define dso_local void @hoist_csetbounds(i32 signext %cond, ptr addrspace(200) %f) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: hoist_csetbounds:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -96
; CHECK-NEXT:    sc cra, 80(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs0, 64(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs1, 48(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs2, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs3, 16(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs4, 0(csp) # 16-byte Folded Spill
; CHECK-NEXT:    cmove cs0, ca1
; CHECK-NEXT:    cincoffset ca0, ca1, 4
; CHECK-NEXT:    li s3, -1
; CHECK-NEXT:    li s4, 99
; CHECK-NEXT:    csetbounds cs1, ca1, 4
; CHECK-NEXT:    csetbounds cs2, ca0, 4
; CHECK-NEXT:    j .LBB0_2
; CHECK-NEXT:  .LBB0_1: # %for.inc
; CHECK-NEXT:    # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    addiw s3, s3, 1
; CHECK-NEXT:    bgeu s3, s4, .LBB0_4
; CHECK-NEXT:  .LBB0_2: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    beqz s0, .LBB0_1
; CHECK-NEXT:  # %bb.3: # %if.then
; CHECK-NEXT:    # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    cmove ca0, cs1
; CHECK-NEXT:    cmove ca1, cs2
; CHECK-NEXT:    ccall call
; CHECK-NEXT:    j .LBB0_1
; CHECK-NEXT:  .LBB0_4: # %for.cond.cleanup
; CHECK-NEXT:    lc cra, 80(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs0, 64(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs1, 48(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs2, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs3, 16(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs4, 0(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 96
; CHECK-NEXT:    ret
; HOIST-OPT-LABEL: define dso_local void @hoist_csetbounds
; HOIST-OPT-SAME: (i32 signext [[COND:%.*]], ptr addrspace(200) [[F:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; HOIST-OPT-NEXT:  entry:
; HOIST-OPT-NEXT:    [[TOBOOL:%.*]] = icmp eq ptr addrspace(200) [[F]], null
; HOIST-OPT-NEXT:    br i1 [[TOBOOL]], label [[FOR_COND_CLEANUP:%.*]], label [[ENTRY_SPLIT:%.*]]
; HOIST-OPT:       entry.split:
; HOIST-OPT-NEXT:    [[DST:%.*]] = getelementptr inbounds [[STRUCT_FOO:%.*]], ptr addrspace(200) [[F]], i64 0, i32 1
; HOIST-OPT-NEXT:    [[ADDRESS_WITH_BOUNDS:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull [[F]], i64 4)
; HOIST-OPT-NEXT:    [[ADDRESS_WITH_BOUNDS1:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull [[DST]], i64 4)
; HOIST-OPT-NEXT:    br label [[FOR_BODY:%.*]]
; HOIST-OPT:       for.cond.cleanup:
; HOIST-OPT-NEXT:    ret void
; HOIST-OPT:       for.body:
; HOIST-OPT-NEXT:    [[I_06:%.*]] = phi i32 [ 0, [[ENTRY_SPLIT]] ], [ [[INC:%.*]], [[FOR_BODY]] ]
; HOIST-OPT-NEXT:    tail call void @call(ptr addrspace(200) [[ADDRESS_WITH_BOUNDS]], ptr addrspace(200) [[ADDRESS_WITH_BOUNDS1]])
; HOIST-OPT-NEXT:    [[INC]] = add nuw nsw i32 [[I_06]], 1
; HOIST-OPT-NEXT:    [[CMP:%.*]] = icmp ult i32 [[I_06]], 99
; HOIST-OPT-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_COND_CLEANUP]]
;
entry:
  %tobool = icmp eq ptr addrspace(200) %f, null
  %dst = getelementptr inbounds %struct.foo, ptr addrspace(200) %f, i64 0, i32 1
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.inc
  ret void

for.body:                                         ; preds = %for.inc, %entry
  %i.06 = phi i32 [ 0, %entry ], [ %inc, %for.inc ]
  br i1 %tobool, label %for.inc, label %if.then

if.then:                                          ; preds = %for.body
  %address.with.bounds = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull %f, i64 4)
  %address.with.bounds1 = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull %dst, i64 4)
  call void @call(ptr addrspace(200) %address.with.bounds, ptr addrspace(200) %address.with.bounds1)
  br label %for.inc

for.inc:                                          ; preds = %if.then, %for.body
  %inc = add nuw nsw i32 %i.06, 1
  %cmp = icmp ult i32 %i.06, 99
  br i1 %cmp, label %for.body, label %for.cond.cleanup
}
