; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/memcpy-no-preserve-tags-attr.ll
; Check that the no_preserve_tags annotation on memcpy/memmove intrinsics allows
; use to inline struct copies >= capability size.
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+cap-mode,+f,+d -o - < %s | FileCheck %s

%struct.pair = type { i64, i64 }

; Function Attrs: argmemonly nounwind
declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) nocapture writeonly, ptr addrspace(200) nocapture readonly, i64, i1)
declare void @llvm.memmove.p200.p200.i64(ptr addrspace(200) nocapture writeonly, ptr addrspace(200) nocapture readonly, i64, i1)

; Without a no_preserve_tags attribute we always call memcpy. In this case we
; don't know whether the type might actually contain capabilities (e.g. unions).
define void @memcpy_no_attr(ptr addrspace(200) %a, ptr addrspace(200) %b) addrspace(200) nounwind {
; CHECK-LABEL: memcpy_no_attr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -16
; CHECK-NEXT:    sc cra, 0(csp) # 16-byte Folded Spill
; CHECK-NEXT:    li a2, 16
; CHECK-NEXT:    ccall memcpy
; CHECK-NEXT:    lc cra, 0(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 16
; CHECK-NEXT:    ret
entry:
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 8 %a, ptr addrspace(200) align 8 %b, i64 16, i1 false)
  ret void
}

define void @memmove_no_attr(ptr addrspace(200) %a, ptr addrspace(200) %b) addrspace(200) nounwind {
; CHECK-LABEL: memmove_no_attr:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -16
; CHECK-NEXT:    sc cra, 0(csp) # 16-byte Folded Spill
; CHECK-NEXT:    li a2, 16
; CHECK-NEXT:    ccall memmove
; CHECK-NEXT:    lc cra, 0(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 16
; CHECK-NEXT:    ret
entry:
  call void @llvm.memmove.p200.p200.i64(ptr addrspace(200) align 8 %a, ptr addrspace(200) align 8 %b, i64 16, i1 false)
  ret void
}

; We have to emit a call if the intrinsic has must_preserve_cheri_tags:
define void @memcpy_must_preserve(ptr addrspace(200) %a, ptr addrspace(200) %b) addrspace(200) nounwind {
; CHECK-LABEL: memcpy_must_preserve:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -16
; CHECK-NEXT:    sc cra, 0(csp) # 16-byte Folded Spill
; CHECK-NEXT:    li a2, 16
; CHECK-NEXT:    ccall memcpy
; CHECK-NEXT:    lc cra, 0(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 16
; CHECK-NEXT:    ret
entry:
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 8 %a, ptr addrspace(200) align 8 %b, i64 16, i1 false) must_preserve_cheri_tags
  ret void
}

define void @memmove_must_preserve(ptr addrspace(200) %a, ptr addrspace(200) %b) addrspace(200) nounwind {
; CHECK-LABEL: memmove_must_preserve:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -16
; CHECK-NEXT:    sc cra, 0(csp) # 16-byte Folded Spill
; CHECK-NEXT:    li a2, 16
; CHECK-NEXT:    ccall memmove
; CHECK-NEXT:    lc cra, 0(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 16
; CHECK-NEXT:    ret
entry:
  call void @llvm.memmove.p200.p200.i64(ptr addrspace(200) align 8 %a, ptr addrspace(200) align 8 %b, i64 16, i1 false) must_preserve_cheri_tags
  ret void
}

; We should be able to inline the call memcpy/memmove if the intrinsic has no_preserve_cheri_tags:
define void @memcpy_no_preserve(ptr addrspace(200) %a, ptr addrspace(200) %b) addrspace(200) nounwind {
; CHECK-LABEL: memcpy_no_preserve:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 8(ca1)
; CHECK-NEXT:    sd a2, 8(ca0)
; CHECK-NEXT:    ld a1, 0(ca1)
; CHECK-NEXT:    sd a1, 0(ca0)
; CHECK-NEXT:    ret
entry:
  call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 8 %a, ptr addrspace(200) align 8 %b, i64 16, i1 false) no_preserve_cheri_tags
  ret void
}

define void @memmove_no_preserve(ptr addrspace(200) %a, ptr addrspace(200) %b) addrspace(200) nounwind {
; CHECK-LABEL: memmove_no_preserve:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ld a2, 8(ca1)
; CHECK-NEXT:    ld a1, 0(ca1)
; CHECK-NEXT:    sd a2, 8(ca0)
; CHECK-NEXT:    sd a1, 0(ca0)
; CHECK-NEXT:    ret
entry:
  call void @llvm.memmove.p200.p200.i64(ptr addrspace(200) align 8 %a, ptr addrspace(200) align 8 %b, i64 16, i1 false) no_preserve_cheri_tags
  ret void
}
