; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes --force-update
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/trunc-load.ll
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+cap-mode,+f,+d %s -o - < %s | FileCheck %s --check-prefix=PURECAP
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d -o - < %s | FileCheck %s --check-prefix=HYBRID

define zeroext i16 @trunc_load_zext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_load_zext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clwu a0, 0(ca0)
; PURECAP-NEXT:    lui a1, 16
; PURECAP-NEXT:    addiw a1, a1, -1
; PURECAP-NEXT:    and a0, a0, a1
; PURECAP-NEXT:    cret
;
; HYBRID-LABEL: trunc_load_zext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    lwu.cap a0, (ca0)
; HYBRID-NEXT:    lui a1, 16
; HYBRID-NEXT:    addiw a1, a1, -1
; HYBRID-NEXT:    and a0, a0, a1
; HYBRID-NEXT:    ret
  %1 = load i32, i32 addrspace(200)* %p
  %2 = trunc i32 %1 to i16
  ret i16 %2
}

define signext i16 @trunc_load_sext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_load_sext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clw a0, 0(ca0)
; PURECAP-NEXT:    slli a0, a0, 48
; PURECAP-NEXT:    srai a0, a0, 48
; PURECAP-NEXT:    cret
;
; HYBRID-LABEL: trunc_load_sext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    lw.cap a0, (ca0)
; HYBRID-NEXT:    slli a0, a0, 48
; HYBRID-NEXT:    srai a0, a0, 48
; HYBRID-NEXT:    ret
  %1 = load i32, i32 addrspace(200)* %p
  %2 = trunc i32 %1 to i16
  ret i16 %2
}

define zeroext i16 @trunc_load_gep_zext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_load_gep_zext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clwu a0, 4(ca0)
; PURECAP-NEXT:    lui a1, 16
; PURECAP-NEXT:    addiw a1, a1, -1
; PURECAP-NEXT:    and a0, a0, a1
; PURECAP-NEXT:    cret
;
; HYBRID-LABEL: trunc_load_gep_zext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cincoffset ca0, ca0, 4
; HYBRID-NEXT:    lwu.cap a0, (ca0)
; HYBRID-NEXT:    lui a1, 16
; HYBRID-NEXT:    addiw a1, a1, -1
; HYBRID-NEXT:    and a0, a0, a1
; HYBRID-NEXT:    ret
  %1 = getelementptr i32, i32 addrspace(200)* %p, i64 1
  %2 = load i32, i32 addrspace(200)* %1
  %3 = trunc i32 %2 to i16
  ret i16 %3
}

define signext i16 @trunc_load_gep_sext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_load_gep_sext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clw a0, 4(ca0)
; PURECAP-NEXT:    slli a0, a0, 48
; PURECAP-NEXT:    srai a0, a0, 48
; PURECAP-NEXT:    cret
;
; HYBRID-LABEL: trunc_load_gep_sext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    cincoffset ca0, ca0, 4
; HYBRID-NEXT:    lw.cap a0, (ca0)
; HYBRID-NEXT:    slli a0, a0, 48
; HYBRID-NEXT:    srai a0, a0, 48
; HYBRID-NEXT:    ret
  %1 = getelementptr i32, i32 addrspace(200)* %p, i64 1
  %2 = load i32, i32 addrspace(200)* %1
  %3 = trunc i32 %2 to i16
  ret i16 %3
}

define zeroext i16 @trunc_lshr_load_zext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_lshr_load_zext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clwu a0, 0(ca0)
; PURECAP-NEXT:    srli a0, a0, 16
; PURECAP-NEXT:    cret
;
; HYBRID-LABEL: trunc_lshr_load_zext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    lwu.cap a0, (ca0)
; HYBRID-NEXT:    srli a0, a0, 16
; HYBRID-NEXT:    ret
  %1 = load i32, i32 addrspace(200)* %p
  %2 = lshr i32 %1, 16
  %3 = trunc i32 %2 to i16
  ret i16 %3
}

define signext i16 @trunc_lshr_load_sext(i32 addrspace(200)* %p) {
; PURECAP-LABEL: trunc_lshr_load_sext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clwu a0, 0(ca0)
; PURECAP-NEXT:    sraiw a0, a0, 16
; PURECAP-NEXT:    cret
;
; HYBRID-LABEL: trunc_lshr_load_sext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    lwu.cap a0, (ca0)
; HYBRID-NEXT:    sraiw a0, a0, 16
; HYBRID-NEXT:    ret
  %1 = load i32, i32 addrspace(200)* %p
  %2 = lshr i32 %1, 16
  %3 = trunc i32 %2 to i16
  ret i16 %3
}
