; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 4
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/cap-from-ptr.ll
;; Check that we can correctly generate code for llvm.cheri.cap.from.pointer()
;; This previously asserted on RISC-V due to a broken ISel pattern.
;; We pipe this input through instcombine first to ensure SelectionDAG sees canonical IR.
; RUN: opt -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -passes=instcombine -S < %s | FileCheck %s --check-prefix=CHECK-IR
; RUN: opt -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -passes=instcombine -S < %s | llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap | FileCheck %s --check-prefix=PURECAP
; RUN: opt -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 -passes=instcombine -S < %s | llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 | FileCheck %s --check-prefix=HYBRID

define internal ptr addrspace(200) @test(ptr addrspace(200) %ptr, ptr addrspace(200) %cap, i64 %offset) nounwind {
; PURECAP-LABEL: test:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cfromptr $c1, $c4, $4
; PURECAP-NEXT:    csc $c1, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cmove $c3, $c1
;
; HYBRID-LABEL: test:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    cfromptr $c1, $c4, $4
; HYBRID-NEXT:    csc $c1, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    cmove $c3, $c1
; CHECK-IR-LABEL: define internal ptr addrspace(200) @test(
; CHECK-IR-SAME: ptr addrspace(200) [[PTR:%.*]], ptr addrspace(200) [[CAP:%.*]], i64 [[OFFSET:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-IR-NEXT:  entry:
; CHECK-IR-NEXT:    [[NEW:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[CAP]], i64 [[OFFSET]])
; CHECK-IR-NEXT:    store ptr addrspace(200) [[NEW]], ptr addrspace(200) [[PTR]], align 16
; CHECK-IR-NEXT:    ret ptr addrspace(200) [[NEW]]
;
entry:
  %new = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) %cap, i64 %offset)
  store ptr addrspace(200) %new, ptr addrspace(200) %ptr, align 16
  ret ptr addrspace(200) %new
}

;; (int_cheri_cap_from_ptr x, 0) -> null
define internal ptr addrspace(200) @cap_from_ptr_zero(ptr addrspace(200) %ptr, ptr addrspace(200) %cap) nounwind {
; PURECAP-LABEL: cap_from_ptr_zero:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cgetnull $c3
;
; HYBRID-LABEL: cap_from_ptr_zero:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    csc $cnull, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    cgetnull $c3
; CHECK-IR-LABEL: define internal ptr addrspace(200) @cap_from_ptr_zero(
; CHECK-IR-SAME: ptr addrspace(200) [[PTR:%.*]], ptr addrspace(200) [[CAP:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-IR-NEXT:  entry:
; CHECK-IR-NEXT:    store ptr addrspace(200) null, ptr addrspace(200) [[PTR]], align 16
; CHECK-IR-NEXT:    ret ptr addrspace(200) null
;
entry:
  %new = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) %cap, i64 0)
  store ptr addrspace(200) %new, ptr addrspace(200) %ptr, align 16
  ret ptr addrspace(200) %new
}

;; Check that (int_cheri_cap_from_ptr ddc, x) can use the DDC register directly
define internal ptr addrspace(200) @cap_from_ptr_ddc(ptr addrspace(200) %ptr, i64 %offset) nounwind {
; PURECAP-LABEL: cap_from_ptr_ddc:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cfromddc $c1, $4
; PURECAP-NEXT:    csc $c1, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cmove $c3, $c1
;
; HYBRID-LABEL: cap_from_ptr_ddc:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    cfromddc $c1, $4
; HYBRID-NEXT:    csc $c1, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    cmove $c3, $c1
; CHECK-IR-LABEL: define internal ptr addrspace(200) @cap_from_ptr_ddc(
; CHECK-IR-SAME: ptr addrspace(200) [[PTR:%.*]], i64 [[OFFSET:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-IR-NEXT:  entry:
; CHECK-IR-NEXT:    [[DDC:%.*]] = call ptr addrspace(200) @llvm.cheri.ddc.get()
; CHECK-IR-NEXT:    [[NEW:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[DDC]], i64 [[OFFSET]])
; CHECK-IR-NEXT:    store ptr addrspace(200) [[NEW]], ptr addrspace(200) [[PTR]], align 16
; CHECK-IR-NEXT:    ret ptr addrspace(200) [[NEW]]
;
entry:
  %ddc = call ptr addrspace(200) @llvm.cheri.ddc.get()
  %new = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) %ddc, i64 %offset)
  store ptr addrspace(200) %new, ptr addrspace(200) %ptr, align 16
  ret ptr addrspace(200) %new
}

;; Check that (int_cheri_cap_from_ptr x, 0) -> null has priority over direct DDC usage
define internal ptr addrspace(200) @cap_from_ptr_ddc_zero(ptr addrspace(200) %ptr) nounwind {
; PURECAP-LABEL: cap_from_ptr_ddc_zero:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    csc $cnull, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cgetnull $c3
;
; HYBRID-LABEL: cap_from_ptr_ddc_zero:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    csc $cnull, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    cgetnull $c3
; CHECK-IR-LABEL: define internal ptr addrspace(200) @cap_from_ptr_ddc_zero(
; CHECK-IR-SAME: ptr addrspace(200) [[PTR:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-IR-NEXT:  entry:
; CHECK-IR-NEXT:    store ptr addrspace(200) null, ptr addrspace(200) [[PTR]], align 16
; CHECK-IR-NEXT:    ret ptr addrspace(200) null
;
entry:
  %ddc = call ptr addrspace(200) @llvm.cheri.ddc.get()
  %new = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) %ddc, i64 0)
  store ptr addrspace(200) %new, ptr addrspace(200) %ptr, align 16
  ret ptr addrspace(200) %new
}

;; Check that (int_cheri_cap_from_ptr null, x) does not use register zero (since that is DDC)
define internal ptr addrspace(200) @cap_from_ptr_null(ptr addrspace(200) %ptr, i64 %offset) nounwind {
; PURECAP-LABEL: cap_from_ptr_null:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cgetnull $c1
; PURECAP-NEXT:    cfromptr $c1, $c1, $4
; PURECAP-NEXT:    csc $c1, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cmove $c3, $c1
;
; HYBRID-LABEL: cap_from_ptr_null:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    cgetnull $c1
; HYBRID-NEXT:    cfromptr $c1, $c1, $4
; HYBRID-NEXT:    csc $c1, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    cmove $c3, $c1
; CHECK-IR-LABEL: define internal ptr addrspace(200) @cap_from_ptr_null(
; CHECK-IR-SAME: ptr addrspace(200) [[PTR:%.*]], i64 [[OFFSET:%.*]]) addrspace(200) #[[ATTR0]] {
; CHECK-IR-NEXT:  entry:
; CHECK-IR-NEXT:    [[NEW:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) null, i64 [[OFFSET]])
; CHECK-IR-NEXT:    store ptr addrspace(200) [[NEW]], ptr addrspace(200) [[PTR]], align 16
; CHECK-IR-NEXT:    ret ptr addrspace(200) [[NEW]]
;
entry:
  %new = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) null, i64 %offset)
  store ptr addrspace(200) %new, ptr addrspace(200) %ptr, align 16
  ret ptr addrspace(200) %new
}

declare ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200), i64)
declare ptr addrspace(200) @llvm.cheri.ddc.get()
