; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/memcpy-zeroinit.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap < %s -o - | FileCheck %s
; Check that the copy from the zeroinitializer global is turned into a series of zero stores
; or memset() as long as the memcpy is not volatile:

%struct.umutex = type { i32, i32, [2 x i32], ptr addrspace(200), i32, [2 x i32] }

@_thr_umutex_init.default_mtx = internal addrspace(200) constant %struct.umutex zeroinitializer, align 16

define void @_thr_umutex_init(ptr addrspace(200) %mtx) local_unnamed_addr addrspace(200) nounwind "frame-pointer"="none" {
; CHECK-LABEL: _thr_umutex_init:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csc $cnull, $zero, 0($c3)
; CHECK-NEXT:    csc $cnull, $zero, 32($c3)
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    csc $cnull, $zero, 16($c3)
  tail call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 %mtx, ptr addrspace(200) align 16 @_thr_umutex_init.default_mtx, i64 48, i1 false)
  ret void
}

define void @_thr_umutex_init_volatile(ptr addrspace(200) %mtx) local_unnamed_addr addrspace(200) nounwind "frame-pointer"="none" {
; CHECK-LABEL: _thr_umutex_init_volatile:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; CHECK-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; CHECK-NEXT:    cgetpccincoffset $c1, $1
; CHECK-NEXT:    clcbi $c1, %captab20(_thr_umutex_init.default_mtx)($c1)
; CHECK-NEXT:    clc $c2, $zero, 0($c1)
; CHECK-NEXT:    csc $c2, $zero, 0($c3)
; CHECK-NEXT:    clc $c2, $zero, 32($c1)
; CHECK-NEXT:    csc $c2, $zero, 32($c3)
; CHECK-NEXT:    clc $c1, $zero, 16($c1)
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    csc $c1, $zero, 16($c3)
  tail call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 %mtx, ptr addrspace(200) align 16 @_thr_umutex_init.default_mtx, i64 48, i1 true)
  ret void
}

declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noalias nocapture writeonly %0, ptr addrspace(200) noalias nocapture readonly %1, i64 %2, i1 immarg %3) addrspace(200)
