; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/ptrtoint.ll
;; Check that we can correctly generate code for ptrtoint and perform simple folds
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap < %s | FileCheck %s
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 < %s | FileCheck %s --check-prefix=HYBRID

define internal i64 @ptrtoint(ptr addrspace(200) %cap) addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    cgetaddr $2, $c3
;
; HYBRID-LABEL: ptrtoint:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    ctoptr $2, $c3, $ddc
  %ret = ptrtoint ptr addrspace(200) %cap to i64
  ret i64 %ret
}

define internal i64 @ptrtoint_plus_const(ptr addrspace(200) %cap) addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_plus_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cgetaddr $1, $c3
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    daddiu $2, $1, 2
;
; HYBRID-LABEL: ptrtoint_plus_const:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    ctoptr $1, $c3, $ddc
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddiu $2, $1, 2
  %zero = ptrtoint ptr addrspace(200) %cap to i64
  %ret = add i64 %zero, 2
  ret i64 %ret
}

define internal i64 @ptrtoint_plus_var(ptr addrspace(200) %cap, i64 %add) addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_plus_var:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cgetaddr $1, $c3
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    daddu $2, $1, $4
;
; HYBRID-LABEL: ptrtoint_plus_var:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    ctoptr $1, $c3, $ddc
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddu $2, $1, $4
  %zero = ptrtoint ptr addrspace(200) %cap to i64
  %ret = add i64 %zero, %add
  ret i64 %ret
}

define internal i64 @ptrtoint_null() addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_null:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    cgetaddr $2, $cnull
;
; HYBRID-LABEL: ptrtoint_null:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    ctoptr $2, $cnull, $ddc
  %ret = ptrtoint ptr addrspace(200) null to i64
  ret i64 %ret
}

define internal i64 @ptrtoint_null_plus_const() addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_null_plus_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cgetaddr $1, $cnull
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    daddiu $2, $1, 2
;
; HYBRID-LABEL: ptrtoint_null_plus_const:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    ctoptr $1, $cnull, $ddc
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddiu $2, $1, 2
  %zero = ptrtoint ptr addrspace(200) null to i64
  %ret = add i64 %zero, 2
  ret i64 %ret
}

define internal i64 @ptrtoint_null_plus_var(i64 %add) addrspace(200) nounwind {
; CHECK-LABEL: ptrtoint_null_plus_var:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cgetaddr $1, $cnull
; CHECK-NEXT:    cjr $c17
; CHECK-NEXT:    daddu $2, $1, $4
;
; HYBRID-LABEL: ptrtoint_null_plus_var:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    ctoptr $1, $cnull, $ddc
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    daddu $2, $1, $4
  %zero = ptrtoint ptr addrspace(200) null to i64
  %ret = add i64 %zero, %add
  ret i64 %ret
}
