; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/trunc-load.ll
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap %s -o - < %s | FileCheck %s --check-prefix=PURECAP
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi n64 -o - < %s | FileCheck %s --check-prefix=HYBRID

define zeroext i16 @trunc_load_zext(ptr addrspace(200) %p) {
; PURECAP-LABEL: trunc_load_zext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clhu $2, $zero, 2($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    nop
;
; HYBRID-LABEL: trunc_load_zext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    clhu $2, $zero, 2($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    nop
  %1 = load i32, ptr addrspace(200) %p
  %2 = trunc i32 %1 to i16
  ret i16 %2
}

define signext i16 @trunc_load_sext(ptr addrspace(200) %p) {
; PURECAP-LABEL: trunc_load_sext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clh $2, $zero, 2($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    nop
;
; HYBRID-LABEL: trunc_load_sext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    clh $2, $zero, 2($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    nop
  %1 = load i32, ptr addrspace(200) %p
  %2 = trunc i32 %1 to i16
  ret i16 %2
}

define zeroext i16 @trunc_load_gep_zext(ptr addrspace(200) %p) {
; PURECAP-LABEL: trunc_load_gep_zext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clhu $2, $zero, 6($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    nop
;
; HYBRID-LABEL: trunc_load_gep_zext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    clhu $2, $zero, 6($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    nop
  %1 = getelementptr i32, ptr addrspace(200) %p, i64 1
  %2 = load i32, ptr addrspace(200) %1
  %3 = trunc i32 %2 to i16
  ret i16 %3
}

define signext i16 @trunc_load_gep_sext(ptr addrspace(200) %p) {
; PURECAP-LABEL: trunc_load_gep_sext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clh $2, $zero, 6($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    nop
;
; HYBRID-LABEL: trunc_load_gep_sext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    clh $2, $zero, 6($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    nop
  %1 = getelementptr i32, ptr addrspace(200) %p, i64 1
  %2 = load i32, ptr addrspace(200) %1
  %3 = trunc i32 %2 to i16
  ret i16 %3
}

define zeroext i16 @trunc_lshr_load_zext(ptr addrspace(200) %p) {
; PURECAP-LABEL: trunc_lshr_load_zext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clhu $2, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    nop
;
; HYBRID-LABEL: trunc_lshr_load_zext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    clhu $2, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    nop
  %1 = load i32, ptr addrspace(200) %p
  %2 = lshr i32 %1, 16
  %3 = trunc i32 %2 to i16
  ret i16 %3
}

define signext i16 @trunc_lshr_load_sext(ptr addrspace(200) %p) {
; PURECAP-LABEL: trunc_lshr_load_sext:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    clh $2, $zero, 0($c3)
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    nop
;
; HYBRID-LABEL: trunc_lshr_load_sext:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    clh $2, $zero, 0($c3)
; HYBRID-NEXT:    jr $ra
; HYBRID-NEXT:    nop
  %1 = load i32, ptr addrspace(200) %p
  %2 = lshr i32 %1, 16
  %3 = trunc i32 %2 to i16
  ret i16 %3
}
