; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=ipsccp -o - -S < %s | FileCheck %s
; RUN: opt -passes=gvn -o - -S < %s | FileCheck %s
; RUN: opt -passes=newgvn -o - -S < %s | FileCheck %s
target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "riscv64-codasip-linux-gnu"

; Function Attrs: noinline nounwind
define dso_local signext i32 @f(ptr addrspace(200) noundef %p) addrspace(200) #0 {
; CHECK-LABEL: define dso_local signext i32 @f
; CHECK-SAME: (ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP:%.*]] = icmp ne ptr addrspace(200) [[P]], getelementptr (i8, ptr addrspace(200) null, i64 4294967296)
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_END:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    br label [[RETURN:%.*]]
; CHECK:       if.end:
; CHECK-NEXT:    call void @doit(ptr addrspace(200) noundef [[P]])
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 1, [[IF_THEN]] ], [ 0, [[IF_END]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %cmp = icmp ne ptr addrspace(200) %p, getelementptr (i8, ptr addrspace(200) null, i64 4294967296)
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  br label %return

if.end:                                           ; preds = %entry
  call void @doit(ptr addrspace(200) noundef %p)
  br label %return

return:                                           ; preds = %if.end, %if.then
  %retval.0 = phi i32 [ 1, %if.then ], [ 0, %if.end ]
  ret i32 %retval.0
}

declare void @doit(ptr addrspace(200) noundef) addrspace(200) #1

attributes #0 = { noinline nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+64bit,+cap-mode,+zcherihybrid,+zcheripurecap" }
attributes #1 = { "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+64bit,+cap-mode,+zcherihybrid,+zcheripurecap" }

