; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/dagcombine-ptradd-deleted-regression.ll
; This would previously crash DAGCombiner::visitPTRADD since the PTRADD
; corresponding to the second GEP would be collapsed to a no-op when
; reassociated and delete the synthesised PTRADD node, not just the ADD, which
; the folding code was not prepared for.
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+zcheripurecap,+zcherihybrid,+f %s -o - | FileCheck %s --check-prefix=HYBRID
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+zcheripurecap,+cap-mode,+f %s -o - | FileCheck %s --check-prefix=PURECAP
declare i32 @bar(i32 addrspace(200)*)
define internal i32 @foo(i32 addrspace(200)* %a, i32 addrspace(200)* %b) nounwind {
; HYBRID-LABEL: foo:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; HYBRID-NEXT:    caddi ca0, ca0, 4
; HYBRID-NEXT:    sc ca0, 0(sp) # 8-byte Folded Spill
; HYBRID-NEXT:  .LBB0_1: # %loop
; HYBRID-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-NEXT:    lc ca0, 0(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    call bar@plt
; HYBRID-NEXT:    j .LBB0_1
;
; PURECAP-LABEL: foo:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    caddi csp, csp, -16
; PURECAP-NEXT:    sc cra, 8(csp) # 8-byte Folded Spill
; PURECAP-NEXT:    sc cs0, 0(csp) # 8-byte Folded Spill
; PURECAP-NEXT:    caddi cs0, ca0, 4
; PURECAP-NEXT:  .LBB0_1: # %loop
; PURECAP-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-NEXT:    cmv ca0, cs0
; PURECAP-NEXT:    call bar
; PURECAP-NEXT:    j .LBB0_1
entry:
  br label %loop
loop:
  %0 = getelementptr inbounds i32, i32 addrspace(200)* %a, i32 1
  %1 = load i32, i32 addrspace(200)* %b, align 16
  %2 = mul i32 0, %1
  %3 = getelementptr inbounds i32, i32 addrspace(200)* %0, i32 %2
  %4 = call i32 @bar(i32 addrspace(200)* %3)
  br label %loop
}
