; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/machinelicm-hoist-csetbounds.ll
; Previously LLVM would hoist CSetBounds instructions out of if conditions/loops
; even if the source pointer could be NULL. On MIPS and RISC-V this results in a
; tag violation so we must ensure that the CSetBounds happens after the NULL check.
; Note: Opt correctly hoists the condition+csetbounds into a preheader, and LLC
; used to unconditionally hoist the csetbounds.
; RUN: opt -data-layout="e-m:e-pf200:64:64:64:32-p:32:32-i64:64-n32-S128-A200-P200-G200" -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+zcheripurecap,+cap-mode,+f "-passes=default<O3>" -S < %s | FileCheck %s --check-prefix=HOIST-OPT
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+zcheripurecap,+cap-mode,+f -O3 < %s | FileCheck %s
; Generated from the following C code (with subobject bounds):
; struct foo {
; int src;
; int dst;
; };
;
; void call(int* src, int* dst);
;
; void hoist_csetbounds(int cond, struct foo* f) {
; for (int i = 0; i < 100; i++) {
; if (f) {
; call(&f->src, &f->dst);
; }
; }
; }
%struct.foo = type { i32, i32 }
declare dso_local void @call(ptr addrspace(200), ptr addrspace(200)) local_unnamed_addr addrspace(200) nounwind
declare ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200), i32) addrspace(200) nounwind readnone willreturn
define dso_local void @hoist_csetbounds(i32 signext %cond, ptr addrspace(200) %f) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: hoist_csetbounds:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    caddi csp, csp, -48
; CHECK-NEXT:    sc cra, 40(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sc cs0, 32(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sc cs1, 24(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sc cs2, 16(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sc cs3, 8(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sc cs4, 0(csp) # 8-byte Folded Spill
; CHECK-NEXT:    cmv cs0, ca1
; CHECK-NEXT:    caddi ca0, ca1, 4
; CHECK-NEXT:    li s3, -1
; CHECK-NEXT:    li s4, 99
; CHECK-NEXT:    li a1, 4
; CHECK-NEXT:    scbndsr cs1, cs0, a1
; CHECK-NEXT:    scbndsr cs2, ca0, a1
; CHECK-NEXT:    j .LBB0_2
; CHECK-NEXT:  .LBB0_1: # %for.inc
; CHECK-NEXT:    # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    addi s3, s3, 1
; CHECK-NEXT:    bgeu s3, s4, .LBB0_4
; CHECK-NEXT:  .LBB0_2: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    beqz s0, .LBB0_1
; CHECK-NEXT:  # %bb.3: # %if.then
; CHECK-NEXT:    # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    cmv ca0, cs1
; CHECK-NEXT:    cmv ca1, cs2
; CHECK-NEXT:    call call
; CHECK-NEXT:    j .LBB0_1
; CHECK-NEXT:  .LBB0_4: # %for.cond.cleanup
; CHECK-NEXT:    lc cra, 40(csp) # 8-byte Folded Reload
; CHECK-NEXT:    lc cs0, 32(csp) # 8-byte Folded Reload
; CHECK-NEXT:    lc cs1, 24(csp) # 8-byte Folded Reload
; CHECK-NEXT:    lc cs2, 16(csp) # 8-byte Folded Reload
; CHECK-NEXT:    lc cs3, 8(csp) # 8-byte Folded Reload
; CHECK-NEXT:    lc cs4, 0(csp) # 8-byte Folded Reload
; CHECK-NEXT:    caddi csp, csp, 48
; CHECK-NEXT:    ret
; HOIST-OPT-LABEL: define dso_local void @hoist_csetbounds
; HOIST-OPT-SAME: (i32 signext [[COND:%.*]], ptr addrspace(200) [[F:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; HOIST-OPT-NEXT:  entry:
; HOIST-OPT-NEXT:    [[TOBOOL:%.*]] = icmp eq ptr addrspace(200) [[F]], null
; HOIST-OPT-NEXT:    br i1 [[TOBOOL]], label [[FOR_COND_CLEANUP:%.*]], label [[ENTRY_SPLIT:%.*]]
; HOIST-OPT:       entry.split:
; HOIST-OPT-NEXT:    [[DST:%.*]] = getelementptr inbounds [[STRUCT_FOO:%.*]], ptr addrspace(200) [[F]], i32 0, i32 1
; HOIST-OPT-NEXT:    [[ADDRESS_WITH_BOUNDS:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) nonnull [[F]], i32 4)
; HOIST-OPT-NEXT:    [[ADDRESS_WITH_BOUNDS1:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) nonnull [[DST]], i32 4)
; HOIST-OPT-NEXT:    br label [[FOR_BODY:%.*]]
; HOIST-OPT:       for.cond.cleanup:
; HOIST-OPT-NEXT:    ret void
; HOIST-OPT:       for.body:
; HOIST-OPT-NEXT:    [[I_06:%.*]] = phi i32 [ 0, [[ENTRY_SPLIT]] ], [ [[INC:%.*]], [[FOR_BODY]] ]
; HOIST-OPT-NEXT:    tail call void @call(ptr addrspace(200) [[ADDRESS_WITH_BOUNDS]], ptr addrspace(200) [[ADDRESS_WITH_BOUNDS1]])
; HOIST-OPT-NEXT:    [[INC]] = add nuw nsw i32 [[I_06]], 1
; HOIST-OPT-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[INC]], 100
; HOIST-OPT-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP]], label [[FOR_BODY]]
;
entry:
  %tobool = icmp eq ptr addrspace(200) %f, null
  %dst = getelementptr inbounds %struct.foo, ptr addrspace(200) %f, i64 0, i32 1
  br label %for.body
for.cond.cleanup: ; preds = %for.inc
  ret void
for.body: ; preds = %for.inc, %entry
  %i.06 = phi i32 [ 0, %entry ], [ %inc, %for.inc ]
  br i1 %tobool, label %for.inc, label %if.then
if.then: ; preds = %for.body
  %address.with.bounds = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) nonnull %f, i32 4)
  %address.with.bounds1 = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) nonnull %dst, i32 4)
  call void @call(ptr addrspace(200) %address.with.bounds, ptr addrspace(200) %address.with.bounds1)
  br label %for.inc
for.inc: ; preds = %if.then, %for.body
  %inc = add nuw nsw i32 %i.06, 1
  %cmp = icmp ult i32 %i.06, 99
  br i1 %cmp, label %for.body, label %for.cond.cleanup
}
