; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --function-signature --scrub-attributes
; This used to crash: https://github.com/CTSRD-CHERI/llvm-project/issues/286
; RUN: opt  -S -passes=gvn %s -o - | FileCheck %s
target datalayout = "E-m:e-pf200:128:128:128:64-i8:8:32-i16:16:32-i64:64-n32:64-S128"
target triple = "riscv64-unknown-freebsd"

; Generated from this C++ source code (reduced testcase for libc++)
; template <class T> class j {
;  T aj;
;public:
;  template <class c> j(c k) : aj(k) {}
;};
;template <class d, class c>
;void operator-(j<d>, j<c> &);
;
;void e(long k) {
;  j<__int128> a(k), b(a);
;  j<__int128>(0) - b;
;}

%class.j = type { i128 }

declare void @_ZmiInnEv1jIT_ERS0_IT0_E(i64 inreg, i64 inreg, ptr dereferenceable(16))

define void @_Z1el(i64 signext %k) local_unnamed_addr {
; CHECK-LABEL: define {{[^@]+}}@_Z1el
; CHECK-SAME: (i64 signext [[K:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[A_SROA_0:%.*]] = alloca ptr addrspace(200), align 16
; CHECK-NEXT:    [[B:%.*]] = alloca ptr addrspace(200), align 16
; CHECK-NEXT:    [[CONV_I_I:%.*]] = sext i64 [[K]] to i128
; CHECK-NEXT:    store i128 [[CONV_I_I]], ptr [[A_SROA_0]], align 16
; CHECK-NEXT:    [[A_SROA_0_0_A_SROA_0_0_:%.*]] = load ptr addrspace(200), ptr [[A_SROA_0]], align 16
; CHECK-NEXT:    store ptr addrspace(200) [[A_SROA_0_0_A_SROA_0_0_]], ptr [[B]], align 16
; CHECK-NEXT:    call void @_ZmiInnEv1jIT_ERS0_IT0_E(i64 inreg 0, i64 inreg 0, ptr nonnull dereferenceable(16) [[B]])
; CHECK-NEXT:    ret void
;
entry:
  %a.sroa.0 = alloca ptr addrspace(200), align 16
  %tmpcast7 = bitcast ptr %a.sroa.0 to ptr
  %b = alloca ptr addrspace(200), align 16
  %tmpcast = bitcast ptr %b to ptr
  %conv.i.i = sext i64 %k to i128
  store i128 %conv.i.i, ptr %tmpcast7, align 16
  %a.sroa.0.0.a.sroa.0.0. = load ptr addrspace(200), ptr %a.sroa.0, align 16
  store ptr addrspace(200) %a.sroa.0.0.a.sroa.0.0., ptr %b, align 16
  call void @_ZmiInnEv1jIT_ERS0_IT0_E(i64 inreg 0, i64 inreg 0, ptr nonnull dereferenceable(16) %tmpcast)
  ret void
}

attributes #0 = { argmemonly nofree nosync nounwind willreturn }
