; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=gvn -S -o - %s | FileCheck %s
; RUN: opt -passes=newgvn -S -o - %s | FileCheck %s

; IR Generated from the following C code
;
;
; long foo(void *b, void *p){
;   void *q;
;
;   q = __builtin_cheri_address_set(b, (long)p);
;   if (p == q)
;     return __builtin_cheri_length_get(q); // this parameter cannot be replaced
;                                           // with p even though p == q
;   return 0;
; }
;
target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n32:64-S128-A200-P200-G200"
target triple = "riscv64-codasip-linux-gnu"

; Function Attrs: mustprogress nofree noinline nosync nounwind willreturn memory(none)
define dso_local i64 @foo(ptr addrspace(200) noundef readnone %b, ptr addrspace(200) noundef readnone %p) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: define dso_local i64 @foo
; CHECK-SAME: (ptr addrspace(200) noundef readnone [[B:%.*]], ptr addrspace(200) noundef readnone [[P:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[P]])
; CHECK-NEXT:    [[TMP1:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[B]], i64 [[TMP0]])
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr addrspace(200) [[TMP1]], [[P]]
; CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[RETURN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    [[TMP2:%.*]] = tail call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[TMP1]])
; CHECK-NEXT:    br label [[RETURN]]
; CHECK:       return:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i64 [ [[TMP2]], [[IF_THEN]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret i64 [[RETVAL_0]]
;
entry:
  %0 = tail call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) %p)
  %1 = tail call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) %b, i64 %0)
  %cmp = icmp eq ptr addrspace(200) %1, %p
  br i1 %cmp, label %if.then, label %return

if.then:                                          ; preds = %entry
  %2 = tail call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) %1)
  br label %return

return:                                           ; preds = %entry, %if.then
  %retval.0 = phi i64 [ %2, %if.then ], [ 0, %entry ]
  ret i64 %retval.0
}

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
declare i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200)) addrspace(200) #1

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
declare ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200), i64) addrspace(200) #1

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
declare i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200)) addrspace(200) #1

attributes #0 = { mustprogress nofree noinline nosync nounwind willreturn memory(none) "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-features"="+64bit,+cap-mode,+zcherihybrid,+zcheripurecap" }
attributes #1 = { mustprogress nofree nosync nounwind willreturn memory(none) }
