// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %cheri_purecap_cc1 -o - -O2 -emit-llvm  %s | FileCheck %s
// Found while trying to use the builtin in QtBase
// CHECK-LABEL: define {{[^@]+}}@test1
// CHECK-SAME: (ptr addrspace(200) noundef readnone [[C:%.*]], i32 noundef signext [[B:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ALIGNMENT:%.*]] = zext i32 [[B]] to i64
// CHECK-NEXT:    [[INVERTED_MASK:%.*]] = sub nsw i64 0, [[ALIGNMENT]]
// CHECK-NEXT:    [[ALIGNED_RESULT:%.*]] = tail call ptr addrspace(200) @llvm.ptrmask.p200.i64(ptr addrspace(200) [[C]], i64 [[INVERTED_MASK]])
// CHECK-NEXT:    ret ptr addrspace(200) [[ALIGNED_RESULT]]
//
extern "C" char* test1(char* c, int b) {
  return __builtin_align_down(c, b);
}

// Found while compiling libnv
// CHECK-LABEL: define {{[^@]+}}@test2
// CHECK-SAME: (ptr addrspace(200) noundef [[VALUE:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR2:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[PTRADDR:%.*]] = tail call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[VALUE]])
// CHECK-NEXT:    [[OVER_BOUNDARY:%.*]] = add i64 [[PTRADDR]], 3
// CHECK-NEXT:    [[ALIGNED_RESULT:%.*]] = and i64 [[OVER_BOUNDARY]], -4
// CHECK-NEXT:    [[ALIGNED_CAP:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[VALUE]], i64 [[ALIGNED_RESULT]])
// CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr addrspace(200) [[ALIGNED_CAP]], i64 4) ]
// CHECK-NEXT:    ret ptr addrspace(200) [[ALIGNED_CAP]]
//
extern "C" __uintcap_t test2(__uintcap_t value) {
  // There should be two casts from capability to address (one for size, one for
  // alignment). The alignment one could be an offset get instead but this doesn't
  // really make any difference since Sema validates that it is a valid capability.
  return __builtin_align_up(value, (__uintcap_t)sizeof(0));
}
