// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %cheri_purecap_cc1 -std=c++11 -o - -emit-llvm %s -O1 | FileCheck %s --check-prefix MIPS-PURECAP
// RUN: %cheri_cc1 -std=c++11 -o - -emit-llvm %s -O1 | FileCheck %s --check-prefix MIPS-NOCHERI
// RUN: %riscv64_cheri_cc1 -std=c++11 -o - -emit-llvm %s -O1 | FileCheck %s --check-prefix RISCV64-NOCHERI
// TODO: RISCV purecap still uses sret
// RUN: %riscv64_cheri_purecap_cc1 -std=c++11 -o - -emit-llvm %s -O1 | FileCheck %s --check-prefix RISCV64-PURECAP

// Remove NOT suffix to check the generated assembly:
// REQUIRESNOT: mips-registered-target
// RUNNOT: %cheri_purecap_cc1 %s -std=c++11 -o - -S -O2 -mframe-pointer=none
// RUNNOT: %cheri_cc1 %s -std=c++11 -o - -S -O2 -mframe-pointer=none

class A {
public:
  int x;
  int foo();
};

typedef int (A::* AMemberFuncPtr)();
typedef int A::* AMemberDataPtr;

// MIPS-PURECAP-LABEL: define {{[^@]+}}@_Z10return_p2fv
// MIPS-PURECAP-SAME: () local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
// MIPS-PURECAP-NEXT:  entry:
// MIPS-PURECAP-NEXT:    ret { ptr addrspace(200), i64 } { ptr addrspace(200) @_ZN1A3fooEv, i64 0 }
//
// MIPS-NOCHERI-LABEL: define {{[^@]+}}@_Z10return_p2fv
// MIPS-NOCHERI-SAME: () local_unnamed_addr #[[ATTR0:[0-9]+]] {
// MIPS-NOCHERI-NEXT:  entry:
// MIPS-NOCHERI-NEXT:    ret { i64, i64 } { i64 ptrtoint (ptr @_ZN1A3fooEv to i64), i64 0 }
//
// RISCV64-NOCHERI-LABEL: define {{[^@]+}}@_Z10return_p2fv
// RISCV64-NOCHERI-SAME: () local_unnamed_addr #[[ATTR0:[0-9]+]] {
// RISCV64-NOCHERI-NEXT:  entry:
// RISCV64-NOCHERI-NEXT:    ret [2 x i64] [i64 ptrtoint (ptr @_ZN1A3fooEv to i64), i64 0]
//
// RISCV64-PURECAP-LABEL: define {{[^@]+}}@_Z10return_p2fv
// RISCV64-PURECAP-SAME: (ptr addrspace(200) dead_on_unwind noalias nocapture writable writeonly sret({ ptr addrspace(200), i64 }) align 16 [[AGG_RESULT:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
// RISCV64-PURECAP-NEXT:  entry:
// RISCV64-PURECAP-NEXT:    store { ptr addrspace(200), i64 } { ptr addrspace(200) @_ZN1A3fooEv, i64 0 }, ptr addrspace(200) [[AGG_RESULT]], align 16, !tbaa [[TBAA4:![0-9]+]]
// RISCV64-PURECAP-NEXT:    ret void
//
AMemberFuncPtr return_p2f() {
  return &A::foo;
}

// MIPS-PURECAP-LABEL: define {{[^@]+}}@_Z15return_p2f_nullv
// MIPS-PURECAP-SAME: () local_unnamed_addr addrspace(200) #[[ATTR0]] {
// MIPS-PURECAP-NEXT:  entry:
// MIPS-PURECAP-NEXT:    ret { ptr addrspace(200), i64 } zeroinitializer
//
// MIPS-NOCHERI-LABEL: define {{[^@]+}}@_Z15return_p2f_nullv
// MIPS-NOCHERI-SAME: () local_unnamed_addr #[[ATTR0]] {
// MIPS-NOCHERI-NEXT:  entry:
// MIPS-NOCHERI-NEXT:    ret { i64, i64 } zeroinitializer
//
// RISCV64-NOCHERI-LABEL: define {{[^@]+}}@_Z15return_p2f_nullv
// RISCV64-NOCHERI-SAME: () local_unnamed_addr #[[ATTR0]] {
// RISCV64-NOCHERI-NEXT:  entry:
// RISCV64-NOCHERI-NEXT:    ret [2 x i64] zeroinitializer
//
// RISCV64-PURECAP-LABEL: define {{[^@]+}}@_Z15return_p2f_nullv
// RISCV64-PURECAP-SAME: (ptr addrspace(200) dead_on_unwind noalias nocapture writable writeonly sret({ ptr addrspace(200), i64 }) align 16 [[AGG_RESULT:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR2:[0-9]+]] {
// RISCV64-PURECAP-NEXT:  entry:
// RISCV64-PURECAP-NEXT:    tail call void @llvm.memset.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[AGG_RESULT]], i8 0, i64 32, i1 false)
// RISCV64-PURECAP-NEXT:    ret void
//
AMemberFuncPtr return_p2f_null() {
  return nullptr;
}

// MIPS-PURECAP-LABEL: define {{[^@]+}}@_Z15passthrough_p2fM1AFivE
// MIPS-PURECAP-SAME: (ptr addrspace(200) inreg [[P2F_COERCE0:%.*]], i64 inreg [[P2F_COERCE1:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0]] {
// MIPS-PURECAP-NEXT:  entry:
// MIPS-PURECAP-NEXT:    [[P2F1_FCA_0_INSERT:%.*]] = insertvalue { ptr addrspace(200), i64 } poison, ptr addrspace(200) [[P2F_COERCE0]], 0
// MIPS-PURECAP-NEXT:    [[P2F1_FCA_1_INSERT:%.*]] = insertvalue { ptr addrspace(200), i64 } [[P2F1_FCA_0_INSERT]], i64 [[P2F_COERCE1]], 1
// MIPS-PURECAP-NEXT:    ret { ptr addrspace(200), i64 } [[P2F1_FCA_1_INSERT]]
//
// MIPS-NOCHERI-LABEL: define {{[^@]+}}@_Z15passthrough_p2fM1AFivE
// MIPS-NOCHERI-SAME: (i64 inreg [[P2F_COERCE0:%.*]], i64 inreg [[P2F_COERCE1:%.*]]) local_unnamed_addr #[[ATTR0]] {
// MIPS-NOCHERI-NEXT:  entry:
// MIPS-NOCHERI-NEXT:    [[P2F1_FCA_0_INSERT:%.*]] = insertvalue { i64, i64 } poison, i64 [[P2F_COERCE0]], 0
// MIPS-NOCHERI-NEXT:    [[P2F1_FCA_1_INSERT:%.*]] = insertvalue { i64, i64 } [[P2F1_FCA_0_INSERT]], i64 [[P2F_COERCE1]], 1
// MIPS-NOCHERI-NEXT:    ret { i64, i64 } [[P2F1_FCA_1_INSERT]]
//
// RISCV64-NOCHERI-LABEL: define {{[^@]+}}@_Z15passthrough_p2fM1AFivE
// RISCV64-NOCHERI-SAME: ([2 x i64] returned [[P2F_COERCE:%.*]]) local_unnamed_addr #[[ATTR0]] {
// RISCV64-NOCHERI-NEXT:  entry:
// RISCV64-NOCHERI-NEXT:    ret [2 x i64] [[P2F_COERCE]]
//
// RISCV64-PURECAP-LABEL: define {{[^@]+}}@_Z15passthrough_p2fM1AFivE
// RISCV64-PURECAP-SAME: (ptr addrspace(200) dead_on_unwind noalias nocapture writable writeonly sret({ ptr addrspace(200), i64 }) align 16 [[AGG_RESULT:%.*]], ptr addrspace(200) nocapture noundef readonly [[TMP0:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR3:[0-9]+]] {
// RISCV64-PURECAP-NEXT:  entry:
// RISCV64-PURECAP-NEXT:    tail call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[AGG_RESULT]], ptr addrspace(200) noundef nonnull align 16 dereferenceable(32) [[TMP0]], i64 32, i1 false)
// RISCV64-PURECAP-NEXT:    ret void
//
AMemberFuncPtr passthrough_p2f(AMemberFuncPtr p2f) {
  return p2f;
}

// MIPS-PURECAP-LABEL: define {{[^@]+}}@_Z15return_p2d_nullv
// MIPS-PURECAP-SAME: () local_unnamed_addr addrspace(200) #[[ATTR0]] {
// MIPS-PURECAP-NEXT:  entry:
// MIPS-PURECAP-NEXT:    ret i64 -1
//
// MIPS-NOCHERI-LABEL: define {{[^@]+}}@_Z15return_p2d_nullv
// MIPS-NOCHERI-SAME: () local_unnamed_addr #[[ATTR0]] {
// MIPS-NOCHERI-NEXT:  entry:
// MIPS-NOCHERI-NEXT:    ret i64 -1
//
// RISCV64-NOCHERI-LABEL: define {{[^@]+}}@_Z15return_p2d_nullv
// RISCV64-NOCHERI-SAME: () local_unnamed_addr #[[ATTR0]] {
// RISCV64-NOCHERI-NEXT:  entry:
// RISCV64-NOCHERI-NEXT:    ret i64 -1
//
// RISCV64-PURECAP-LABEL: define {{[^@]+}}@_Z15return_p2d_nullv
// RISCV64-PURECAP-SAME: () local_unnamed_addr addrspace(200) #[[ATTR4:[0-9]+]] {
// RISCV64-PURECAP-NEXT:  entry:
// RISCV64-PURECAP-NEXT:    ret i64 -1
//
AMemberDataPtr return_p2d_null() {
  return nullptr;
}

// MIPS-PURECAP-LABEL: define {{[^@]+}}@_Z10return_p2dv
// MIPS-PURECAP-SAME: () local_unnamed_addr addrspace(200) #[[ATTR0]] {
// MIPS-PURECAP-NEXT:  entry:
// MIPS-PURECAP-NEXT:    ret i64 0
//
// MIPS-NOCHERI-LABEL: define {{[^@]+}}@_Z10return_p2dv
// MIPS-NOCHERI-SAME: () local_unnamed_addr #[[ATTR0]] {
// MIPS-NOCHERI-NEXT:  entry:
// MIPS-NOCHERI-NEXT:    ret i64 0
//
// RISCV64-NOCHERI-LABEL: define {{[^@]+}}@_Z10return_p2dv
// RISCV64-NOCHERI-SAME: () local_unnamed_addr #[[ATTR0]] {
// RISCV64-NOCHERI-NEXT:  entry:
// RISCV64-NOCHERI-NEXT:    ret i64 0
//
// RISCV64-PURECAP-LABEL: define {{[^@]+}}@_Z10return_p2dv
// RISCV64-PURECAP-SAME: () local_unnamed_addr addrspace(200) #[[ATTR4]] {
// RISCV64-PURECAP-NEXT:  entry:
// RISCV64-PURECAP-NEXT:    ret i64 0
//
AMemberDataPtr return_p2d() {
  return &A::x;
}

// MIPS-PURECAP-LABEL: define {{[^@]+}}@_Z15passthrough_p2dM1Ai
// MIPS-PURECAP-SAME: (i64 returned [[P2D:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0]] {
// MIPS-PURECAP-NEXT:  entry:
// MIPS-PURECAP-NEXT:    ret i64 [[P2D]]
//
// MIPS-NOCHERI-LABEL: define {{[^@]+}}@_Z15passthrough_p2dM1Ai
// MIPS-NOCHERI-SAME: (i64 returned [[P2D:%.*]]) local_unnamed_addr #[[ATTR0]] {
// MIPS-NOCHERI-NEXT:  entry:
// MIPS-NOCHERI-NEXT:    ret i64 [[P2D]]
//
// RISCV64-NOCHERI-LABEL: define {{[^@]+}}@_Z15passthrough_p2dM1Ai
// RISCV64-NOCHERI-SAME: (i64 returned [[P2D:%.*]]) local_unnamed_addr #[[ATTR0]] {
// RISCV64-NOCHERI-NEXT:  entry:
// RISCV64-NOCHERI-NEXT:    ret i64 [[P2D]]
//
// RISCV64-PURECAP-LABEL: define {{[^@]+}}@_Z15passthrough_p2dM1Ai
// RISCV64-PURECAP-SAME: (i64 returned [[P2D:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR4]] {
// RISCV64-PURECAP-NEXT:  entry:
// RISCV64-PURECAP-NEXT:    ret i64 [[P2D]]
//
AMemberDataPtr passthrough_p2d(AMemberDataPtr p2d) {
  return p2d;
}

