// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// This previously crashed during SROA. This is a terrible test case, but running the IR
// prior to SROA through opt doesn't crash...
// RUN: %cheri_cc1 -O3 -emit-llvm %s -o - | FileCheck %s

class a {
  int b;
  int *c;

public:
  a &e() { return *this; }
};
int d;
class f {
  void h() const;
};
// CHECK-LABEL: @_ZNK1f1hEv(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void f::h() const {
  a g;
  if (d)
    ;
  else
    g = g.e() = g.e();
}
