// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %cheri_purecap_cc1 -std=c++11 -emit-llvm -o - %s | FileCheck %s
/// Check that enum values whereby the underlying enum type is [u]intcap_t are
/// converted to i8 addrspace(200)*

typedef __intcap_t a;
enum : a { b, d };
// CHECK-LABEL: define {{[^@]+}}@_Z1cv
// CHECK-SAME: () addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 1)
//
a c() {
  return d;
}

// CHECK-LABEL: define {{[^@]+}}@_Z1ev
// CHECK-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 1))
// CHECK-NEXT:    [[CONV:%.*]] = trunc i64 [[TMP0]] to i32
// CHECK-NEXT:    ret void
//
void e() {
  (int(d));
}
