// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
/// Turning on subobject bounds in hybrid mode previously crashed because we
/// were trying to set bounds on non-CHERI array decay and array indexing.
// RUN: %riscv64_cheri_cc1 -cheri-bounds=subobject-safe -Rcheri-subobject-bounds -verify -o - -emit-llvm %s
// RUN: %riscv64_cheri_cc1 -cheri-bounds=subobject-safe -Rcheri-subobject-bounds -verify -o - -emit-llvm %s | FileCheck %s

void pass_decayed_array(const char *);
static char array[] = "";
// CHECK-LABEL: define dso_local void @_Z4testv
// CHECK-SAME: () #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @_Z18pass_decayed_arrayPKc(ptr noundef @_ZL5array)
// CHECK-NEXT:    ret void
//
void test() {
  pass_decayed_array(array);
}

void pass_decayed_array_cap(const char * __capability);
// CHECK-LABEL: define dso_local void @_Z5test2v
// CHECK-SAME: () #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @_Z22pass_decayed_array_capU12__capabilityPKc(ptr addrspace(200) noundef addrspacecast (ptr @_ZL5array to ptr addrspace(200)))
// CHECK-NEXT:    ret void
//
void test2() {
  // NOTE: no subobject bounds here, the AST has the decay first then the
  // conversion to __capability.
  pass_decayed_array_cap(array);
}

char global_array[4];
// CHECK-LABEL: define dso_local noundef signext i8 @_Z12flatten_argvv
// CHECK-SAME: () #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr getelementptr inbounds ([4 x i8], ptr @global_array, i64 0, i64 3), align 1
// CHECK-NEXT:    ret i8 [[TMP0]]
//
char flatten_argv() {
  return global_array[3];
}

struct Foo {
  float f;
  int buffer[64];
  int i;
};

/// Check that we set container bounds on a pointer argument and individual
/// element bounds for a reference (but only for __capability!)
void call(int *arg);
void call_cap(int * __capability arg);
void call_ref(int &i);
void call_cap_ref(int & __capability i);

// CHECK-LABEL: define dso_local void @_Z20container_bounds_capU12__capabilityP3Foo
// CHECK-SAME: (ptr addrspace(200) noundef [[F:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[F_ADDR:%.*]] = alloca ptr addrspace(200), align 16
// CHECK-NEXT:    store ptr addrspace(200) [[F]], ptr [[F_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr [[F_ADDR]], align 16
// CHECK-NEXT:    [[BUFFER:%.*]] = getelementptr inbounds [[STRUCT_FOO:%.*]], ptr addrspace(200) [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[BUFFER]], i64 256)
// CHECK-NEXT:    [[TMP2:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[TMP1]], i64 256)
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(200) [[TMP2]], i64 0, i64 16
// CHECK-NEXT:    call void @_Z8call_capU12__capabilityPi(ptr addrspace(200) noundef [[ARRAYIDX]])
// CHECK-NEXT:    ret void
//
void container_bounds_cap(struct Foo * __capability f) {
  call_cap(&f->buffer[16]);  // Should use container bounds for the address of array element
  // expected-remark@-1{{using size of containing type 'int[64]' instead of object type 'int' for subobject bounds on &array[<CONSTANT>]}}
  // expected-remark@-2{{setting sub-object bounds for field 'buffer' (array subscript on 'int[64]') to 256 bytes}}
  // expected-remark@-3{{setting sub-object bounds for pointer to 'int' to 256 bytes}}
}

// CHECK-LABEL: define dso_local void @_Z21single_ref_bounds_capU12__capabilityP3Foo
// CHECK-SAME: (ptr addrspace(200) noundef [[F:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[F_ADDR:%.*]] = alloca ptr addrspace(200), align 16
// CHECK-NEXT:    store ptr addrspace(200) [[F]], ptr [[F_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr [[F_ADDR]], align 16
// CHECK-NEXT:    [[BUFFER:%.*]] = getelementptr inbounds [[STRUCT_FOO:%.*]], ptr addrspace(200) [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[BUFFER]], i64 256)
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [64 x i32], ptr addrspace(200) [[TMP1]], i64 0, i64 16
// CHECK-NEXT:    call void @_Z12call_cap_refU12__capabilityRi(ptr addrspace(200) noundef nonnull align 4 dereferenceable(4) [[ARRAYIDX]])
// CHECK-NEXT:    ret void
//
void single_ref_bounds_cap(struct Foo * __capability f) {
  call_cap_ref(f->buffer[16]);  // Should set individual element bounds here
  // expected-remark@-1{{setting sub-object bounds for field 'buffer' (array subscript on 'int[64]') to 256 bytes}}
}

// CHECK-LABEL: define dso_local void @_Z31integer_ptr_no_container_boundsP3Foo
// CHECK-SAME: (ptr noundef [[F:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[F_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[F]], ptr [[F_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[F_ADDR]], align 8
// CHECK-NEXT:    [[BUFFER:%.*]] = getelementptr inbounds [[STRUCT_FOO:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [64 x i32], ptr [[BUFFER]], i64 0, i64 16
// CHECK-NEXT:    call void @_Z4callPi(ptr noundef [[ARRAYIDX]])
// CHECK-NEXT:    ret void
//
void integer_ptr_no_container_bounds(struct Foo *f) {
  call(&f->buffer[16]); // no bounds for non-caps
}

// CHECK-LABEL: define dso_local void @_Z21integer_ref_no_boundsP3Foo
// CHECK-SAME: (ptr noundef [[F:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[F_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[F]], ptr [[F_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[F_ADDR]], align 8
// CHECK-NEXT:    [[BUFFER:%.*]] = getelementptr inbounds [[STRUCT_FOO:%.*]], ptr [[TMP0]], i32 0, i32 1
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [64 x i32], ptr [[BUFFER]], i64 0, i64 16
// CHECK-NEXT:    call void @_Z8call_refRi(ptr noundef nonnull align 4 dereferenceable(4) [[ARRAYIDX]])
// CHECK-NEXT:    ret void
//
void integer_ref_no_bounds(struct Foo *f) {
  call_ref(f->buffer[16]);  // no bounds for non-caps
}



