// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
//
// RUN: %riscv64_cheri_purecap_cc1 -o - -emit-llvm -disable-O0-optnone -target-feature +cheri-bounded-vararg %s\
// RUN:   | opt -S -passes=mem2reg | FileCheck %s --check-prefixes=CHECK-L64PC128
// RUN: %riscv32_cheri_purecap_cc1 -o - -emit-llvm -disable-O0-optnone -target-feature +cheri-bounded-vararg %s\
// RUN:   | opt -S -passes=mem2reg | FileCheck %s --check-prefixes=CHECK-IL32PC64

#include <stdarg.h>

struct hfa {
  float x;
  float y;
  float z;
};

struct comp {
  int *x;
  int y;
};


void call1(double, float);


// CHECK-L64PC128-LABEL: define {{[^@]+}}@callee_test_scalars
// CHECK-L64PC128-SAME: (i32 noundef signext [[COUNT:%.*]], ...) addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-L64PC128-NEXT:  entry:
// CHECK-L64PC128-NEXT:    [[ARGS:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-L64PC128-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[ARGS]])
// CHECK-L64PC128-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 16
// CHECK-L64PC128-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK]], i64 16
// CHECK-L64PC128-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[ARGS]], align 16
// CHECK-L64PC128-NEXT:    [[TMP0:%.*]] = load double, ptr addrspace(200) [[STACK]], align 16
// CHECK-L64PC128-NEXT:    [[STACK1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 16
// CHECK-L64PC128-NEXT:    [[NEW_STACK2:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK1]], i64 16
// CHECK-L64PC128-NEXT:    store ptr addrspace(200) [[NEW_STACK2]], ptr addrspace(200) [[ARGS]], align 16
// CHECK-L64PC128-NEXT:    [[TMP1:%.*]] = load float, ptr addrspace(200) [[STACK1]], align 16
// CHECK-L64PC128-NEXT:    call void @llvm.va_end.p200(ptr addrspace(200) [[ARGS]])
// CHECK-L64PC128-NEXT:    call void @call1(double noundef [[TMP0]], float noundef [[TMP1]])
// CHECK-L64PC128-NEXT:    ret void
//
// CHECK-IL32PC64-LABEL: define {{[^@]+}}@callee_test_scalars
// CHECK-IL32PC64-SAME: (i32 noundef [[COUNT:%.*]], ...) addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-IL32PC64-NEXT:  entry:
// CHECK-IL32PC64-NEXT:    [[ARGS:%.*]] = alloca ptr addrspace(200), align 8, addrspace(200)
// CHECK-IL32PC64-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[ARGS]])
// CHECK-IL32PC64-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 8
// CHECK-IL32PC64-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK]], i32 8
// CHECK-IL32PC64-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[ARGS]], align 8
// CHECK-IL32PC64-NEXT:    [[TMP0:%.*]] = load double, ptr addrspace(200) [[STACK]], align 8
// CHECK-IL32PC64-NEXT:    [[STACK1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 8
// CHECK-IL32PC64-NEXT:    [[NEW_STACK2:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK1]], i32 8
// CHECK-IL32PC64-NEXT:    store ptr addrspace(200) [[NEW_STACK2]], ptr addrspace(200) [[ARGS]], align 8
// CHECK-IL32PC64-NEXT:    [[TMP1:%.*]] = load float, ptr addrspace(200) [[STACK1]], align 8
// CHECK-IL32PC64-NEXT:    call void @llvm.va_end.p200(ptr addrspace(200) [[ARGS]])
// CHECK-IL32PC64-NEXT:    call void @call1(double noundef [[TMP0]], float noundef [[TMP1]])
// CHECK-IL32PC64-NEXT:    ret void
//
void callee_test_scalars(int count, ...) {
  va_list args;
  va_start(args, count);
  double num0 = va_arg(args, double);
  float num1 = va_arg(args, float);
  va_end(args);
  return call1(num0, num1);
}


void call2(struct hfa, struct comp);

// CHECK-L64PC128-LABEL: define {{[^@]+}}@callee_test_aggregate
// CHECK-L64PC128-SAME: (i32 noundef signext [[COUNT:%.*]], ...) addrspace(200) #[[ATTR0]] {
// CHECK-L64PC128-NEXT:  entry:
// CHECK-L64PC128-NEXT:    [[ARGS:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-L64PC128-NEXT:    [[NUM0:%.*]] = alloca [[STRUCT_HFA:%.*]], align 4, addrspace(200)
// CHECK-L64PC128-NEXT:    [[NUM1:%.*]] = alloca [[STRUCT_COMP:%.*]], align 16, addrspace(200)
// CHECK-L64PC128-NEXT:    [[NUM0_COERCE:%.*]] = alloca [2 x i64], align 8, addrspace(200)
// CHECK-L64PC128-NEXT:    [[BYVAL_TEMP:%.*]] = alloca [[STRUCT_COMP]], align 16, addrspace(200)
// CHECK-L64PC128-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[ARGS]])
// CHECK-L64PC128-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 16
// CHECK-L64PC128-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK]], i64 16
// CHECK-L64PC128-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[ARGS]], align 16
// CHECK-L64PC128-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 4 [[NUM0]], ptr addrspace(200) align 16 [[STACK]], i64 12, i1 false)
// CHECK-L64PC128-NEXT:    [[STACK1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 16
// CHECK-L64PC128-NEXT:    [[NEW_STACK2:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK1]], i64 16
// CHECK-L64PC128-NEXT:    store ptr addrspace(200) [[NEW_STACK2]], ptr addrspace(200) [[ARGS]], align 16
// CHECK-L64PC128-NEXT:    [[VAARG_ADDR:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[STACK1]], align 16
// CHECK-L64PC128-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 [[NUM1]], ptr addrspace(200) align 16 [[VAARG_ADDR]], i64 32, i1 false)
// CHECK-L64PC128-NEXT:    call void @llvm.va_end.p200(ptr addrspace(200) [[ARGS]])
// CHECK-L64PC128-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 8 [[NUM0_COERCE]], ptr addrspace(200) align 4 [[NUM0]], i64 12, i1 false)
// CHECK-L64PC128-NEXT:    [[TMP0:%.*]] = load [2 x i64], ptr addrspace(200) [[NUM0_COERCE]], align 8
// CHECK-L64PC128-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 [[BYVAL_TEMP]], ptr addrspace(200) align 16 [[NUM1]], i64 32, i1 false)
// CHECK-L64PC128-NEXT:    call void @call2([2 x i64] [[TMP0]], ptr addrspace(200) noundef [[BYVAL_TEMP]])
// CHECK-L64PC128-NEXT:    ret void
//
// CHECK-IL32PC64-LABEL: define {{[^@]+}}@callee_test_aggregate
// CHECK-IL32PC64-SAME: (i32 noundef [[COUNT:%.*]], ...) addrspace(200) #[[ATTR0]] {
// CHECK-IL32PC64-NEXT:  entry:
// CHECK-IL32PC64-NEXT:    [[ARGS:%.*]] = alloca ptr addrspace(200), align 8, addrspace(200)
// CHECK-IL32PC64-NEXT:    [[NUM0:%.*]] = alloca [[STRUCT_HFA:%.*]], align 4, addrspace(200)
// CHECK-IL32PC64-NEXT:    [[NUM1:%.*]] = alloca [[STRUCT_COMP:%.*]], align 8, addrspace(200)
// CHECK-IL32PC64-NEXT:    [[BYVAL_TEMP:%.*]] = alloca [[STRUCT_HFA]], align 4, addrspace(200)
// CHECK-IL32PC64-NEXT:    [[BYVAL_TEMP4:%.*]] = alloca [[STRUCT_COMP]], align 8, addrspace(200)
// CHECK-IL32PC64-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[ARGS]])
// CHECK-IL32PC64-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 8
// CHECK-IL32PC64-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK]], i32 8
// CHECK-IL32PC64-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[ARGS]], align 8
// CHECK-IL32PC64-NEXT:    [[VAARG_ADDR:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[STACK]], align 8
// CHECK-IL32PC64-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) align 4 [[NUM0]], ptr addrspace(200) align 4 [[VAARG_ADDR]], i32 12, i1 false)
// CHECK-IL32PC64-NEXT:    [[STACK1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS]], align 8
// CHECK-IL32PC64-NEXT:    [[NEW_STACK2:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK1]], i32 8
// CHECK-IL32PC64-NEXT:    store ptr addrspace(200) [[NEW_STACK2]], ptr addrspace(200) [[ARGS]], align 8
// CHECK-IL32PC64-NEXT:    [[VAARG_ADDR3:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[STACK1]], align 8
// CHECK-IL32PC64-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) align 8 [[NUM1]], ptr addrspace(200) align 8 [[VAARG_ADDR3]], i32 16, i1 false)
// CHECK-IL32PC64-NEXT:    call void @llvm.va_end.p200(ptr addrspace(200) [[ARGS]])
// CHECK-IL32PC64-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) align 4 [[BYVAL_TEMP]], ptr addrspace(200) align 4 [[NUM0]], i32 12, i1 false)
// CHECK-IL32PC64-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) align 8 [[BYVAL_TEMP4]], ptr addrspace(200) align 8 [[NUM1]], i32 16, i1 false)
// CHECK-IL32PC64-NEXT:    call void @call2(ptr addrspace(200) noundef [[BYVAL_TEMP]], ptr addrspace(200) noundef [[BYVAL_TEMP4]])
// CHECK-IL32PC64-NEXT:    ret void
//
void callee_test_aggregate(int count, ...){
  va_list args;
  va_start(args, count);
  struct hfa num0 = va_arg(args, struct hfa);
  struct comp num1 = va_arg(args, struct comp);
  va_end(args);
  return call2(num0, num1);
}


// CHECK-L64PC128-LABEL: define {{[^@]+}}@test_vacopy
// CHECK-L64PC128-SAME: (i32 noundef signext [[COUNT:%.*]], ...) addrspace(200) #[[ATTR0]] {
// CHECK-L64PC128-NEXT:  entry:
// CHECK-L64PC128-NEXT:    [[ARGS:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-L64PC128-NEXT:    [[ARGS1:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-L64PC128-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[ARGS]])
// CHECK-L64PC128-NEXT:    call void @llvm.va_copy.p200.p200(ptr addrspace(200) [[ARGS1]], ptr addrspace(200) [[ARGS]])
// CHECK-L64PC128-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS1]], align 16
// CHECK-L64PC128-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
// CHECK-IL32PC64-LABEL: define {{[^@]+}}@test_vacopy
// CHECK-IL32PC64-SAME: (i32 noundef [[COUNT:%.*]], ...) addrspace(200) #[[ATTR0]] {
// CHECK-IL32PC64-NEXT:  entry:
// CHECK-IL32PC64-NEXT:    [[ARGS:%.*]] = alloca ptr addrspace(200), align 8, addrspace(200)
// CHECK-IL32PC64-NEXT:    [[ARGS1:%.*]] = alloca ptr addrspace(200), align 8, addrspace(200)
// CHECK-IL32PC64-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[ARGS]])
// CHECK-IL32PC64-NEXT:    call void @llvm.va_copy.p200.p200(ptr addrspace(200) [[ARGS1]], ptr addrspace(200) [[ARGS]])
// CHECK-IL32PC64-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[ARGS1]], align 8
// CHECK-IL32PC64-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
va_list test_vacopy(int count, ...){
  va_list args;
  va_list args1;
  va_start(args, count);
  va_copy(args1, args);
  return args1;
}


struct empty {};

// CHECK-L64PC128-LABEL: define {{[^@]+}}@foo
// CHECK-L64PC128-SAME: (i32 noundef signext [[COUNT:%.*]], ...) addrspace(200) #[[ATTR0]] {
// CHECK-L64PC128-NEXT:  entry:
// CHECK-L64PC128-NEXT:    [[AP:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-L64PC128-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[AP]])
// CHECK-L64PC128-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[AP]], align 16
// CHECK-L64PC128-NEXT:    [[STACK1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[AP]], align 16
// CHECK-L64PC128-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK1]], i64 16
// CHECK-L64PC128-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[AP]], align 16
// CHECK-L64PC128-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(200) [[STACK1]], align 16
// CHECK-L64PC128-NEXT:    ret i32 [[TMP0]]
//
// CHECK-IL32PC64-LABEL: define {{[^@]+}}@foo
// CHECK-IL32PC64-SAME: (i32 noundef [[COUNT:%.*]], ...) addrspace(200) #[[ATTR0]] {
// CHECK-IL32PC64-NEXT:  entry:
// CHECK-IL32PC64-NEXT:    [[AP:%.*]] = alloca ptr addrspace(200), align 8, addrspace(200)
// CHECK-IL32PC64-NEXT:    call void @llvm.va_start.p200(ptr addrspace(200) [[AP]])
// CHECK-IL32PC64-NEXT:    [[STACK:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[AP]], align 8
// CHECK-IL32PC64-NEXT:    [[STACK1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[AP]], align 8
// CHECK-IL32PC64-NEXT:    [[NEW_STACK:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[STACK1]], i32 8
// CHECK-IL32PC64-NEXT:    store ptr addrspace(200) [[NEW_STACK]], ptr addrspace(200) [[AP]], align 8
// CHECK-IL32PC64-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(200) [[STACK1]], align 8
// CHECK-IL32PC64-NEXT:    ret i32 [[TMP0]]
//
int foo(int count, ...) {
  int ret;
  __builtin_va_list ap;
  __builtin_va_start (ap, count);
  __builtin_va_arg (ap, struct empty);
  ret = __builtin_va_arg(ap, int);
  return ret;
}
