// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %riscv32_cheri_purecap_cc1 -cheri-bounds=subobject-safe-exact -o - -emit-llvm %s | FileCheck %s --check-prefixes=CHECK-IL32PC64
// RUN: %riscv64_cheri_purecap_cc1 -cheri-bounds=subobject-safe-exact -o - -emit-llvm %s | FileCheck %s --check-prefixes=CHECK-L64PC128

// CHECK-IL32PC64-LABEL: %struct.NeedPadBase = type { i32, [508 x i8], [4096 x i8] }
// CHECK-L64PC128-LABEL: %struct.NeedPadBase = type { i32, [4 x i8], [4096 x i8] }
struct NeedPadBase {
  int field;
  char unrepresentable[0x1000] __attribute__((cheri_pad_representable));
} s_base;

// CHECK-IL32PC64-LABEL: %struct.NeedPadTop = type { [4097 x i8], [511 x i8], i32, [508 x i8] }
// CHECK-L64PC128-LABEL: %struct.NeedPadTop = type { [4097 x i8], [7 x i8], i32, [4 x i8] }
struct NeedPadTop {
  char unrepresentable[0x1001] __attribute__((cheri_pad_representable));
  int field;
} s_top;

// CHECK-IL32PC64-LABEL: %struct.NeedPadBoth = type { i32, [508 x i8], [4097 x i8], [511 x i8], i32, [508 x i8] }
// CHECK-L64PC128-LABEL: %struct.NeedPadBoth = type { i32, [4 x i8], [4097 x i8], [7 x i8], i32, [4 x i8] }
struct NeedPadBoth {
  int pre;
  char unrepresentable[0x1001] __attribute__((cheri_pad_representable));
  int post;
} s_both;

// CHECK-IL32PC64-LABEL: %struct.NeedMaxPad = type { i32, [508 x i8], [0 x i8] }
// CHECK-L64PC128-LABEL: %struct.NeedMaxPad = type { i32, [4 x i8], [0 x i8] }
struct NeedMaxPad {
  int pre;
  char unrepresentable[] __attribute__((cheri_pad_representable(0x1000)));
} s_variable;

// CHECK-IL32PC64-LABEL: %struct.NeedMaxPad1 = type { i32, [508 x i8], [1 x i8], [511 x i8] }
// CHECK-L64PC128-LABEL: %struct.NeedMaxPad1 = type { i32, [4 x i8], [1 x i8], [7 x i8] }
struct NeedMaxPad1 {
  int pre;
  char unrepresentable[1] __attribute__((cheri_pad_representable(0x1000)));
} s_variable1;


// CHECK-IL32PC64-LABEL: @large_global = addrspace(200) global [4097 x i8] zeroinitializer, align 1
// CHECK-L64PC128-LABEL: @large_global = addrspace(200) global [4097 x i8] zeroinitializer, align 1
char large_global[0x1001] __attribute__((cheri_pad_representable));

// CHECK-IL32PC64-LABEL: define dso_local ptr addrspace(200) @check_global
// CHECK-IL32PC64-SAME: () addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-IL32PC64-NEXT:  entry:
// CHECK-IL32PC64-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) @large_global, i32 4097)
// CHECK-IL32PC64-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
// CHECK-L64PC128-LABEL: define dso_local ptr addrspace(200) @check_global
// CHECK-L64PC128-SAME: () addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-L64PC128-NEXT:  entry:
// CHECK-L64PC128-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) @large_global, i64 4097)
// CHECK-L64PC128-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
char *check_global() {
  return large_global;
}

// CHECK-IL32PC64-LABEL: define dso_local ptr addrspace(200) @check_global1
// CHECK-IL32PC64-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-IL32PC64-NEXT:  entry:
// CHECK-IL32PC64-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) @large_global, i32 4097)
// CHECK-IL32PC64-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) [[TMP0]], i32 4097)
// CHECK-IL32PC64-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4097 x i8], ptr addrspace(200) [[TMP1]], i32 0, i32 0
// CHECK-IL32PC64-NEXT:    ret ptr addrspace(200) [[ARRAYIDX]]
//
// CHECK-L64PC128-LABEL: define dso_local ptr addrspace(200) @check_global1
// CHECK-L64PC128-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-L64PC128-NEXT:  entry:
// CHECK-L64PC128-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) @large_global, i64 4097)
// CHECK-L64PC128-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[TMP0]], i64 4097)
// CHECK-L64PC128-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4097 x i8], ptr addrspace(200) [[TMP1]], i64 0, i64 0
// CHECK-L64PC128-NEXT:    ret ptr addrspace(200) [[ARRAYIDX]]
//
char *check_global1() {
  return &large_global[0];
}

// CHECK-IL32PC64-LABEL: define dso_local ptr addrspace(200) @get_s_base
// CHECK-IL32PC64-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-IL32PC64-NEXT:  entry:
// CHECK-IL32PC64-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) getelementptr inbounds ([[STRUCT_NEEDPADBASE:%.*]], ptr addrspace(200) @s_base, i32 0, i32 2), i32 4096)
// CHECK-IL32PC64-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
// CHECK-L64PC128-LABEL: define dso_local ptr addrspace(200) @get_s_base
// CHECK-L64PC128-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-L64PC128-NEXT:  entry:
// CHECK-L64PC128-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) getelementptr inbounds ([[STRUCT_NEEDPADBASE:%.*]], ptr addrspace(200) @s_base, i32 0, i32 2), i64 4096)
// CHECK-L64PC128-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
char *get_s_base() {
  return s_base.unrepresentable;
}

// CHECK-IL32PC64-LABEL: define dso_local ptr addrspace(200) @get_s_top
// CHECK-IL32PC64-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-IL32PC64-NEXT:  entry:
// CHECK-IL32PC64-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) @s_top, i32 4097)
// CHECK-IL32PC64-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
// CHECK-L64PC128-LABEL: define dso_local ptr addrspace(200) @get_s_top
// CHECK-L64PC128-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-L64PC128-NEXT:  entry:
// CHECK-L64PC128-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) @s_top, i64 4097)
// CHECK-L64PC128-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
char *get_s_top() {
  return s_top.unrepresentable;
}

// CHECK-IL32PC64-LABEL: define dso_local ptr addrspace(200) @get_s_both
// CHECK-IL32PC64-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-IL32PC64-NEXT:  entry:
// CHECK-IL32PC64-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) getelementptr inbounds ([[STRUCT_NEEDPADBOTH:%.*]], ptr addrspace(200) @s_both, i32 0, i32 2), i32 4097)
// CHECK-IL32PC64-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
// CHECK-L64PC128-LABEL: define dso_local ptr addrspace(200) @get_s_both
// CHECK-L64PC128-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-L64PC128-NEXT:  entry:
// CHECK-L64PC128-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) getelementptr inbounds ([[STRUCT_NEEDPADBOTH:%.*]], ptr addrspace(200) @s_both, i32 0, i32 2), i64 4097)
// CHECK-L64PC128-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
char *get_s_both() {
  return s_both.unrepresentable;
}
