// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
/// Using __capability without the appropriate -march string previously
/// crashed clang during codegen instead of emitting an error earlier.
// RUN: %clang_cc1 -triple riscv64 -fsyntax-only %s -verify=no-cheri
// RUN: %clang_cc1 -triple riscv64 -target-feature +xcheri -fsyntax-only %s -verify=cheri
// cheri-no-diagnostics

// TODO: The message is not quite right (should use qualifier instead of attribute).
void *__capability foo; // no-cheri-error{{'__capability' attribute is not supported on targets missing CHERI; specify an appropriate -march= or -mcpu=}}
