// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUNs: %cheri_purecap_cc1 -fno-delete-null-pointer-checks -munwind-tables -mllvm -cheri-cap-table-abi=pcrel -debug-info-kind=line-tables-only -dwarf-version=5 -debugger-tuning=gdb -nobuiltininc -cheri-uintcap=offset -O2 -std=c++11 -mstack-alignment=16 -S %s -emit-llvm -o %s.opt.ll
// RUNs: %cheri128_purecap_cc1 -fno-delete-null-pointer-checks -munwind-tables -mllvm -cheri-cap-table-abi=pcrel -debug-info-kind=standalone -dwarf-version=2 -debugger-tuning=gdb -nobuiltininc -cheri-uintcap=offset -O2 -std=c++11 -mstack-alignment=16 -o - -S %s
// RUN: %cheri128_purecap_cc1 -fno-delete-null-pointer-checks -cheri-uintcap=offset -O2 -std=c++11 -o - -emit-llvm %s | FileCheck %s
// Check that this no longer crashes:
// RUN: %cheri128_purecap_cc1 -fno-delete-null-pointer-checks -cheri-uintcap=offset -O2 -std=c++11 -o /dev/null -S %s -verify
// REQUIRES: clang

// This previously caused crashes when casting __int128 to __uintcap_t

/// Alignment is 1 for load since we can't know what y contained:
// CHECK-LABEL: define dso_local ptr addrspace(200) @minimal_test_case
// CHECK-SAME: (i128 noundef signext [[Y:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = trunc i128 [[Y]] to i64
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr addrspace(200) null, i64 [[CONV]]
// CHECK-NEXT:    [[R_0_COPYLOAD:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[TMP0]], align 1
// CHECK-NEXT:    ret ptr addrspace(200) [[R_0_COPYLOAD]]
//
extern "C" __uintcap_t minimal_test_case(__int128 y) {
   // expected-warning@-1{{found underaligned load of capability type (aligned to 1 bytes}}
   // expected-note@-2{{use __builtin_assume_aligned() or cast to (u)intptr_t*}}
  __uintcap_t r;
  __builtin_memcpy(&r, (void *)(__uintcap_t)y, sizeof(r));
  return r;
}

/// Alignment is 16 for load due to the explicit cast to __uintcap_t*
// CHECK-LABEL: define dso_local ptr addrspace(200) @minimal_test_case2
// CHECK-SAME: (i128 noundef signext [[Y:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = trunc i128 [[Y]] to i64
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr addrspace(200) null, i64 [[CONV]]
// CHECK-NEXT:    [[R_0_COPYLOAD:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[TMP0]], align 16
// CHECK-NEXT:    ret ptr addrspace(200) [[R_0_COPYLOAD]]
//
extern "C" __uintcap_t minimal_test_case2(__int128 y) {
  __uintcap_t r;
  __builtin_memcpy(&r, (__uintcap_t*)(void *)(__uintcap_t)y, sizeof(r));
  return r;
}

// CHECK-LABEL: define dso_local ptr addrspace(200) @minimal_test_case3
// CHECK-SAME: (i128 noundef signext [[Y:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i128, align 16, addrspace(200)
// CHECK-NEXT:    store i128 [[Y]], ptr addrspace(200) [[Y_ADDR]], align 16, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[Y_ADDR_0_Y_ADDR_0_Y_ADDR_0_Y_ADDR_0_R_0_COPYLOAD:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[Y_ADDR]], align 16
// CHECK-NEXT:    ret ptr addrspace(200) [[Y_ADDR_0_Y_ADDR_0_Y_ADDR_0_Y_ADDR_0_R_0_COPYLOAD]]
//
extern "C" __uintcap_t minimal_test_case3(__int128 y) {
  __uintcap_t r;
  // This is out of bounds for CHERI256: __builtin_memcpy(&r, &y, sizeof(r));
  __builtin_memcpy(&r, &y, sizeof(y));
  return r;
}

// extern "C" __uintcap_t minimal_test_case2(char* buf) {
//   __uintcap_t r;
//   memcpy(&r, buf, sizeof(r));
//   return r;
// }
