; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Previously a call to @llvm.trap() with following code would cause machine
; verifier issues on MIPS (as TRAP was marked as being a terminator).
; This compiles fine on other architectures, so check we do the same for MIPS.
; RUN: sed 's/addrspace(200)/addrspace(0)/' %s | llc -mtriple=mips64-unknown-freebsd -relocation-model=pic -verify-machineinstrs | FileCheck %s --check-prefix=MIPS
; RUN: %cheri_purecap_llc -o - %s -verify-machineinstrs  | FileCheck %s --check-prefix=PURECAP
; For comparison, this works for X86
; RUNNOT: sed 's/addrspace(200)/addrspace(0)/' %s | llc -mtriple=x86_64-unknown-freebsd -relocation-model=pic -verify-machineinstrs | FileCheck %s --check-prefix=MIPS


declare void @llvm.trap() addrspace(200) #0
declare void @widget() addrspace(200) #1
define hidden void @eggs() addrspace(200) #1 {
; MIPS-LABEL: eggs:
; MIPS:       # %bb.0: # %entry
; MIPS-NEXT:    daddiu $sp, $sp, -[[#STACKFRAME_SIZE:]]
; MIPS-NEXT:    sd $ra, 8($sp) # 8-byte Folded Spill
; MIPS-NEXT:    sd $gp, 0($sp) # 8-byte Folded Spill
; MIPS-NEXT:    lui $1, %hi(%neg(%gp_rel(eggs)))
; MIPS-NEXT:    daddu $1, $1, $25
; MIPS-NEXT:    daddiu $gp, $1, %lo(%neg(%gp_rel(eggs)))
; MIPS-NEXT:    break
; MIPS-NEXT:    ld $25, %call16(widget)($gp)
; MIPS-NEXT:    .reloc .Ltmp0, R_MIPS_JALR, widget
; MIPS-NEXT:  .Ltmp0:
; MIPS-NEXT:    jalr $25
; MIPS-NEXT:    nop
;
; PURECAP-LABEL: eggs:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset $c11, $c11, -[[#STACKFRAME_SIZE:]]
; PURECAP-NEXT:    csc $c17, $zero, 0($c11)
; PURECAP-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; PURECAP-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; PURECAP-NEXT:    cgetpccincoffset $c1, $1
; PURECAP-NEXT:    break
; PURECAP-NEXT:    clcbi $c12, %capcall20(widget)($c1)
; PURECAP-NEXT:    cjalr $c12, $c17
; PURECAP-NEXT:    nop
entry:
  call void @llvm.trap()
  call void @widget() #2
  unreachable
}

attributes #0 = { cold noreturn nounwind }
attributes #1 = { nounwind "use-soft-float"="true" }
attributes #2 = { noreturn }
