; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64 -mattr=+m -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=RV64I
; RUN: llc -mtriple=riscv64 -mattr=+m,+zish4add -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=RV64ZISH4ADD
; RUN: llc -mtriple=riscv64 -mattr=+m,+zish4add,+zba -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=RV64ZISH4ADD_ZBA

define i128 @sh4add(i64 %0, ptr %1){
; RV64I-LABEL: sh4add:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 4
; RV64I-NEXT:    add a1, a1, a0
; RV64I-NEXT:    ld a0, 0(a1)
; RV64I-NEXT:    ld a1, 8(a1)
; RV64I-NEXT:    ret
;
; RV64ZISH4ADD-LABEL: sh4add:
; RV64ZISH4ADD:       # %bb.0:
; RV64ZISH4ADD-NEXT:    sh4add a1, a0, a1
; RV64ZISH4ADD-NEXT:    ld a0, 0(a1)
; RV64ZISH4ADD-NEXT:    ld a1, 8(a1)
; RV64ZISH4ADD-NEXT:    ret
;
; RV64ZISH4ADD_ZBA-LABEL: sh4add:
; RV64ZISH4ADD_ZBA:       # %bb.0:
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a1, a0, a1
; RV64ZISH4ADD_ZBA-NEXT:    ld a0, 0(a1)
; RV64ZISH4ADD_ZBA-NEXT:    ld a1, 8(a1)
; RV64ZISH4ADD_ZBA-NEXT:    ret
    %3 = getelementptr inbounds i128, ptr %1, i64 %0
    %4 = load i128, ptr %3
    ret i128 %4
}

define signext i64 @sh4add_mult(i64 %0, i64 %1){
; RV64I-LABEL: sh4add_mult:
; RV64I:       # %bb.0:
; RV64I-NEXT:    slli a0, a0, 4
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64ZISH4ADD-LABEL: sh4add_mult:
; RV64ZISH4ADD:       # %bb.0:
; RV64ZISH4ADD-NEXT:    sh4add a0, a0, a1
; RV64ZISH4ADD-NEXT:    ret
;
; RV64ZISH4ADD_ZBA-LABEL: sh4add_mult:
; RV64ZISH4ADD_ZBA:       # %bb.0:
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a0, a0, a1
; RV64ZISH4ADD_ZBA-NEXT:    ret
  %a = shl i64 %0, 4
  %b = add i64 %a, %1
  ret i64 %b
}

define i64 @addmul272(i64 %a, i64 %b) {
; RV64I-LABEL: addmul272:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a2, 272
; RV64I-NEXT:    mul a0, a0, a2
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64ZISH4ADD-LABEL: addmul272:
; RV64ZISH4ADD:       # %bb.0:
; RV64ZISH4ADD-NEXT:    sh4add a0, a0, a0
; RV64ZISH4ADD-NEXT:    sh4add a0, a0, a1
; RV64ZISH4ADD-NEXT:    ret
;
; RV64ZISH4ADD_ZBA-LABEL: addmul272:
; RV64ZISH4ADD_ZBA:       # %bb.0:
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a0, a0, a0
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a0, a0, a1
; RV64ZISH4ADD_ZBA-NEXT:    ret
  %c = mul i64 %a, 272
  %d = add i64 %c, %b
  ret i64 %d
}

define i64 @addmul34(i64 %a, i64 %b) {
; RV64I-LABEL: addmul34:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a2, 34
; RV64I-NEXT:    mul a0, a0, a2
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64ZISH4ADD-LABEL: addmul34:
; RV64ZISH4ADD:       # %bb.0:
; RV64ZISH4ADD-NEXT:    li a2, 34
; RV64ZISH4ADD-NEXT:    mul a0, a0, a2
; RV64ZISH4ADD-NEXT:    add a0, a0, a1
; RV64ZISH4ADD-NEXT:    ret
;
; RV64ZISH4ADD_ZBA-LABEL: addmul34:
; RV64ZISH4ADD_ZBA:       # %bb.0:
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a0, a0, a0
; RV64ZISH4ADD_ZBA-NEXT:    sh1add a0, a0, a1
; RV64ZISH4ADD_ZBA-NEXT:    ret
  %c = mul i64 %a, 34
  %d = add i64 %c, %b
  ret i64 %d
}

define i64 @addmul68(i64 %a, i64 %b) {
; RV64I-LABEL: addmul68:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a2, 68
; RV64I-NEXT:    mul a0, a0, a2
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64ZISH4ADD-LABEL: addmul68:
; RV64ZISH4ADD:       # %bb.0:
; RV64ZISH4ADD-NEXT:    li a2, 68
; RV64ZISH4ADD-NEXT:    mul a0, a0, a2
; RV64ZISH4ADD-NEXT:    add a0, a0, a1
; RV64ZISH4ADD-NEXT:    ret
;
; RV64ZISH4ADD_ZBA-LABEL: addmul68:
; RV64ZISH4ADD_ZBA:       # %bb.0:
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a0, a0, a0
; RV64ZISH4ADD_ZBA-NEXT:    sh2add a0, a0, a1
; RV64ZISH4ADD_ZBA-NEXT:    ret
  %c = mul i64 %a, 68
  %d = add i64 %c, %b
  ret i64 %d
}

define i64 @addmul136(i64 %a, i64 %b) {
; RV64I-LABEL: addmul136:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a2, 136
; RV64I-NEXT:    mul a0, a0, a2
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64ZISH4ADD-LABEL: addmul136:
; RV64ZISH4ADD:       # %bb.0:
; RV64ZISH4ADD-NEXT:    li a2, 136
; RV64ZISH4ADD-NEXT:    mul a0, a0, a2
; RV64ZISH4ADD-NEXT:    add a0, a0, a1
; RV64ZISH4ADD-NEXT:    ret
;
; RV64ZISH4ADD_ZBA-LABEL: addmul136:
; RV64ZISH4ADD_ZBA:       # %bb.0:
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a0, a0, a0
; RV64ZISH4ADD_ZBA-NEXT:    sh3add a0, a0, a1
; RV64ZISH4ADD_ZBA-NEXT:    ret
  %c = mul i64 %a, 136
  %d = add i64 %c, %b
  ret i64 %d
}

define i64 @addmul48(i64 %a, i64 %b) {
; RV64I-LABEL: addmul48:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a2, 48
; RV64I-NEXT:    mul a0, a0, a2
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64ZISH4ADD-LABEL: addmul48:
; RV64ZISH4ADD:       # %bb.0:
; RV64ZISH4ADD-NEXT:    li a2, 48
; RV64ZISH4ADD-NEXT:    mul a0, a0, a2
; RV64ZISH4ADD-NEXT:    add a0, a0, a1
; RV64ZISH4ADD-NEXT:    ret
;
; RV64ZISH4ADD_ZBA-LABEL: addmul48:
; RV64ZISH4ADD_ZBA:       # %bb.0:
; RV64ZISH4ADD_ZBA-NEXT:    sh1add a0, a0, a0
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a0, a0, a1
; RV64ZISH4ADD_ZBA-NEXT:    ret
  %c = mul i64 %a, 48
  %d = add i64 %c, %b
  ret i64 %d
}

define i64 @addmul80(i64 %a, i64 %b) {
; RV64I-LABEL: addmul80:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a2, 80
; RV64I-NEXT:    mul a0, a0, a2
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64ZISH4ADD-LABEL: addmul80:
; RV64ZISH4ADD:       # %bb.0:
; RV64ZISH4ADD-NEXT:    li a2, 80
; RV64ZISH4ADD-NEXT:    mul a0, a0, a2
; RV64ZISH4ADD-NEXT:    add a0, a0, a1
; RV64ZISH4ADD-NEXT:    ret
;
; RV64ZISH4ADD_ZBA-LABEL: addmul80:
; RV64ZISH4ADD_ZBA:       # %bb.0:
; RV64ZISH4ADD_ZBA-NEXT:    sh2add a0, a0, a0
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a0, a0, a1
; RV64ZISH4ADD_ZBA-NEXT:    ret
  %c = mul i64 %a, 80
  %d = add i64 %c, %b
  ret i64 %d
}

define i64 @addmul144(i64 %a, i64 %b) {
; RV64I-LABEL: addmul144:
; RV64I:       # %bb.0:
; RV64I-NEXT:    li a2, 144
; RV64I-NEXT:    mul a0, a0, a2
; RV64I-NEXT:    add a0, a0, a1
; RV64I-NEXT:    ret
;
; RV64ZISH4ADD-LABEL: addmul144:
; RV64ZISH4ADD:       # %bb.0:
; RV64ZISH4ADD-NEXT:    li a2, 144
; RV64ZISH4ADD-NEXT:    mul a0, a0, a2
; RV64ZISH4ADD-NEXT:    add a0, a0, a1
; RV64ZISH4ADD-NEXT:    ret
;
; RV64ZISH4ADD_ZBA-LABEL: addmul144:
; RV64ZISH4ADD_ZBA:       # %bb.0:
; RV64ZISH4ADD_ZBA-NEXT:    sh3add a0, a0, a0
; RV64ZISH4ADD_ZBA-NEXT:    sh4add a0, a0, a1
; RV64ZISH4ADD_ZBA-NEXT:    ret
  %c = mul i64 %a, 144
  %d = add i64 %c, %b
  ret i64 %d
}
