; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/frameindex-arith.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+cap-mode,+f %s -o - | FileCheck %s

; Check that we can fold the GEP (PTRADD) into the FrameIndex calculation
; rather than emitting two instructions.

; Contains an explicit @llvm.cheri.cap.bounds.set so CheriBoundAllocas sees the
; use as safe and doesn't interfere by inserting bounds on the FrameIndex
; before the GEP/PTRADD.
define void @foo() nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cincoffset csp, csp, -16
; CHECK-NEXT:    sc cra, 8(csp) # 8-byte Folded Spill
; CHECK-NEXT:    cincoffset ca0, csp, 7
; CHECK-NEXT:    csetbounds ca0, ca0, 0
; CHECK-NEXT:    ccall bar
; CHECK-NEXT:    lc cra, 8(csp) # 8-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 16
; CHECK-NEXT:    ret
  %x = alloca [2 x i8], align 1, addrspace(200)
  %x_plus_1 = getelementptr inbounds [2 x i8], ptr addrspace(200) %x, i32 0, i32 1
  %p = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) %x_plus_1, i32 0)
  call void @bar(ptr addrspace(200) %p)
  ret void
}

declare void @bar(ptr addrspace(200))

declare ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200), i32)
