; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/memcpy-zeroinit.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+cap-mode,+f < %s -o - | FileCheck %s
; Check that the copy from the zeroinitializer global is turned into a series of zero stores
; or memset() as long as the memcpy is not volatile:

%struct.umutex = type { i32, i32, [2 x i32], ptr addrspace(200), i32, [2 x i32] }

@_thr_umutex_init.default_mtx = internal addrspace(200) constant %struct.umutex zeroinitializer, align 16

define void @_thr_umutex_init(ptr addrspace(200) %mtx) local_unnamed_addr addrspace(200) nounwind "frame-pointer"="none" {
; CHECK-LABEL: _thr_umutex_init:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sc cnull, 40(ca0)
; CHECK-NEXT:    sc cnull, 32(ca0)
; CHECK-NEXT:    sc cnull, 24(ca0)
; CHECK-NEXT:    sc cnull, 16(ca0)
; CHECK-NEXT:    sc cnull, 8(ca0)
; CHECK-NEXT:    sc cnull, 0(ca0)
; CHECK-NEXT:    ret
  tail call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 %mtx, ptr addrspace(200) align 16 @_thr_umutex_init.default_mtx, i64 48, i1 false)
  ret void
}

define void @_thr_umutex_init_volatile(ptr addrspace(200) %mtx) local_unnamed_addr addrspace(200) nounwind "frame-pointer"="none" {
; CHECK-LABEL: _thr_umutex_init_volatile:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB1_1: # Label of block must be emitted
; CHECK-NEXT:    auipcc ca1, %got_pcrel_hi(_thr_umutex_init.default_mtx)
; CHECK-NEXT:    lc ca1, %pcrel_lo(.LBB1_1)(ca1)
; CHECK-NEXT:    lc ca2, 40(ca1)
; CHECK-NEXT:    sc ca2, 40(ca0)
; CHECK-NEXT:    lc ca2, 32(ca1)
; CHECK-NEXT:    sc ca2, 32(ca0)
; CHECK-NEXT:    lc ca2, 24(ca1)
; CHECK-NEXT:    sc ca2, 24(ca0)
; CHECK-NEXT:    lc ca2, 16(ca1)
; CHECK-NEXT:    sc ca2, 16(ca0)
; CHECK-NEXT:    lc ca2, 8(ca1)
; CHECK-NEXT:    sc ca2, 8(ca0)
; CHECK-NEXT:    lc ca1, 0(ca1)
; CHECK-NEXT:    sc ca1, 0(ca0)
; CHECK-NEXT:    ret
  tail call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 %mtx, ptr addrspace(200) align 16 @_thr_umutex_init.default_mtx, i64 48, i1 true)
  ret void
}

declare void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) noalias nocapture writeonly %0, ptr addrspace(200) noalias nocapture readonly %1, i64 %2, i1 immarg %3) addrspace(200)
