; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 4
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/stackframe-intrinsics.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+cap-mode,+f %s -o - < %s | FileCheck %s --check-prefix=PURECAP
; RUN: sed 's/addrspace(200)/addrspace(0)/g' %s | llc -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+xcheri,+f | FileCheck %s --check-prefix HYBRID
; Check that we can lower llvm.frameaddress/llvm.returnaddress

; Capability-Inspection Instructions

define dso_local ptr addrspace(200) @frameaddr() addrspace(200) nounwind {
; PURECAP-LABEL: frameaddr:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset csp, csp, -32
; PURECAP-NEXT:    sc cra, 24(csp) # 8-byte Folded Spill
; PURECAP-NEXT:    sc cs0, 16(csp) # 8-byte Folded Spill
; PURECAP-NEXT:    cincoffset cs0, csp, 32
; PURECAP-NEXT:    sc cs0, -32(cs0)
; PURECAP-NEXT:    cmove ca0, cs0
; PURECAP-NEXT:    lc cra, 24(csp) # 8-byte Folded Reload
; PURECAP-NEXT:    lc cs0, 16(csp) # 8-byte Folded Reload
; PURECAP-NEXT:    cincoffset csp, csp, 32
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: frameaddr:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; HYBRID-NEXT:    sw s0, 8(sp) # 4-byte Folded Spill
; HYBRID-NEXT:    addi s0, sp, 16
; HYBRID-NEXT:    sw s0, -16(s0)
; HYBRID-NEXT:    mv a0, s0
; HYBRID-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; HYBRID-NEXT:    lw s0, 8(sp) # 4-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
entry:
  %b = alloca ptr addrspace(200), align 16, addrspace(200)
  %0 = call ptr addrspace(200) @llvm.frameaddress.p200(i32 0)
  store ptr addrspace(200) %0, ptr addrspace(200) %b, align 16
  %1 = load ptr addrspace(200), ptr addrspace(200) %b, align 16
  ret ptr addrspace(200) %1
}

declare ptr addrspace(200) @llvm.frameaddress.p200(i32 immarg) addrspace(200)

define dso_local ptr addrspace(200) @retaddr() addrspace(200) nounwind {
; PURECAP-LABEL: retaddr:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    cincoffset csp, csp, -16
; PURECAP-NEXT:    sc cra, 0(csp)
; PURECAP-NEXT:    cmove ca0, cra
; PURECAP-NEXT:    cincoffset csp, csp, 16
; PURECAP-NEXT:    ret
;
; HYBRID-LABEL: retaddr:
; HYBRID:       # %bb.0: # %entry
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sw ra, 0(sp)
; HYBRID-NEXT:    mv a0, ra
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
entry:
  %b = alloca ptr addrspace(200), align 16, addrspace(200)
  %0 = call ptr addrspace(200) @llvm.returnaddress.p200(i32 0)
  store ptr addrspace(200) %0, ptr addrspace(200) %b, align 16
  %1 = load ptr addrspace(200), ptr addrspace(200) %b, align 16
  ret ptr addrspace(200) %1
}

declare ptr addrspace(200) @llvm.returnaddress.p200(i32 immarg) addrspace(200)
