; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64-unknown-freebsd -mattr=+xcheri,+cap-mode,+cheri-bounded-vararg -target-abi l64pc128d -o - %s | FileCheck %s

%struct.inmem = type { float, float, float, float, [4 x i32] }

define i32 @caller_test_scalars(i32 %x, i128 %y, i64 %z, float %f, double %d) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: caller_test_scalars:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -176
; CHECK-NEXT:    sc cra, 160(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs0, 144(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs1, 128(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs2, 112(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs3, 96(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs4, 80(csp) # 16-byte Folded Spill
; CHECK-NEXT:    mv s0, a5
; CHECK-NEXT:    mv s1, a3
; CHECK-NEXT:    mv s2, a2
; CHECK-NEXT:    mv s3, a1
; CHECK-NEXT:    mv s4, a0
; CHECK-NEXT:    slli a0, a4, 32
; CHECK-NEXT:    srli a0, a0, 32
; CHECK-NEXT:    call __extendsfdf2
; CHECK-NEXT:    mv a1, a0
; CHECK-NEXT:    sd s0, 64(csp)
; CHECK-NEXT:    sd s1, 32(csp)
; CHECK-NEXT:    sd s2, 24(csp)
; CHECK-NEXT:    sd s3, 16(csp)
; CHECK-NEXT:    sd s4, 0(csp)
; CHECK-NEXT:    csetbounds ca0, csp, 80
; CHECK-NEXT:    li a2, -11
; CHECK-NEXT:    candperm ct1, ca0, a2
; CHECK-NEXT:    li a0, 5
; CHECK-NEXT:    sd a1, 48(csp)
; CHECK-NEXT:    call callee
; CHECK-NEXT:    lc cra, 160(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs0, 144(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs1, 128(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs2, 112(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs3, 96(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs4, 80(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 176
; CHECK-NEXT:    ret
entry:
  %conv = fpext float %f to double
  %call = tail call i32 (i32, ...) @callee(i32 5, i32 %x, i128 %y, i64 %z, double %conv, double %d)
  ret i32 %call
}

declare i32 @callee(i32, ...) local_unnamed_addr addrspace(200) nounwind

declare dso_local signext i32 @sum(i32 noundef signext %count, ...) addrspace(200) nounwind;
define dso_local signext i32 @foo() addrspace(200) nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -48
; CHECK-NEXT:    sc cra, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:    sd a1, 16(csp)
; CHECK-NEXT:    csetbounds ca0, csp, 32
; CHECK-NEXT:    li a2, -11
; CHECK-NEXT:    candperm ct1, ca0, a2
; CHECK-NEXT:    li a0, 2
; CHECK-NEXT:    sd a1, 0(csp)
; CHECK-NEXT:    call sum
; CHECK-NEXT:    lc cra, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 48
; CHECK-NEXT:    ret
entry:
  %call = call signext i32 (i32, ...) @sum(i32 noundef signext 2, i32 noundef signext 1, i32 noundef signext 1)
  ret i32 %call
}


define i32 @caller_test_struct(i32 %x, [2 x float] %y.coerce, i32 %z, { i8 addrspace(200)*, i64} %u.coerce) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: caller_test_struct:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -96
; CHECK-NEXT:    sc cra, 80(csp) # 16-byte Folded Spill
; CHECK-NEXT:    mv a6, a0
; CHECK-NEXT:    sd a5, 64(csp)
; CHECK-NEXT:    sc ca4, 48(csp)
; CHECK-NEXT:    sd a3, 32(csp)
; CHECK-NEXT:    sd a2, 24(csp)
; CHECK-NEXT:    sd a1, 16(csp)
; CHECK-NEXT:    csetbounds ca0, csp, 80
; CHECK-NEXT:    li a1, -11
; CHECK-NEXT:    candperm ct1, ca0, a1
; CHECK-NEXT:    li a0, 3
; CHECK-NEXT:    sd a6, 0(csp)
; CHECK-NEXT:    call callee
; CHECK-NEXT:    lc cra, 80(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 96
; CHECK-NEXT:    ret
entry:
  %call = tail call i32 (i32, ...) @callee(i32 3, i32 %x, [2 x float] %y.coerce, i32 %z, { i8 addrspace(200)*, i64} %u.coerce) nounwind
  ret i32 %call
}

define i32 @caller_test_inmem_struct(%struct.inmem addrspace(200)* nocapture readonly %x) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: caller_test_inmem_struct:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -80
; CHECK-NEXT:    sc cra, 64(csp) # 16-byte Folded Spill
; CHECK-NEXT:    sc cs0, 48(csp) # 16-byte Folded Spill
; CHECK-NEXT:    cmove ca1, ca0
; CHECK-NEXT:    cincoffset ca0, csp, 16
; CHECK-NEXT:    csetbounds cs0, ca0, 32
; CHECK-NEXT:    li a2, 32
; CHECK-NEXT:    cmove ca0, cs0
; CHECK-NEXT:    call memcpy
; CHECK-NEXT:    csetbounds ca0, csp, 16
; CHECK-NEXT:    li a1, -11
; CHECK-NEXT:    candperm ct1, ca0, a1
; CHECK-NEXT:    li a0, 1
; CHECK-NEXT:    sc cs0, 0(csp)
; CHECK-NEXT:    call callee
; CHECK-NEXT:    lc cra, 64(csp) # 16-byte Folded Reload
; CHECK-NEXT:    lc cs0, 48(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 80
; CHECK-NEXT:    ret
entry:
  %byval-temp = alloca %struct.inmem, align 4, addrspace(200)
  %0 = bitcast %struct.inmem addrspace(200)* %byval-temp to i8 addrspace(200)*
  call void @llvm.lifetime.start.p200(i64 32, i8 addrspace(200)* nonnull %0) #0
  %1 = bitcast %struct.inmem addrspace(200)* %x to i8 addrspace(200)*
  call void @llvm.memcpy.p200.p200.i64(i8 addrspace(200)* nonnull align 4 dereferenceable(32) %0, i8 addrspace(200)* nonnull align 4 dereferenceable(32) %1, i64 32, i1 false)
  %call = call i32 (i32, ...) @callee(i32 1, %struct.inmem addrspace(200)* nonnull %byval-temp) #0
  call void @llvm.lifetime.end.p200(i64 32, i8 addrspace(200)* nonnull %0) #0
  ret i32 %call
}


define i32 @test_noargs() local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: test_noargs:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a0, 100
; CHECK-NEXT:    cmove ct1, cnull
; CHECK-NEXT:    tail callee
entry:
  %call = tail call i32 (i32, ...) @callee(i32 100) #0
  ret i32 %call
}
declare void @llvm.lifetime.start.p200(i64 immarg, i8 addrspace(200)* nocapture) addrspace(200) #0

declare void @llvm.memcpy.p200.p200.i64(i8 addrspace(200)* noalias nocapture writeonly, i8 addrspace(200)* noalias nocapture readonly, i64, i1 immarg) addrspace(200) #0

declare void @llvm.lifetime.end.p200(i64 immarg, i8 addrspace(200)* nocapture) addrspace(200) #0

define void @callee_test_scalars(i32 %count, ...) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: callee_test_scalars:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -48
; CHECK-NEXT:    sc cra, 32(csp) # 16-byte Folded Spill
; CHECK-NEXT:    cincoffset ca0, csp, 16
; CHECK-NEXT:    csetbounds ca0, ca0, 16
; CHECK-NEXT:    sc ct1, 0(ca0)
; CHECK-NEXT:    lc ca1, 16(csp)
; CHECK-NEXT:    sc ct1, 0(csp)
; CHECK-NEXT:    cincoffset ca0, ca1, 16
; CHECK-NEXT:    sc ca0, 16(csp)
; CHECK-NEXT:    cincoffset ca2, ca1, 32
; CHECK-NEXT:    ld a0, 0(ca1)
; CHECK-NEXT:    sc ca2, 16(csp)
; CHECK-NEXT:    lw a1, 16(ca1)
; CHECK-NEXT:    call call1
; CHECK-NEXT:    lc cra, 32(csp) # 16-byte Folded Reload
; CHECK-NEXT:    cincoffset csp, csp, 48
; CHECK-NEXT:    ret
entry:
  %args = alloca i8 addrspace(200)*, align 16, addrspace(200)
  %0 = bitcast i8 addrspace(200)* addrspace(200)* %args to i8 addrspace(200)*
  call void @llvm.lifetime.start.p200(i64 16, i8 addrspace(200)* nonnull %0) #0
  call void @llvm.va_start.p200(i8 addrspace(200)* nonnull %0)
  %stack = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %args, align 16
  %1 = bitcast i8 addrspace(200)* %stack to double addrspace(200)*
  %new_stack = getelementptr inbounds i8, i8 addrspace(200)* %stack, i64 16
  store i8 addrspace(200)* %new_stack, i8 addrspace(200)* addrspace(200)* %args, align 16
  %2 = load double, double addrspace(200)* %1, align 16
  %3 = bitcast i8 addrspace(200)* %new_stack to float addrspace(200)*
  %new_stack4 = getelementptr inbounds i8, i8 addrspace(200)* %stack, i64 32
  store i8 addrspace(200)* %new_stack4, i8 addrspace(200)* addrspace(200)* %args, align 16
  %4 = load float, float addrspace(200)* %3, align 16
  call void @llvm.va_end.p200(i8 addrspace(200)* nonnull %0)
  call void @call1(double %2, float %4) #3
  call void @llvm.lifetime.end.p200(i64 16, i8 addrspace(200)* nonnull %0) #0
  ret void
}

define i8 addrspace(200)* @test_vacopy(i32 %count, ...) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: test_vacopy:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset csp, csp, -48
; CHECK-NEXT:    cincoffset ca0, csp, 32
; CHECK-NEXT:    csetbounds ca0, ca0, 16
; CHECK-NEXT:    sc ct1, 0(ca0)
; CHECK-NEXT:    lc ca0, 32(csp)
; CHECK-NEXT:    cincoffset ca1, csp, 16
; CHECK-NEXT:    csetbounds ca1, ca1, 16
; CHECK-NEXT:    sc ct1, 0(ca1)
; CHECK-NEXT:    sc ct1, 0(csp)
; CHECK-NEXT:    cincoffset csp, csp, 48
; CHECK-NEXT:    ret
entry:
  %retval = alloca i8 addrspace(200)*, align 16, addrspace(200)
  %args = alloca i8 addrspace(200)*, align 16, addrspace(200)
  %0 = bitcast i8 addrspace(200)* addrspace(200)* %args to i8 addrspace(200)*
  call void @llvm.lifetime.start.p200(i64 16, i8 addrspace(200)* nonnull %0) #0
  call void @llvm.va_start.p200(i8 addrspace(200)* nonnull %0)
  %1 = bitcast i8 addrspace(200)* addrspace(200)* %retval to i8 addrspace(200)*
  call void @llvm.va_copy.p200.p200(i8 addrspace(200)* nonnull %1, i8 addrspace(200)* nonnull %0)
  call void @llvm.lifetime.end.p200(i64 16, i8 addrspace(200)* nonnull %0) #0
  %2 = load i8 addrspace(200)*, i8 addrspace(200)* addrspace(200)* %retval, align 16
  ret i8 addrspace(200)* %2
}

declare void @llvm.va_copy.p200.p200(i8 addrspace(200)*, i8 addrspace(200)*) addrspace(200) #0

declare void @llvm.va_start.p200(i8 addrspace(200)*) addrspace(200) #0

declare void @llvm.va_end.p200(i8 addrspace(200)*) addrspace(200) #0

declare void @call1(double, float) local_unnamed_addr addrspace(200) #0

attributes #0 = { nounwind }
