; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv32 -mattr=+zcheripurecap,+cap-mode -target-abi=il32pc64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=RV32
; RUN: llc -mtriple=riscv64 -mattr=+zcheripurecap,+cap-mode -target-abi=l64pc128 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefixes=RV64

define void @f1() shadowcallstack {
; RV32-LABEL: f1:
; RV32:       # %bb.0:
; RV32-NEXT:    ret
;
; RV64-LABEL: f1:
; RV64:       # %bb.0:
; RV64-NEXT:    ret
  ret void
}

declare void @foo()

define void @f2() shadowcallstack {
; RV32-LABEL: f2:
; RV32:       # %bb.0:
; RV32-NEXT:    tail foo
;
; RV64-LABEL: f2:
; RV64:       # %bb.0:
; RV64-NEXT:    tail foo
  tail call void @foo()
  ret void
}

declare i32 @bar()

define i32 @f3() shadowcallstack {
; RV32-LABEL: f3:
; RV32:       # %bb.0:
; RV32-NEXT:    caddi cgp, cgp, 8
; RV32-NEXT:    sc cra, -8(cgp)
; RV32-NEXT:    .cfi_escape 0x16, 0x03, 0x02, 0x73, 0x78 #
; RV32-NEXT:    caddi csp, csp, -16
; RV32-NEXT:    .cfi_def_cfa_offset 16
; RV32-NEXT:    sc cra, 8(csp) # 8-byte Folded Spill
; RV32-NEXT:    .cfi_offset ra, -8
; RV32-NEXT:    call bar
; RV32-NEXT:    lc cra, 8(csp) # 8-byte Folded Reload
; RV32-NEXT:    caddi csp, csp, 16
; RV32-NEXT:    lc cra, -8(cgp)
; RV32-NEXT:    caddi cgp, cgp, -8
; RV32-NEXT:    .cfi_restore gp
; RV32-NEXT:    ret
;
; RV64-LABEL: f3:
; RV64:       # %bb.0:
; RV64-NEXT:    caddi cgp, cgp, 16
; RV64-NEXT:    sc cra, -16(cgp)
; RV64-NEXT:    .cfi_escape 0x16, 0x03, 0x02, 0x73, 0x70 #
; RV64-NEXT:    caddi csp, csp, -16
; RV64-NEXT:    .cfi_def_cfa_offset 16
; RV64-NEXT:    sc cra, 0(csp) # 16-byte Folded Spill
; RV64-NEXT:    .cfi_offset ra, -16
; RV64-NEXT:    call bar
; RV64-NEXT:    lc cra, 0(csp) # 16-byte Folded Reload
; RV64-NEXT:    caddi csp, csp, 16
; RV64-NEXT:    lc cra, -16(cgp)
; RV64-NEXT:    caddi cgp, cgp, -16
; RV64-NEXT:    .cfi_restore gp
; RV64-NEXT:    ret
  %res = call i32 @bar()
  %res1 = add i32 %res, 1
  ret i32 %res
}

define i32 @f4() shadowcallstack {
; RV32-LABEL: f4:
; RV32:       # %bb.0:
; RV32-NEXT:    caddi cgp, cgp, 8
; RV32-NEXT:    sc cra, -8(cgp)
; RV32-NEXT:    .cfi_escape 0x16, 0x03, 0x02, 0x73, 0x78 #
; RV32-NEXT:    caddi csp, csp, -32
; RV32-NEXT:    .cfi_def_cfa_offset 32
; RV32-NEXT:    sc cra, 24(csp) # 8-byte Folded Spill
; RV32-NEXT:    sc cs0, 16(csp) # 8-byte Folded Spill
; RV32-NEXT:    sc cs1, 8(csp) # 8-byte Folded Spill
; RV32-NEXT:    sc cs2, 0(csp) # 8-byte Folded Spill
; RV32-NEXT:    .cfi_offset ra, -8
; RV32-NEXT:    .cfi_offset s0, -16
; RV32-NEXT:    .cfi_offset s1, -24
; RV32-NEXT:    .cfi_offset s2, -32
; RV32-NEXT:    call bar
; RV32-NEXT:    mv s0, a0
; RV32-NEXT:    call bar
; RV32-NEXT:    mv s1, a0
; RV32-NEXT:    call bar
; RV32-NEXT:    mv s2, a0
; RV32-NEXT:    call bar
; RV32-NEXT:    add s0, s0, s1
; RV32-NEXT:    add a0, s2, a0
; RV32-NEXT:    add a0, s0, a0
; RV32-NEXT:    lc cra, 24(csp) # 8-byte Folded Reload
; RV32-NEXT:    lc cs0, 16(csp) # 8-byte Folded Reload
; RV32-NEXT:    lc cs1, 8(csp) # 8-byte Folded Reload
; RV32-NEXT:    lc cs2, 0(csp) # 8-byte Folded Reload
; RV32-NEXT:    caddi csp, csp, 32
; RV32-NEXT:    lc cra, -8(cgp)
; RV32-NEXT:    caddi cgp, cgp, -8
; RV32-NEXT:    .cfi_restore gp
; RV32-NEXT:    ret
;
; RV64-LABEL: f4:
; RV64:       # %bb.0:
; RV64-NEXT:    caddi cgp, cgp, 16
; RV64-NEXT:    sc cra, -16(cgp)
; RV64-NEXT:    .cfi_escape 0x16, 0x03, 0x02, 0x73, 0x70 #
; RV64-NEXT:    caddi csp, csp, -64
; RV64-NEXT:    .cfi_def_cfa_offset 64
; RV64-NEXT:    sc cra, 48(csp) # 16-byte Folded Spill
; RV64-NEXT:    sc cs0, 32(csp) # 16-byte Folded Spill
; RV64-NEXT:    sc cs1, 16(csp) # 16-byte Folded Spill
; RV64-NEXT:    sc cs2, 0(csp) # 16-byte Folded Spill
; RV64-NEXT:    .cfi_offset ra, -16
; RV64-NEXT:    .cfi_offset s0, -32
; RV64-NEXT:    .cfi_offset s1, -48
; RV64-NEXT:    .cfi_offset s2, -64
; RV64-NEXT:    call bar
; RV64-NEXT:    mv s0, a0
; RV64-NEXT:    call bar
; RV64-NEXT:    mv s1, a0
; RV64-NEXT:    call bar
; RV64-NEXT:    mv s2, a0
; RV64-NEXT:    call bar
; RV64-NEXT:    add s0, s0, s1
; RV64-NEXT:    add a0, s2, a0
; RV64-NEXT:    addw a0, s0, a0
; RV64-NEXT:    lc cra, 48(csp) # 16-byte Folded Reload
; RV64-NEXT:    lc cs0, 32(csp) # 16-byte Folded Reload
; RV64-NEXT:    lc cs1, 16(csp) # 16-byte Folded Reload
; RV64-NEXT:    lc cs2, 0(csp) # 16-byte Folded Reload
; RV64-NEXT:    caddi csp, csp, 64
; RV64-NEXT:    lc cra, -16(cgp)
; RV64-NEXT:    caddi cgp, cgp, -16
; RV64-NEXT:    .cfi_restore gp
; RV64-NEXT:    ret
  %res1 = call i32 @bar()
  %res2 = call i32 @bar()
  %res3 = call i32 @bar()
  %res4 = call i32 @bar()
  %res12 = add i32 %res1, %res2
  %res34 = add i32 %res3, %res4
  %res1234 = add i32 %res12, %res34
  ret i32 %res1234
}

define i32 @f5() shadowcallstack nounwind {
; RV32-LABEL: f5:
; RV32:       # %bb.0:
; RV32-NEXT:    caddi cgp, cgp, 8
; RV32-NEXT:    sc cra, -8(cgp)
; RV32-NEXT:    caddi csp, csp, -16
; RV32-NEXT:    sc cra, 8(csp) # 8-byte Folded Spill
; RV32-NEXT:    call bar
; RV32-NEXT:    lc cra, 8(csp) # 8-byte Folded Reload
; RV32-NEXT:    caddi csp, csp, 16
; RV32-NEXT:    lc cra, -8(cgp)
; RV32-NEXT:    caddi cgp, cgp, -8
; RV32-NEXT:    ret
;
; RV64-LABEL: f5:
; RV64:       # %bb.0:
; RV64-NEXT:    caddi cgp, cgp, 16
; RV64-NEXT:    sc cra, -16(cgp)
; RV64-NEXT:    caddi csp, csp, -16
; RV64-NEXT:    sc cra, 0(csp) # 16-byte Folded Spill
; RV64-NEXT:    call bar
; RV64-NEXT:    lc cra, 0(csp) # 16-byte Folded Reload
; RV64-NEXT:    caddi csp, csp, 16
; RV64-NEXT:    lc cra, -16(cgp)
; RV64-NEXT:    caddi cgp, cgp, -16
; RV64-NEXT:    ret
  %res = call i32 @bar()
  %res1 = add i32 %res, 1
  ret i32 %res
}
