// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %cheri_cc1 -emit-llvm %s -o - -verify | FileCheck %s
// RUN: %cheri_purecap_cc1 -emit-llvm %s -o - -verify | FileCheck %s -check-prefix PURECAP
// expected-no-diagnostics

// CHECK-LABEL: define {{[^@]+}}@assume_aligned_ptr
// CHECK-SAME: (ptr noundef [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[PTR]], ptr [[PTR_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[PTR_ADDR]], align 8
// CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[TMP0]], i64 4) ]
// CHECK-NEXT:    ret ptr [[TMP0]]
//
// PURECAP-LABEL: define {{[^@]+}}@assume_aligned_ptr
// PURECAP-SAME: (ptr addrspace(200) noundef [[PTR:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[PTR]], ptr addrspace(200) [[PTR_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[PTR_ADDR]], align 16
// PURECAP-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr addrspace(200) [[TMP0]], i64 4) ]
// PURECAP-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
int* assume_aligned_ptr(void* ptr) {
  return __builtin_assume_aligned(ptr, 4);
}

// CHECK-LABEL: define {{[^@]+}}@assume_aligned_cap
// CHECK-SAME: (ptr addrspace(200) noundef [[PTR:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr addrspace(200), align 16
// CHECK-NEXT:    store ptr addrspace(200) [[PTR]], ptr [[PTR_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr [[PTR_ADDR]], align 16
// CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr addrspace(200) [[TMP0]], i64 4) ]
// CHECK-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
// PURECAP-LABEL: define {{[^@]+}}@assume_aligned_cap
// PURECAP-SAME: (ptr addrspace(200) noundef [[PTR:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[PTR_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[PTR]], ptr addrspace(200) [[PTR_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[PTR_ADDR]], align 16
// PURECAP-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr addrspace(200) [[TMP0]], i64 4) ]
// PURECAP-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
int* __capability assume_aligned_cap(void* __capability ptr) {
  return __builtin_assume_aligned(ptr, 4);
}
