// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %riscv32_cheri_purecap_cc1 -o - -emit-llvm %s \
// RUN:   | FileCheck %s --check-prefix=CHECK32
// RUN: %riscv64_cheri_purecap_cc1 -o - -emit-llvm %s \
// RUN:   | FileCheck %s --check-prefix=CHECK64

/// Verify that __builtin_bit_cast does not require both types to be consistent
/// with respect to whether each is a capability, since its whole purpose is to
/// arbitrarily reinterpret the object representation.

typedef struct {
  void *p;
} wrap;

typedef struct {
  __PTRADDR_TYPE__ a[sizeof(void *) / sizeof(__PTRADDR_TYPE__)];
} words;

// CHECK32-LABEL: define dso_local %struct.wrap @ptr2wrap
// CHECK32-SAME: (ptr addrspace(200) noundef [[SRC:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK32-NEXT:  entry:
// CHECK32-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_WRAP:%.*]], align 8, addrspace(200)
// CHECK32-NEXT:    [[SRC_ADDR:%.*]] = alloca ptr addrspace(200), align 8, addrspace(200)
// CHECK32-NEXT:    store ptr addrspace(200) [[SRC]], ptr addrspace(200) [[SRC_ADDR]], align 8
// CHECK32-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) align 8 [[RETVAL]], ptr addrspace(200) align 8 [[SRC_ADDR]], i32 8, i1 false)
// CHECK32-NEXT:    [[TMP0:%.*]] = load [[STRUCT_WRAP]], ptr addrspace(200) [[RETVAL]], align 8
// CHECK32-NEXT:    ret [[STRUCT_WRAP]] [[TMP0]]
//
// CHECK64-LABEL: define dso_local %struct.wrap @ptr2wrap
// CHECK64-SAME: (ptr addrspace(200) noundef [[SRC:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK64-NEXT:  entry:
// CHECK64-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_WRAP:%.*]], align 16, addrspace(200)
// CHECK64-NEXT:    [[SRC_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK64-NEXT:    store ptr addrspace(200) [[SRC]], ptr addrspace(200) [[SRC_ADDR]], align 16
// CHECK64-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 [[RETVAL]], ptr addrspace(200) align 16 [[SRC_ADDR]], i64 16, i1 false)
// CHECK64-NEXT:    [[TMP0:%.*]] = load [[STRUCT_WRAP]], ptr addrspace(200) [[RETVAL]], align 16
// CHECK64-NEXT:    ret [[STRUCT_WRAP]] [[TMP0]]
//
wrap ptr2wrap(void *src) {
  return __builtin_bit_cast(wrap, src);
}

// CHECK32-LABEL: define dso_local ptr addrspace(200) @wrap2ptr
// CHECK32-SAME: (ptr addrspace(200) [[SRC_COERCE:%.*]]) addrspace(200) #[[ATTR0]] {
// CHECK32-NEXT:  entry:
// CHECK32-NEXT:    [[SRC:%.*]] = alloca [[STRUCT_WRAP:%.*]], align 8, addrspace(200)
// CHECK32-NEXT:    [[COERCE_DIVE:%.*]] = getelementptr inbounds [[STRUCT_WRAP]], ptr addrspace(200) [[SRC]], i32 0, i32 0
// CHECK32-NEXT:    store ptr addrspace(200) [[SRC_COERCE]], ptr addrspace(200) [[COERCE_DIVE]], align 8
// CHECK32-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[SRC]], align 8
// CHECK32-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
// CHECK64-LABEL: define dso_local ptr addrspace(200) @wrap2ptr
// CHECK64-SAME: (ptr addrspace(200) [[SRC_COERCE:%.*]]) addrspace(200) #[[ATTR0]] {
// CHECK64-NEXT:  entry:
// CHECK64-NEXT:    [[SRC:%.*]] = alloca [[STRUCT_WRAP:%.*]], align 16, addrspace(200)
// CHECK64-NEXT:    [[COERCE_DIVE:%.*]] = getelementptr inbounds [[STRUCT_WRAP]], ptr addrspace(200) [[SRC]], i32 0, i32 0
// CHECK64-NEXT:    store ptr addrspace(200) [[SRC_COERCE]], ptr addrspace(200) [[COERCE_DIVE]], align 16
// CHECK64-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[SRC]], align 16
// CHECK64-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
void *wrap2ptr(wrap src) {
  return __builtin_bit_cast(void *, src);
}

// CHECK32-LABEL: define dso_local [2 x i32] @ptr2words
// CHECK32-SAME: (ptr addrspace(200) noundef [[SRC:%.*]]) addrspace(200) #[[ATTR0]] {
// CHECK32-NEXT:  entry:
// CHECK32-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_WORDS:%.*]], align 4, addrspace(200)
// CHECK32-NEXT:    [[SRC_ADDR:%.*]] = alloca ptr addrspace(200), align 8, addrspace(200)
// CHECK32-NEXT:    store ptr addrspace(200) [[SRC]], ptr addrspace(200) [[SRC_ADDR]], align 8
// CHECK32-NEXT:    call void @llvm.memcpy.p200.p200.i32(ptr addrspace(200) align 4 [[RETVAL]], ptr addrspace(200) align 8 [[SRC_ADDR]], i32 8, i1 false)
// CHECK32-NEXT:    [[COERCE_DIVE:%.*]] = getelementptr inbounds [[STRUCT_WORDS]], ptr addrspace(200) [[RETVAL]], i32 0, i32 0
// CHECK32-NEXT:    [[TMP0:%.*]] = load [2 x i32], ptr addrspace(200) [[COERCE_DIVE]], align 4
// CHECK32-NEXT:    ret [2 x i32] [[TMP0]]
//
// CHECK64-LABEL: define dso_local [2 x i64] @ptr2words
// CHECK64-SAME: (ptr addrspace(200) noundef [[SRC:%.*]]) addrspace(200) #[[ATTR0]] {
// CHECK64-NEXT:  entry:
// CHECK64-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_WORDS:%.*]], align 8, addrspace(200)
// CHECK64-NEXT:    [[SRC_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK64-NEXT:    store ptr addrspace(200) [[SRC]], ptr addrspace(200) [[SRC_ADDR]], align 16
// CHECK64-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 8 [[RETVAL]], ptr addrspace(200) align 16 [[SRC_ADDR]], i64 16, i1 false)
// CHECK64-NEXT:    [[COERCE_DIVE:%.*]] = getelementptr inbounds [[STRUCT_WORDS]], ptr addrspace(200) [[RETVAL]], i32 0, i32 0
// CHECK64-NEXT:    [[TMP0:%.*]] = load [2 x i64], ptr addrspace(200) [[COERCE_DIVE]], align 8
// CHECK64-NEXT:    ret [2 x i64] [[TMP0]]
//
words ptr2words(void *src) {
  return __builtin_bit_cast(words, src);
}

// CHECK32-LABEL: define dso_local ptr addrspace(200) @words2ptr
// CHECK32-SAME: ([2 x i32] [[SRC_COERCE:%.*]]) addrspace(200) #[[ATTR0]] {
// CHECK32-NEXT:  entry:
// CHECK32-NEXT:    [[SRC:%.*]] = alloca [[STRUCT_WORDS:%.*]], align 4, addrspace(200)
// CHECK32-NEXT:    [[COERCE_DIVE:%.*]] = getelementptr inbounds [[STRUCT_WORDS]], ptr addrspace(200) [[SRC]], i32 0, i32 0
// CHECK32-NEXT:    store [2 x i32] [[SRC_COERCE]], ptr addrspace(200) [[COERCE_DIVE]], align 4
// CHECK32-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[SRC]], align 4
// CHECK32-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
// CHECK64-LABEL: define dso_local ptr addrspace(200) @words2ptr
// CHECK64-SAME: ([2 x i64] [[SRC_COERCE:%.*]]) addrspace(200) #[[ATTR0]] {
// CHECK64-NEXT:  entry:
// CHECK64-NEXT:    [[SRC:%.*]] = alloca [[STRUCT_WORDS:%.*]], align 8, addrspace(200)
// CHECK64-NEXT:    [[COERCE_DIVE:%.*]] = getelementptr inbounds [[STRUCT_WORDS]], ptr addrspace(200) [[SRC]], i32 0, i32 0
// CHECK64-NEXT:    store [2 x i64] [[SRC_COERCE]], ptr addrspace(200) [[COERCE_DIVE]], align 8
// CHECK64-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[SRC]], align 8
// CHECK64-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
void *words2ptr(words src) {
  return __builtin_bit_cast(void *, src);
}
