// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %cheri_purecap_cc1 -Wno-tautological-compare -o - -O0 -emit-llvm %s
// RUN: %cheri_purecap_cc1 -o - -O0 -emit-llvm %s | FileCheck %s -check-prefix PURECAP
// RUN: %cheri_cc1 -o - -O0 -emit-llvm %s | FileCheck %s -check-prefix N64

extern int test_ptr(char *c);
// PURECAP-LABEL: define {{[^@]+}}@test_array
// PURECAP-SAME: () addrspace(200) #[[ATTR0:[0-9]+]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[BUF:%.*]] = alloca [1024 x i8], align 1, addrspace(200)
// PURECAP-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [1024 x i8], ptr addrspace(200) [[BUF]], i64 0, i64 0
// PURECAP-NEXT:    [[PTRADDR:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[ARRAYDECAY]])
// PURECAP-NEXT:    [[OVER_BOUNDARY:%.*]] = add i64 [[PTRADDR]], 15
// PURECAP-NEXT:    [[ALIGNED_RESULT:%.*]] = and i64 [[OVER_BOUNDARY]], -16
// PURECAP-NEXT:    [[ALIGNED_CAP:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[ARRAYDECAY]], i64 [[ALIGNED_RESULT]])
// PURECAP-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr addrspace(200) [[ALIGNED_CAP]], i64 16) ]
// PURECAP-NEXT:    [[CALL:%.*]] = call signext i32 @test_ptr(ptr addrspace(200) noundef [[ALIGNED_CAP]])
// PURECAP-NEXT:    ret i32 [[CALL]]
//
// N64-LABEL: define {{[^@]+}}@test_array
// N64-SAME: () #[[ATTR0:[0-9]+]] {
// N64-NEXT:  entry:
// N64-NEXT:    [[BUF:%.*]] = alloca [1024 x i8], align 1
// N64-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [1024 x i8], ptr [[BUF]], i64 0, i64 0
// N64-NEXT:    [[OVER_BOUNDARY:%.*]] = getelementptr inbounds i8, ptr [[ARRAYDECAY]], i64 15
// N64-NEXT:    [[ALIGNED_RESULT:%.*]] = call ptr @llvm.ptrmask.p0.i64(ptr [[OVER_BOUNDARY]], i64 -16)
// N64-NEXT:    [[CALL:%.*]] = call signext i32 @test_ptr(ptr noundef [[ALIGNED_RESULT]])
// N64-NEXT:    ret i32 [[CALL]]
//
int test_array(void) {
  // Array to pointer decay should work:
  char buf[1024];
  return test_ptr(__builtin_align_up(buf, 16));
}
