// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// This used to crash since we were generating an i64 for __builtin_align_up()
// constant expressions:
// https://github.com/CTSRD-CHERI/llvm-project/issues/412
// RUN: %cheri_purecap_cc1 -o - -emit-llvm %s | FileCheck %s

// CHECK-LABEL: define {{[^@]+}}@long_up
// CHECK-SAME: () addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i64 16
//
long long_up() { return __builtin_align_up((long)1, 16); }
// CHECK-LABEL: define {{[^@]+}}@long_down
// CHECK-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i64 0
//
long long_down() { return __builtin_align_down((long)1, 16); }
// CHECK-LABEL: define {{[^@]+}}@cap_up
// CHECK-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 16)
//
__uintcap_t cap_up() { return __builtin_align_up((__uintcap_t)1, 16); }
// CHECK-LABEL: define {{[^@]+}}@cap_down
// CHECK-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret ptr addrspace(200) null
//
__uintcap_t cap_down() { return __builtin_align_down((__uintcap_t)1, 16); }

// CHECK-LABEL: define {{[^@]+}}@a
// CHECK-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr addrspace(200) null, align 4
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int a() { return ((int *)0)[__builtin_align_up((long)0, 16) / 1]; }
// The original test case produced by creduce:
// CHECK-LABEL: define {{[^@]+}}@b
// CHECK-SAME: () addrspace(200) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) null)
// CHECK-NEXT:    [[TMP1:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 1))
// CHECK-NEXT:    [[DIV:%.*]] = udiv i64 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[TMP2:%.*]] = getelementptr i8, ptr addrspace(200) null, i64 [[DIV]]
// CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[TMP2]])
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr addrspace(200) null, i64 [[TMP3]]
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr addrspace(200) [[ARRAYIDX]], align 4
// CHECK-NEXT:    ret i32 [[TMP4]]
//
int b() { return ((int *)0)[__builtin_align_up((__uintcap_t)0, 16) / 1]; }
