// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %riscv64_cheri_cc1 -opaque-pointers -emit-llvm -o - %s | FileCheck %s -check-prefixes HYBRID
// RUN: %riscv64_cheri_purecap_cc1 -opaque-pointers -emit-llvm -o - %s | FileCheck %s -check-prefixes PURECAP

// HYBRID-LABEL: @frameaddr(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[B:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[TMP0:%.*]] = call ptr @llvm.frameaddress.p0(i32 0)
// HYBRID-NEXT:    store ptr [[TMP0]], ptr [[B]], align 8
// HYBRID-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B]], align 8
// HYBRID-NEXT:    ret ptr [[TMP1]]
//
// PURECAP-LABEL: @frameaddr(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[B:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.frameaddress.p200(i32 0)
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[B]], align 16
// PURECAP-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[B]], align 16
// PURECAP-NEXT:    ret ptr addrspace(200) [[TMP1]]
//
void *frameaddr(void) {
  // https://github.com/CTSRD-CHERI/clang/issues/200
  void *b = __builtin_frame_address(0);
  return b;
}

// HYBRID-LABEL: @retaddr(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[B:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[TMP0:%.*]] = call ptr @llvm.returnaddress.p0(i32 0)
// HYBRID-NEXT:    store ptr [[TMP0]], ptr [[B]], align 8
// HYBRID-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B]], align 8
// HYBRID-NEXT:    ret ptr [[TMP1]]
//
// PURECAP-LABEL: @retaddr(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[B:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.returnaddress.p200(i32 0)
// PURECAP-NEXT:    store ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[B]], align 16
// PURECAP-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[B]], align 16
// PURECAP-NEXT:    ret ptr addrspace(200) [[TMP1]]
//
void *retaddr(void) {
  // Also check that we do the right thing for __builtin_return_address()
  void *b = __builtin_return_address(0);
  return b;
}
