// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri128_cc1 -o - -O0 -emit-llvm %s | FileCheck %s --check-prefix=HYBRID
// RUN: %cheri128_purecap_cc1 -o - -O0 -emit-llvm %s | FileCheck %s --check-prefix=PURECAP128

char *start, *end;

// HYBRID-LABEL: @clear_cache(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = load ptr, ptr @start, align 8
// HYBRID-NEXT:    [[TMP1:%.*]] = load ptr, ptr @end, align 8
// HYBRID-NEXT:    call void @llvm.clear_cache.p0(ptr [[TMP0]], ptr [[TMP1]])
// HYBRID-NEXT:    ret void
//
// PURECAP128-LABEL: @clear_cache(
// PURECAP128-NEXT:  entry:
// PURECAP128-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) @start, align 16
// PURECAP128-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) @end, align 16
// PURECAP128-NEXT:    call void @llvm.clear_cache.p200(ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[TMP1]])
// PURECAP128-NEXT:    ret void
//
void clear_cache(void) {
	__builtin___clear_cache(start, end);
}
