// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %cheri_purecap_cc1 -emit-llvm %s -o - -verify | FileCheck %s -check-prefix PURECAP
// expected-no-diagnostics
// RUN: %cheri_purecap_cc1 -emit-llvm -fsanitize=alignment %s -o - -verify | FileCheck %s -check-prefix PURECAP-ALIGN
// expected-no-diagnostics

// PURECAP-LABEL: define dso_local ptr addrspace(200) @foo
// PURECAP-SAME: (ptr addrspace(200) noundef [[CAP:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[CAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[CAP]], ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-NEXT:    [[PTRADDR:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[TMP0]])
// PURECAP-NEXT:    [[OVER_BOUNDARY:%.*]] = add i64 [[PTRADDR]], 15
// PURECAP-NEXT:    [[ALIGNED_INTPTR:%.*]] = and i64 [[OVER_BOUNDARY]], -16
// PURECAP-NEXT:    [[DIFF:%.*]] = sub i64 [[ALIGNED_INTPTR]], [[PTRADDR]]
// PURECAP-NEXT:    [[ALIGNED_RESULT:%.*]] = getelementptr i8, ptr addrspace(200) [[TMP0]], i64 [[DIFF]]
// PURECAP-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr addrspace(200) [[ALIGNED_RESULT]], i64 16) ]
// PURECAP-NEXT:    ret ptr addrspace(200) [[ALIGNED_RESULT]]
//
// PURECAP-ALIGN-LABEL: define dso_local ptr addrspace(200) @foo
// PURECAP-ALIGN-SAME: (ptr addrspace(200) noundef [[CAP:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// PURECAP-ALIGN-NEXT:  entry:
// PURECAP-ALIGN-NEXT:    [[CAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-ALIGN-NEXT:    store ptr addrspace(200) [[CAP]], ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-ALIGN-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-ALIGN-NEXT:    [[PTRADDR:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[TMP0]])
// PURECAP-ALIGN-NEXT:    [[OVER_BOUNDARY:%.*]] = add i64 [[PTRADDR]], 15
// PURECAP-ALIGN-NEXT:    [[ALIGNED_INTPTR:%.*]] = and i64 [[OVER_BOUNDARY]], -16
// PURECAP-ALIGN-NEXT:    [[DIFF:%.*]] = sub i64 [[ALIGNED_INTPTR]], [[PTRADDR]]
// PURECAP-ALIGN-NEXT:    [[ALIGNED_RESULT:%.*]] = getelementptr i8, ptr addrspace(200) [[TMP0]], i64 [[DIFF]]
// PURECAP-ALIGN-NEXT:    [[PTRINT:%.*]] = ptrtoint ptr addrspace(200) [[ALIGNED_RESULT]] to i64
// PURECAP-ALIGN-NEXT:    [[MASKEDPTR:%.*]] = and i64 [[PTRINT]], 15
// PURECAP-ALIGN-NEXT:    [[MASKCOND:%.*]] = icmp eq i64 [[MASKEDPTR]], 0
// PURECAP-ALIGN-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(200) [[ALIGNED_RESULT]] to i64, !nosanitize !2
// PURECAP-ALIGN-NEXT:    br i1 [[MASKCOND]], label [[CONT:%.*]], label [[HANDLER_ALIGNMENT_ASSUMPTION:%.*]], !prof [[PROF3:![0-9]+]], !nosanitize !2
// PURECAP-ALIGN:       handler.alignment_assumption:
// PURECAP-ALIGN-NEXT:    call void @__ubsan_handle_alignment_assumption_abort(ptr addrspace(200) @[[GLOB1:[0-9]+]], i64 [[TMP1]], i64 16, i64 0) #[[ATTR4:[0-9]+]], !nosanitize !2
// PURECAP-ALIGN-NEXT:    unreachable, !nosanitize !2
// PURECAP-ALIGN:       cont:
// PURECAP-ALIGN-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr addrspace(200) [[ALIGNED_RESULT]], i64 16) ]
// PURECAP-ALIGN-NEXT:    ret ptr addrspace(200) [[ALIGNED_RESULT]]
//
void *foo(__UINTPTR_TYPE__ cap) {
  return (void *)__builtin_align_up(cap, 16);
}

// PURECAP-LABEL: define dso_local ptr addrspace(200) @bar
// PURECAP-SAME: (ptr addrspace(200) noundef [[CAP:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[CAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-NEXT:    store ptr addrspace(200) [[CAP]], ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-NEXT:    [[PTRADDR:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[TMP0]])
// PURECAP-NEXT:    [[ALIGNED_INTPTR:%.*]] = and i64 [[PTRADDR]], -16
// PURECAP-NEXT:    [[DIFF:%.*]] = sub i64 [[ALIGNED_INTPTR]], [[PTRADDR]]
// PURECAP-NEXT:    [[ALIGNED_RESULT:%.*]] = getelementptr i8, ptr addrspace(200) [[TMP0]], i64 [[DIFF]]
// PURECAP-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr addrspace(200) [[ALIGNED_RESULT]], i64 16) ]
// PURECAP-NEXT:    ret ptr addrspace(200) [[ALIGNED_RESULT]]
//
// PURECAP-ALIGN-LABEL: define dso_local ptr addrspace(200) @bar
// PURECAP-ALIGN-SAME: (ptr addrspace(200) noundef [[CAP:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-ALIGN-NEXT:  entry:
// PURECAP-ALIGN-NEXT:    [[CAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// PURECAP-ALIGN-NEXT:    store ptr addrspace(200) [[CAP]], ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-ALIGN-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP_ADDR]], align 16
// PURECAP-ALIGN-NEXT:    [[PTRADDR:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[TMP0]])
// PURECAP-ALIGN-NEXT:    [[ALIGNED_INTPTR:%.*]] = and i64 [[PTRADDR]], -16
// PURECAP-ALIGN-NEXT:    [[DIFF:%.*]] = sub i64 [[ALIGNED_INTPTR]], [[PTRADDR]]
// PURECAP-ALIGN-NEXT:    [[ALIGNED_RESULT:%.*]] = getelementptr i8, ptr addrspace(200) [[TMP0]], i64 [[DIFF]]
// PURECAP-ALIGN-NEXT:    [[PTRINT:%.*]] = ptrtoint ptr addrspace(200) [[ALIGNED_RESULT]] to i64
// PURECAP-ALIGN-NEXT:    [[MASKEDPTR:%.*]] = and i64 [[PTRINT]], 15
// PURECAP-ALIGN-NEXT:    [[MASKCOND:%.*]] = icmp eq i64 [[MASKEDPTR]], 0
// PURECAP-ALIGN-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(200) [[ALIGNED_RESULT]] to i64, !nosanitize !2
// PURECAP-ALIGN-NEXT:    br i1 [[MASKCOND]], label [[CONT:%.*]], label [[HANDLER_ALIGNMENT_ASSUMPTION:%.*]], !prof [[PROF3]], !nosanitize !2
// PURECAP-ALIGN:       handler.alignment_assumption:
// PURECAP-ALIGN-NEXT:    call void @__ubsan_handle_alignment_assumption_abort(ptr addrspace(200) @[[GLOB2:[0-9]+]], i64 [[TMP1]], i64 16, i64 0) #[[ATTR4]], !nosanitize !2
// PURECAP-ALIGN-NEXT:    unreachable, !nosanitize !2
// PURECAP-ALIGN:       cont:
// PURECAP-ALIGN-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr addrspace(200) [[ALIGNED_RESULT]], i64 16) ]
// PURECAP-ALIGN-NEXT:    ret ptr addrspace(200) [[ALIGNED_RESULT]]
//
void *bar(__UINTPTR_TYPE__ cap) {
  return (void *)__builtin_align_down(cap, 16);
}

