// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_cc1 -disable-O0-optnone -emit-llvm %s -o - \
// RUN:   | opt -S -mem2reg | FileCheck %s

typedef __SIZE_TYPE__ size_t;

// CHECK-LABEL: @decay_incomplete(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    ret ptr addrspace(200) [[ADD_PTR]]
//
char * __capability decay_incomplete(char p[__capability]) {
  return p + 1;
}

// CHECK-LABEL: @member_incomplete(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    ret ptr addrspace(200) [[ARRAYIDX]]
//
char * __capability member_incomplete(char p[__capability]) {
  return &p[1];
}

// CHECK-LABEL: @sub_incomplete(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr addrspace(200) [[ARRAYIDX]], align 1
// CHECK-NEXT:    ret i8 [[TMP0]]
//
char sub_incomplete(char p[__capability]) {
  return p[1];
}

// CHECK-LABEL: @decay_constant(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    ret ptr addrspace(200) [[ADD_PTR]]
//
char * __capability decay_constant(char p[__capability 2]) {
  return p + 1;
}

// CHECK-LABEL: @member_constant(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    ret ptr addrspace(200) [[ARRAYIDX]]
//
char * __capability member_constant(char p[__capability 2]) {
  return &p[1];
}

// CHECK-LABEL: @sub_constant(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr addrspace(200) [[ARRAYIDX]], align 1
// CHECK-NEXT:    ret i8 [[TMP0]]
//
char sub_constant(char p[__capability 2]) {
  return p[1];
}

// CHECK-LABEL: @decay_constant_static(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    ret ptr addrspace(200) [[ADD_PTR]]
//
char * __capability decay_constant_static(char p[__capability static 2]) {
  return p + 1;
}

// CHECK-LABEL: @member_constant_static(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    ret ptr addrspace(200) [[ARRAYIDX]]
//
char * __capability member_constant_static(char p[__capability static 2]) {
  return &p[1];
}

// CHECK-LABEL: @sub_constant_static(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr addrspace(200) [[ARRAYIDX]], align 1
// CHECK-NEXT:    ret i8 [[TMP0]]
//
char sub_constant_static(char p[__capability static 2]) {
  return p[1];
}

// CHECK-LABEL: @decay_variable(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    ret ptr addrspace(200) [[ADD_PTR]]
//
char * __capability decay_variable(size_t n, char p[__capability n]) {
  return p + 1;
}

// CHECK-LABEL: @member_variable(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    ret ptr addrspace(200) [[ARRAYIDX]]
//
char * __capability member_variable(size_t n, char p[__capability n]) {
  return &p[1];
}

// CHECK-LABEL: @sub_variable(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[P:%.*]], i64 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr addrspace(200) [[ARRAYIDX]], align 1
// CHECK-NEXT:    ret i8 [[TMP0]]
//
char sub_variable(size_t n, char p[__capability n]) {
  return p[1];
}
