// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %cheri_purecap_cc1 -emit-llvm -o - %s -disable-llvm-optzns -O0 | FileCheck %s -check-prefix PCREL
// Test that Clang does not crash when the type of the called function
// differs from the arguments that are passed.
// Ideally this should be in the LLVM unit tests but it doesn't seem to be
// possible to create IR whereby the arguments passed differs from what is
// allowed as per the function prototype.

// PCREL-LABEL: define {{[^@]+}}@a
// PCREL-SAME: () addrspace(200) #[[ATTR0:[0-9]+]] {
// PCREL-NEXT:  entry:
// PCREL-NEXT:    call void @a(i32 noundef signext 3)
// PCREL-NEXT:    ret void
//
void a() {
  a(3);
}
