// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_cc1 -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: @main(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[P:%.*]] = alloca ptr addrspace(200), align 16
// CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr [[P]], align 16
// CHECK-NEXT:    [[CMP:%.*]] = icmp eq ptr addrspace(200) [[TMP0]], null
// CHECK-NEXT:    br i1 [[CMP]], label [[IF_THEN:%.*]], label [[IF_ELSE:%.*]]
// CHECK:       if.then:
// CHECK-NEXT:    br label [[IF_END3:%.*]]
// CHECK:       if.else:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr [[P]], align 16
// CHECK-NEXT:    [[CMP1:%.*]] = icmp eq ptr addrspace(200) null, [[TMP1]]
// CHECK-NEXT:    br i1 [[CMP1]], label [[IF_THEN2:%.*]], label [[IF_END:%.*]]
// CHECK:       if.then2:
// CHECK-NEXT:    br label [[IF_END]]
// CHECK:       if.end:
// CHECK-NEXT:    br label [[IF_END3]]
// CHECK:       if.end3:
// CHECK-NEXT:    ret i32 0
//
int main(void) {
  char * __capability p;
  if (p == (void * __capability)0) {
  }
  else if ((void * __capability)0 == p) {
  }
  return 0;
}
