// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %riscv32_cheri_purecap_cc1 -disable-O0-optnone %s -S -emit-llvm -o - | opt -passes=mem2reg -S -o - | FileCheck %s --check-prefix=RV32
// RUN: %riscv64_cheri_purecap_cc1 -disable-O0-optnone %s -S -emit-llvm -o - | opt -passes=mem2reg -S -o - | FileCheck %s --check-prefix=RV64

// RV32-LABEL: define dso_local i32 @ptr_to_int
// RV32-SAME: (ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// RV32-NEXT:  entry:
// RV32-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) asm "", "=C,0"(ptr addrspace(200) [[P]]) #[[ATTR1:[0-9]+]], !srcloc !4
// RV32-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(200) [[TMP0]] to i32
// RV32-NEXT:    ret i32 [[TMP1]]
//
// RV64-LABEL: define dso_local signext i32 @ptr_to_int
// RV64-SAME: (ptr addrspace(200) noundef [[P:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// RV64-NEXT:  entry:
// RV64-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) asm "", "=C,0"(ptr addrspace(200) [[P]]) #[[ATTR1:[0-9]+]], !srcloc !4
// RV64-NEXT:    [[TMP1:%.*]] = ptrtoint ptr addrspace(200) [[TMP0]] to i64
// RV64-NEXT:    [[TMP2:%.*]] = trunc i64 [[TMP1]] to i32
// RV64-NEXT:    ret i32 [[TMP2]]
//
int ptr_to_int(void *p) {
  int i;
  asm ("" : "=C"(i) : "0"(p));
  return i;
}
