// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_cc1 -emit-llvm -O0 %s -o - | FileCheck %s
// This previously crashed during code generation

typedef struct a { struct a * __capability b; } * c;
// CHECK-LABEL: @d(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[E:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[E]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr [[TMP0]], align 16
// CHECK-NEXT:    [[B:%.*]] = getelementptr inbounds [[STRUCT_A:%.*]], ptr addrspace(200) [[TMP1]], i32 0, i32 0
// CHECK-NEXT:    [[B_ASCAST:%.*]] = addrspacecast ptr addrspace(200) [[B]] to ptr
// CHECK-NEXT:    store ptr [[B_ASCAST]], ptr [[E]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[E]], align 8
// CHECK-NEXT:    ret ptr [[TMP2]]
//
c __capability * d(void) {
  c __capability *e;
  e = (__cheri_fromcap struct a * __capability *)&(*e)->b;
  return e;
}
