// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_purecap_cc1 -w -O2 -std=gnu99 -o - -emit-llvm %s | FileCheck %s -check-prefix PCREL

// https://github.com/CTSRD-CHERI/clang/issues/144

int a();
// unless we mark a as weak the compiler will optimize out the if (a) case since it assumed to be non-null
#pragma weak a
int d();
int e();
// PCREL-LABEL: @b(
// PCREL-NEXT:  entry:
// PCREL-NEXT:    br i1 icmp ne (ptr addrspace(200) @a, ptr addrspace(200) null), label [[IF_THEN:%.*]], label [[IF_END:%.*]]
// PCREL:       if.then:
// PCREL-NEXT:    [[CALL:%.*]] = tail call signext i32 @d() #[[ATTR2:[0-9]+]]
// PCREL-NEXT:    br label [[IF_END]]
// PCREL:       if.end:
// PCREL-NEXT:    br i1 icmp eq (ptr addrspace(200) @a, ptr addrspace(200) null), label [[CLEANUP:%.*]], label [[IF_END2:%.*]]
// PCREL:       if.end2:
// PCREL-NEXT:    [[CALL3:%.*]] = tail call signext i32 @e() #[[ATTR2]]
// PCREL-NEXT:    br label [[CLEANUP]]
// PCREL:       cleanup:
// PCREL-NEXT:    [[RETVAL_0:%.*]] = phi ptr addrspace(200) [ @a, [[IF_END2]] ], [ null, [[IF_END]] ]
// PCREL-NEXT:    ret ptr addrspace(200) [[RETVAL_0]]
//
int *b() {
  int *c;
  if (a)
    d();
  c = a;
  if (c == 0)
    return 0;
  e();
  return c;
}
