// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %cheri_cc1 -o - %s -emit-llvm | FileCheck %s
#define CHERI_CCALL(suffix, cls) \
	__attribute__((cheri_ccall))\
	__attribute__((cheri_method_suffix(suffix)))\
	__attribute__((cheri_method_class(cls)))

struct cheri_class
{
  void * __capability a;
  void * __capability b;
};

struct cheri_class def;
struct cheri_class other;


CHERI_CCALL("_cap", def)
__attribute__((pointer_interpretation_capabilities))
void *foo(void*, void*);

CHERI_CCALL("_cap", def)
void *baz(void*, void*);

// CHECK-LABEL: define {{[^@]+}}@bar
// CHECK-SAME: (ptr noundef [[A:%.*]], ptr noundef [[B:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr @__cheri_method.def.baz, align 8, !invariant.load !2
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr addrspace(200), ptr @def, align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr getelementptr inbounds ([[STRUCT_CHERI_CLASS:%.*]], ptr @def, i32 0, i32 1), align 16
// CHECK-NEXT:    [[CALL:%.*]] = call chericcallcc ptr @cheri_invoke(ptr addrspace(200) noundef [[TMP3]], ptr addrspace(200) noundef [[TMP4]], i64 noundef zeroext [[TMP2]], ptr noundef [[TMP0]], ptr noundef [[TMP1]])
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = addrspacecast ptr [[TMP5]] to ptr addrspace(200)
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = addrspacecast ptr [[TMP7]] to ptr addrspace(200)
// CHECK-NEXT:    [[TMP9:%.*]] = load i64, ptr @__cheri_method.def.foo, align 8, !invariant.load !2
// CHECK-NEXT:    [[TMP10:%.*]] = load ptr addrspace(200), ptr @def, align 16
// CHECK-NEXT:    [[TMP11:%.*]] = load ptr addrspace(200), ptr getelementptr inbounds ([[STRUCT_CHERI_CLASS]], ptr @def, i32 0, i32 1), align 16
// CHECK-NEXT:    [[CALL1:%.*]] = call chericcallcc ptr addrspace(200) @cheri_invoke(ptr addrspace(200) noundef [[TMP10]], ptr addrspace(200) noundef [[TMP11]], i64 noundef zeroext [[TMP9]], ptr addrspace(200) noundef [[TMP6]], ptr addrspace(200) noundef [[TMP8]])
// CHECK-NEXT:    [[CALL1_ASCAST:%.*]] = addrspacecast ptr addrspace(200) [[CALL1]] to ptr
// CHECK-NEXT:    ret ptr [[CALL1_ASCAST]]
//
void *bar(void *a, void *b)
{
	baz(a, b);
	return (__cheri_fromcap void*)foo((__cheri_tocap void * __capability)a, (__cheri_tocap void * __capability)b);
}

