// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_purecap_cc1 %s -O0 -msoft-float -emit-llvm -o - | FileCheck %s
// Ensure literals don't spontaneously switch address space during calls when
// using the pure capability ABI. A regression test for #5.

// CHECK-LABEL: @takes_string_ptr(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    store ptr addrspace(200) [[A:%.*]], ptr addrspace(200) [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[A_ADDR]], align 16
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[TMP0]], i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr addrspace(200) [[ARRAYIDX]], align 1
// CHECK-NEXT:    ret i8 [[TMP1]]
//
char takes_string_ptr(const char *a) {
    return a[0];
}

// CHECK-LABEL: @main(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4, addrspace(200)
// CHECK-NEXT:    store i32 0, ptr addrspace(200) [[RETVAL]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call signext i8 @takes_string_ptr(ptr addrspace(200) noundef @.str)
// CHECK-NEXT:    [[CONV:%.*]] = sext i8 [[CALL]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
int main(void) {
  return takes_string_ptr("hi");
}
