// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %cheri_cc1 %s "-target-abi" "purecap" -emit-llvm  -o - -O2 | FileCheck %s

extern void test(const char*);

// CHECK-LABEL: define {{[^@]+}}@foo
// CHECK-SAME: () local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    br label [[FOR_BODY:%.*]]
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    ret void
// CHECK:       for.body:
// CHECK-NEXT:    [[I_04:%.*]] = phi i64 [ 1, [[ENTRY:%.*]] ], [ [[INC:%.*]], [[FOR_BODY]] ]
// CHECK-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.stacksave.p200()
// CHECK-NEXT:    [[VLA:%.*]] = alloca i8, i64 [[I_04]], align 1, addrspace(200)
// CHECK-NEXT:    [[SUB:%.*]] = add nsw i64 [[I_04]], -1
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[VLA]], i64 [[SUB]]
// CHECK-NEXT:    store i8 0, ptr addrspace(200) [[ARRAYIDX]], align 1, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    call void @test(ptr addrspace(200) noundef nonnull [[VLA]]) #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    call void @llvm.stackrestore.p200(ptr addrspace(200) [[TMP0]])
// CHECK-NEXT:    [[INC]] = add nuw nsw i64 [[I_04]], 1
// CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INC]], 32
// CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP:%.*]], label [[FOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
//
void foo(void) {
  for (long i = 1; i < 32; i++) {
    char vla[i];
    vla[i - 1] = '\0';
    test(vla);
  }
}
