// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_cc1 -Wno-cheri-capability-misuse %s -disable-O0-optnone -emit-llvm -o - \
// RUN:   | opt -S -mem2reg | FileCheck %s -check-prefixes HYBRID
// RUN: %cheri_purecap_cc1 -Wno-cheri-capability-misuse %s -disable-O0-optnone -emit-llvm -o - \
// RUN:   | opt -S -mem2reg | FileCheck %s -check-prefixes PURECAP
// RUN: %cheri_cc1 -DWITH_CHERI_CASTS %s -disable-O0-optnone -emit-llvm -o - \
// RUN:   | opt -S -mem2reg | FileCheck %s -check-prefixes HYBRID
// RUN: %cheri_purecap_cc1 -DWITH_CHERI_CASTS %s -disable-O0-optnone -emit-llvm -o - \
// RUN:   | opt -S -mem2reg | FileCheck %s -check-prefixes PURECAP

extern void *global_ptr;
extern void * __capability global_cap;

#ifdef WITH_CHERI_CASTS
#define CHERI_TOCAP __cheri_tocap
#define CHERI_FROMCAP __cheri_fromcap
#else
#define CHERI_TOCAP
#define CHERI_FROMCAP
#endif

// HYBRID-LABEL: @c_cast_add_cap(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = load ptr, ptr @global_ptr, align 8
// HYBRID-NEXT:    [[TMP1:%.*]] = addrspacecast ptr [[TMP0]] to ptr addrspace(200)
// HYBRID-NEXT:    ret ptr addrspace(200) [[TMP1]]
//
// PURECAP-LABEL: @c_cast_add_cap(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) @global_ptr, align 16
// PURECAP-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
void * __capability c_cast_add_cap(void) {
  void * __capability ptr2cap = (CHERI_TOCAP void * __capability)global_ptr;
  return ptr2cap;
}

// HYBRID-LABEL: @c_cast_remove_cap(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr @global_cap, align 16
// HYBRID-NEXT:    [[TMP1:%.*]] = addrspacecast ptr addrspace(200) [[TMP0]] to ptr
// HYBRID-NEXT:    ret ptr [[TMP1]]
//
// PURECAP-LABEL: @c_cast_remove_cap(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) @global_cap, align 16
// PURECAP-NEXT:    ret ptr addrspace(200) [[TMP0]]
//
void *c_cast_remove_cap(void) {
  void *cap2ptr = (CHERI_FROMCAP void *)global_cap;
  return cap2ptr;
}
