// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_purecap_cc1 -O2 -o - -emit-llvm %s | FileCheck %s
// This code was hitting an assertion due to memcpy optimizations assuming address space zero
int memcmp(const void * __capability, const void * __capability, unsigned long);

struct foo { char a[8]; };

// CHECK-LABEL: @test(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[D:%.*]] = alloca [[STRUCT_FOO:%.*]], align 1, addrspace(200)
// CHECK-NEXT:    call void @llvm.lifetime.start.p200(i64 8, ptr addrspace(200) nonnull [[D]]) #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    [[BCMP:%.*]] = call i32 @bcmp(ptr addrspace(200) noundef nonnull dereferenceable(8) [[D]], ptr addrspace(200) noundef nonnull dereferenceable(8) @.str, i64 8)
// CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq i32 [[BCMP]], 0
// CHECK-NEXT:    [[DOT:%.*]] = zext i1 [[TOBOOL_NOT]] to i32
// CHECK-NEXT:    call void @llvm.lifetime.end.p200(i64 8, ptr addrspace(200) nonnull [[D]]) #[[ATTR4]]
// CHECK-NEXT:    ret i32 [[DOT]]
//
int test(void) {
  struct foo d;
  if (memcmp(d.a, "", sizeof(d)))
    return 0;
  return 1;
}


int a[];
int b;
// CHECK-LABEL: @test2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[LHSV:%.*]] = load i32, ptr addrspace(200) @a, align 4
// CHECK-NEXT:    [[RHSV:%.*]] = load i32, ptr addrspace(200) @b, align 4
// CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i32 [[LHSV]], [[RHSV]]
// CHECK-NEXT:    [[LNOT_EXT:%.*]] = zext i1 [[DOTNOT]] to i32
// CHECK-NEXT:    ret i32 [[LNOT_EXT]]
//
int test2(void) { return !memcmp(a, &b, sizeof b); }

