// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_cc1 %s -o - -emit-llvm | FileCheck %s

int cst(const __capability __cheri_input void *x);

// CHECK-LABEL: @callconst(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X:%.*]] = alloca [[STRUCT_X:%.*]], align 4
// CHECK-NEXT:    [[Y:%.*]] = alloca ptr addrspace(200), align 16
// CHECK-NEXT:    [[X_ASCAST:%.*]] = addrspacecast ptr [[X]] to ptr addrspace(200)
// CHECK-NEXT:    store ptr addrspace(200) [[X_ASCAST]], ptr [[Y]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr [[Y]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[TMP0]], i64 65495)
// CHECK-NEXT:    [[CALL:%.*]] = call signext i32 @cst(ptr addrspace(200) noundef [[TMP1]])
// CHECK-NEXT:    ret i32 0
//
int callconst(void)
{
  struct x { int a,b,c; } x;
  __capability struct x *y = (__capability struct x*)&x;
  // Make sure we remove the write permissions from the capability
  cst(y);
  return 0;
}

