// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_purecap_cc1 -o - -O0 -emit-llvm %s | %cheri_FileCheck %s
// RUN: %cheri_cc1 -o - -O0 -emit-llvm %s | %cheri_FileCheck %s -check-prefix=HYBRID
// https://github.com/CTSRD-CHERI/clang/issues/178
struct a {
  void *__capability ptr;
};
// CHECK-LABEL: @c(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[FIRST:%.*]] = alloca [[STRUCT_A:%.*]], align 16, addrspace(200)
// CHECK-NEXT:    [[SECOND:%.*]] = alloca [[STRUCT_A]], align 16, addrspace(200)
// CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds [[STRUCT_A]], ptr addrspace(200) [[FIRST]], i32 0, i32 0
// CHECK-NEXT:    store ptr addrspace(200) [[SECOND]], ptr addrspace(200) [[PTR]], align 16
// CHECK-NEXT:    ret void
//
// HYBRID-LABEL: @c(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[FIRST:%.*]] = alloca [[STRUCT_A:%.*]], align 16
// HYBRID-NEXT:    [[SECOND:%.*]] = alloca [[STRUCT_A]], align 16
// HYBRID-NEXT:    [[SECOND_ASCAST:%.*]] = addrspacecast ptr [[SECOND]] to ptr addrspace(200)
// HYBRID-NEXT:    [[PTR:%.*]] = getelementptr inbounds [[STRUCT_A]], ptr [[FIRST]], i32 0, i32 0
// HYBRID-NEXT:    store ptr addrspace(200) [[SECOND_ASCAST]], ptr [[PTR]], align 16
// HYBRID-NEXT:    ret void
//
void c(void) {
  struct a first;
  struct a second;
  first.ptr = (__cheri_tocap void *__capability) & second;
}

struct foo;

// CHECK-LABEL: @test(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[FOOPTR_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    [[FOOCAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    [[PTR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    [[CAP:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    store ptr addrspace(200) [[FOOPTR:%.*]], ptr addrspace(200) [[FOOPTR_ADDR]], align 16
// CHECK-NEXT:    store ptr addrspace(200) [[FOOCAP:%.*]], ptr addrspace(200) [[FOOCAP_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[FOOCAP_ADDR]], align 16
// CHECK-NEXT:    store ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[PTR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[FOOPTR_ADDR]], align 16
// CHECK-NEXT:    store ptr addrspace(200) [[TMP1]], ptr addrspace(200) [[CAP]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[PTR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr addrspace(200) [[TMP2]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP]], align 16
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr addrspace(200) [[TMP4]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP3]], [[TMP5]]
// CHECK-NEXT:    ret i32 [[ADD]]
//
// HYBRID-LABEL: @test(
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[FOOPTR_ADDR:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[FOOCAP_ADDR:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    [[PTR:%.*]] = alloca ptr, align 8
// HYBRID-NEXT:    [[CAP:%.*]] = alloca ptr addrspace(200), align 16
// HYBRID-NEXT:    store ptr [[FOOPTR:%.*]], ptr [[FOOPTR_ADDR]], align 8
// HYBRID-NEXT:    store ptr addrspace(200) [[FOOCAP:%.*]], ptr [[FOOCAP_ADDR]], align 16
// HYBRID-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr [[FOOCAP_ADDR]], align 16
// HYBRID-NEXT:    [[TMP1:%.*]] = addrspacecast ptr addrspace(200) [[TMP0]] to ptr
// HYBRID-NEXT:    store ptr [[TMP1]], ptr [[PTR]], align 8
// HYBRID-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[FOOPTR_ADDR]], align 8
// HYBRID-NEXT:    [[TMP3:%.*]] = addrspacecast ptr [[TMP2]] to ptr addrspace(200)
// HYBRID-NEXT:    store ptr addrspace(200) [[TMP3]], ptr [[CAP]], align 16
// HYBRID-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[PTR]], align 8
// HYBRID-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
// HYBRID-NEXT:    [[TMP6:%.*]] = load ptr addrspace(200), ptr [[CAP]], align 16
// HYBRID-NEXT:    [[TMP7:%.*]] = load i32, ptr addrspace(200) [[TMP6]], align 4
// HYBRID-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP5]], [[TMP7]]
// HYBRID-NEXT:    ret i32 [[ADD]]
//
int test(struct foo* fooptr, struct foo* __capability foocap) {
  int* ptr = (__cheri_fromcap void*)foocap;
  int* __capability cap = (__cheri_tocap void* __capability)fooptr;
  return *ptr + *cap;
}
