// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals --include-generated-funcs --global-value-regex ".+"
// RUN: %riscv64_cheri_cc1 -o - -emit-llvm -Wno-cheri-capability-misuse %s | FileCheck --check-prefix=HYBRID %s
// RUN: %riscv64_cheri_purecap_cc1 -o - -emit-llvm -Wno-cheri-capability-misuse %s | FileCheck --check-prefix=PURECAP %s

extern char x[];

/// These should all preserve provenance
__intcap s = (__intcap)x;
unsigned __intcap u = (unsigned __intcap)x;
__intcap u2s = (__intcap)(unsigned __intcap)x;
unsigned __intcap s2u = (unsigned __intcap)(__intcap)x;
void *__capability s2p = (void *__capability)(__intcap)x;
void *__capability u2p = (void *__capability)(unsigned __intcap)x;
void *__capability s2u2p = (void *__capability)(unsigned __intcap)(__intcap)x;
void *__capability u2s2p = (void *__capability)(__intcap)(unsigned __intcap)x;

/// These should all strip provenance
__intcap s2l2s = (__intcap)(long)(__intcap)x;
__intcap l2s = (__intcap)(long)x;
void *__capability s2l2s2p = (void *__capability)(__intcap)(long)(__intcap)x;

//.
// HYBRID: @x = external global [0 x i8], align 1
// HYBRID: @s = global i8 addrspace(200)* addrspacecast (i8* getelementptr inbounds ([0 x i8], [0 x i8]* @x, i32 0, i32 0) to i8 addrspace(200)*), align 16
// HYBRID: @u = global i8 addrspace(200)* addrspacecast (i8* getelementptr inbounds ([0 x i8], [0 x i8]* @x, i32 0, i32 0) to i8 addrspace(200)*), align 16
// HYBRID: @u2s = global i8 addrspace(200)* addrspacecast (i8* getelementptr inbounds ([0 x i8], [0 x i8]* @x, i32 0, i32 0) to i8 addrspace(200)*), align 16
// HYBRID: @s2u = global i8 addrspace(200)* addrspacecast (i8* getelementptr inbounds ([0 x i8], [0 x i8]* @x, i32 0, i32 0) to i8 addrspace(200)*), align 16
// HYBRID: @s2p = global i8 addrspace(200)* addrspacecast (i8* getelementptr inbounds ([0 x i8], [0 x i8]* @x, i32 0, i32 0) to i8 addrspace(200)*), align 16
// HYBRID: @u2p = global i8 addrspace(200)* addrspacecast (i8* getelementptr inbounds ([0 x i8], [0 x i8]* @x, i32 0, i32 0) to i8 addrspace(200)*), align 16
// HYBRID: @s2u2p = global i8 addrspace(200)* addrspacecast (i8* getelementptr inbounds ([0 x i8], [0 x i8]* @x, i32 0, i32 0) to i8 addrspace(200)*), align 16
// HYBRID: @u2s2p = global i8 addrspace(200)* addrspacecast (i8* getelementptr inbounds ([0 x i8], [0 x i8]* @x, i32 0, i32 0) to i8 addrspace(200)*), align 16
// HYBRID: @s2l2s = global i8 addrspace(200)* getelementptr (i8, i8 addrspace(200)* null, i64 ptrtoint ([0 x i8]* @x to i64)), align 16
// HYBRID: @l2s = global i8 addrspace(200)* getelementptr (i8, i8 addrspace(200)* null, i64 ptrtoint ([0 x i8]* @x to i64)), align 16
// HYBRID: @s2l2s2p = global i8 addrspace(200)* getelementptr (i8, i8 addrspace(200)* null, i64 ptrtoint ([0 x i8]* @x to i64)), align 16
//.
// PURECAP: @x = external addrspace(200) global [0 x i8], align 1
// PURECAP: @s = addrspace(200) global i8 addrspace(200)* getelementptr inbounds ([0 x i8], [0 x i8] addrspace(200)* @x, i32 0, i32 0), align 16
// PURECAP: @u = addrspace(200) global i8 addrspace(200)* getelementptr inbounds ([0 x i8], [0 x i8] addrspace(200)* @x, i32 0, i32 0), align 16
// PURECAP: @u2s = addrspace(200) global i8 addrspace(200)* getelementptr inbounds ([0 x i8], [0 x i8] addrspace(200)* @x, i32 0, i32 0), align 16
// PURECAP: @s2u = addrspace(200) global i8 addrspace(200)* getelementptr inbounds ([0 x i8], [0 x i8] addrspace(200)* @x, i32 0, i32 0), align 16
// PURECAP: @s2p = addrspace(200) global i8 addrspace(200)* getelementptr inbounds ([0 x i8], [0 x i8] addrspace(200)* @x, i32 0, i32 0), align 16
// PURECAP: @u2p = addrspace(200) global i8 addrspace(200)* getelementptr inbounds ([0 x i8], [0 x i8] addrspace(200)* @x, i32 0, i32 0), align 16
// PURECAP: @s2u2p = addrspace(200) global i8 addrspace(200)* getelementptr inbounds ([0 x i8], [0 x i8] addrspace(200)* @x, i32 0, i32 0), align 16
// PURECAP: @u2s2p = addrspace(200) global i8 addrspace(200)* getelementptr inbounds ([0 x i8], [0 x i8] addrspace(200)* @x, i32 0, i32 0), align 16
// PURECAP: @s2l2s = addrspace(200) global i8 addrspace(200)* getelementptr (i8, i8 addrspace(200)* null, i64 ptrtoint ([0 x i8] addrspace(200)* @x to i64)), align 16
// PURECAP: @l2s = addrspace(200) global i8 addrspace(200)* getelementptr (i8, i8 addrspace(200)* null, i64 ptrtoint ([0 x i8] addrspace(200)* @x to i64)), align 16
// PURECAP: @s2l2s2p = addrspace(200) global i8 addrspace(200)* getelementptr (i8, i8 addrspace(200)* null, i64 ptrtoint ([0 x i8] addrspace(200)* @x to i64)), align 16
//.
