// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
/// Check that we generate correct code when dealing with overloaded builtins
// RUN: %cheri_purecap_cc1 %s -emit-llvm -o - -disable-O0-optnone | opt -S -passes=mem2reg | FileCheck %s --check-prefixes=PURECAP
// RUN: %cheri_cc1 %s -emit-llvm -o - -disable-O0-optnone | opt -S -passes=mem2reg | FileCheck %s --check-prefixes=HYBRID

typedef __SIZE_TYPE__ size_t;
typedef _Bool bool;

#define call_overloaded_builtins(T, x, x2)                                     \
  size_t result1 = __builtin_cheri_address_get(x);                             \
  T result2 = __builtin_cheri_address_set(x, 1);                               \
  size_t result3 = __builtin_cheri_base_get(x);                                \
  T result4 = __builtin_cheri_bounds_set(x, 1);                                \
  T result5 = __builtin_cheri_bounds_set_exact(x, 1);                          \
  bool result6 = __builtin_cheri_equal_exact(x, x2);                           \
  T result7 = __builtin_cheri_flags_set(x, 1);                                 \
  size_t result8 = __builtin_cheri_flags_get(x);                               \
  size_t result9 = __builtin_cheri_length_get(x);                              \
  size_t result10 = __builtin_cheri_offset_get(x);                             \
  T result11 = __builtin_cheri_offset_increment(x, 1);                         \
  T result12 = __builtin_cheri_offset_set(x, 1);                               \
  T result13 = __builtin_cheri_perms_and(x, 1);                                \
  size_t result14 = __builtin_cheri_perms_get(x);                              \
  T result15 = __builtin_cheri_seal(x, x2);                                    \
  T result16 = __builtin_cheri_seal_entry(x);                                  \
  bool result17 = __builtin_cheri_sealed_get(x);                               \
  bool result18 = __builtin_cheri_subset_test(x, x2);                          \
  T result19 = __builtin_cheri_tag_clear(x);                                   \
  bool result20 = __builtin_cheri_tag_get(x);                                  \
  size_t result21 = __builtin_cheri_type_get(x);                               \
  T result22 = __builtin_cheri_unseal(x, x2);                                  \
  T result23 = __builtin_cheri_conditional_seal(x, x2);                        \
  T result24 = __builtin_cheri_cap_type_copy(x, x2);                           \
  void *__capability result25 = __builtin_cheri_cap_build(x, (__uintcap_t)x2); \
  size_t result26 = __builtin_cheri_high_get(x);                               \
  T result27 = __builtin_cheri_high_set(x, 1);                                 \
  __builtin_cheri_perms_check(x, 1);                                           \
  __builtin_cheri_type_check(x, x2);

// PURECAP-LABEL: define {{[^@]+}}@test_void_ptr
// PURECAP-SAME: (ptr addrspace(200) noundef [[ARG:%.*]], ptr addrspace(200) noundef [[ARG2:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// PURECAP-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[__BUILTIN_CHERI_OFFSET_INCREMENT:%.*]] = getelementptr i8, ptr addrspace(200) [[ARG]], i64 1
// PURECAP-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// PURECAP-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// PURECAP-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// PURECAP-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    ret void
//
// HYBRID-LABEL: define {{[^@]+}}@test_void_ptr
// HYBRID-SAME: (ptr addrspace(200) noundef [[ARG:%.*]], ptr addrspace(200) noundef [[ARG2:%.*]]) #[[ATTR0:[0-9]+]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// HYBRID-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[__BUILTIN_CHERI_OFFSET_INCREMENT:%.*]] = getelementptr i8, ptr addrspace(200) [[ARG]], i64 1
// HYBRID-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// HYBRID-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// HYBRID-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// HYBRID-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    ret void
//
void test_void_ptr(void *__capability arg, void *__capability arg2) {
  call_overloaded_builtins(void *__capability, arg, arg2);
}

// PURECAP-LABEL: define {{[^@]+}}@test_const_char_ptr
// PURECAP-SAME: (ptr addrspace(200) noundef [[ARG:%.*]], ptr addrspace(200) noundef [[ARG2:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// PURECAP-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[__BUILTIN_CHERI_OFFSET_INCREMENT:%.*]] = getelementptr i8, ptr addrspace(200) [[ARG]], i64 1
// PURECAP-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// PURECAP-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// PURECAP-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// PURECAP-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    ret void
//
// HYBRID-LABEL: define {{[^@]+}}@test_const_char_ptr
// HYBRID-SAME: (ptr addrspace(200) noundef [[ARG:%.*]], ptr addrspace(200) noundef [[ARG2:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// HYBRID-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[__BUILTIN_CHERI_OFFSET_INCREMENT:%.*]] = getelementptr i8, ptr addrspace(200) [[ARG]], i64 1
// HYBRID-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// HYBRID-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// HYBRID-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// HYBRID-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    ret void
//
void test_const_char_ptr(const char *__capability arg, const char *__capability arg2) {
  call_overloaded_builtins(const char *__capability, arg, arg2);
}

// PURECAP-LABEL: define {{[^@]+}}@test_long_ptr
// PURECAP-SAME: (ptr addrspace(200) noundef [[ARG:%.*]], ptr addrspace(200) noundef [[ARG2:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// PURECAP-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[__BUILTIN_CHERI_OFFSET_INCREMENT:%.*]] = getelementptr i8, ptr addrspace(200) [[ARG]], i64 1
// PURECAP-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// PURECAP-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// PURECAP-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// PURECAP-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    ret void
//
// HYBRID-LABEL: define {{[^@]+}}@test_long_ptr
// HYBRID-SAME: (ptr addrspace(200) noundef [[ARG:%.*]], ptr addrspace(200) noundef [[ARG2:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// HYBRID-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[__BUILTIN_CHERI_OFFSET_INCREMENT:%.*]] = getelementptr i8, ptr addrspace(200) [[ARG]], i64 1
// HYBRID-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// HYBRID-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// HYBRID-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// HYBRID-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    ret void
//
void test_long_ptr(long *__capability arg, long *__capability arg2) {
  call_overloaded_builtins(long *__capability, arg, arg2);
}

// PURECAP-LABEL: define {{[^@]+}}@test_uintcap_t
// PURECAP-SAME: (ptr addrspace(200) noundef [[ARG:%.*]], ptr addrspace(200) noundef [[ARG2:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// PURECAP-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[__BUILTIN_CHERI_OFFSET_INCREMENT:%.*]] = getelementptr i8, ptr addrspace(200) [[ARG]], i64 1
// PURECAP-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// PURECAP-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// PURECAP-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// PURECAP-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) [[ARG]])
// PURECAP-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) [[ARG]], i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// PURECAP-NEXT:    ret void
//
// HYBRID-LABEL: define {{[^@]+}}@test_uintcap_t
// HYBRID-SAME: (ptr addrspace(200) noundef [[ARG:%.*]], ptr addrspace(200) noundef [[ARG2:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// HYBRID-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[__BUILTIN_CHERI_OFFSET_INCREMENT:%.*]] = getelementptr i8, ptr addrspace(200) [[ARG]], i64 1
// HYBRID-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// HYBRID-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// HYBRID-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// HYBRID-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) [[ARG]])
// HYBRID-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) [[ARG]], i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) [[ARG]], ptr addrspace(200) [[ARG2]])
// HYBRID-NEXT:    ret void
//
void test_uintcap_t(__uintcap_t arg, __uintcap_t arg2) {
  call_overloaded_builtins(__uintcap_t, arg, arg2);
}

// PURECAP-LABEL: define {{[^@]+}}@test_null_constant
// PURECAP-SAME: (ptr addrspace(200) noundef [[ARG:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP1:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP2:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    [[TMP4:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP4]] to i8
// PURECAP-NEXT:    [[TMP5:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    [[TMP6:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP9:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    [[TMP10:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP12:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP13:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) null)
// PURECAP-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP13]] to i8
// PURECAP-NEXT:    [[TMP14:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP14]] to i8
// PURECAP-NEXT:    [[TMP15:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) null)
// PURECAP-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP16]] to i8
// PURECAP-NEXT:    [[TMP17:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP18:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP19:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP22:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    ret void
//
// HYBRID-LABEL: define {{[^@]+}}@test_null_constant
// HYBRID-SAME: (ptr addrspace(200) noundef [[ARG:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP1:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP2:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    [[TMP4:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP4]] to i8
// HYBRID-NEXT:    [[TMP5:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    [[TMP6:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP9:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    [[TMP10:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP12:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP13:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) null)
// HYBRID-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP13]] to i8
// HYBRID-NEXT:    [[TMP14:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP14]] to i8
// HYBRID-NEXT:    [[TMP15:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) null)
// HYBRID-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP16]] to i8
// HYBRID-NEXT:    [[TMP17:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP18:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP19:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP22:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    ret void
//
void test_null_constant(__uintcap_t arg) {
  call_overloaded_builtins(void *__capability, (void *)0, (void *)0);
}

// PURECAP-LABEL: define {{[^@]+}}@test_null_int_ptr
// PURECAP-SAME: (ptr addrspace(200) noundef [[ARG:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP1:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP2:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    [[TMP4:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP4]] to i8
// PURECAP-NEXT:    [[TMP5:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    [[TMP6:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP9:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    [[TMP10:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP12:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP13:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) null)
// PURECAP-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP13]] to i8
// PURECAP-NEXT:    [[TMP14:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP14]] to i8
// PURECAP-NEXT:    [[TMP15:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) null)
// PURECAP-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP16]] to i8
// PURECAP-NEXT:    [[TMP17:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP18:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP19:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP22:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) null)
// PURECAP-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) null, i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) null, ptr addrspace(200) null)
// PURECAP-NEXT:    ret void
//
// HYBRID-LABEL: define {{[^@]+}}@test_null_int_ptr
// HYBRID-SAME: (ptr addrspace(200) noundef [[ARG:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP1:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP2:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    [[TMP4:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP4]] to i8
// HYBRID-NEXT:    [[TMP5:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    [[TMP6:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP9:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    [[TMP10:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP12:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP13:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) null)
// HYBRID-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP13]] to i8
// HYBRID-NEXT:    [[TMP14:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP14]] to i8
// HYBRID-NEXT:    [[TMP15:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) null)
// HYBRID-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP16]] to i8
// HYBRID-NEXT:    [[TMP17:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP18:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP19:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP22:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) null, i64 1)
// HYBRID-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) null, ptr addrspace(200) null)
// HYBRID-NEXT:    ret void
//
void test_null_int_ptr(__uintcap_t arg) {
  call_overloaded_builtins(const int *__capability, (const int *__capability)0, (const int *__capability)0);
}

// PURECAP-LABEL: define {{[^@]+}}@test_cap_from_ptr
// PURECAP-SAME: (ptr addrspace(200) noundef [[AUTHCAP1:%.*]], ptr addrspace(200) noundef [[AUTHCAP2:%.*]], i64 noundef signext [[L:%.*]], i32 noundef signext [[I:%.*]], i32 noundef signext [[U:%.*]]) addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 [[L]])
// PURECAP-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP2]], i64 [[L]])
// PURECAP-NEXT:    [[TMP2:%.*]] = call ptr addrspace(200) @llvm.cheri.ddc.get()
// PURECAP-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[TMP2]], i64 [[L]])
// PURECAP-NEXT:    [[TMP4:%.*]] = sext i32 [[I]] to i64
// PURECAP-NEXT:    [[TMP5:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 [[TMP4]])
// PURECAP-NEXT:    [[TMP6:%.*]] = zext i32 [[U]] to i64
// PURECAP-NEXT:    [[TMP7:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 [[TMP6]])
// PURECAP-NEXT:    [[TMP8:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 0)
// PURECAP-NEXT:    ret void
//
// HYBRID-LABEL: define {{[^@]+}}@test_cap_from_ptr
// HYBRID-SAME: (ptr addrspace(200) noundef [[AUTHCAP1:%.*]], ptr addrspace(200) noundef [[AUTHCAP2:%.*]], i64 noundef signext [[L:%.*]], i32 noundef signext [[I:%.*]], i32 noundef signext [[U:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 [[L]])
// HYBRID-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP2]], i64 [[L]])
// HYBRID-NEXT:    [[TMP2:%.*]] = call ptr addrspace(200) @llvm.cheri.ddc.get()
// HYBRID-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[TMP2]], i64 [[L]])
// HYBRID-NEXT:    [[TMP4:%.*]] = sext i32 [[I]] to i64
// HYBRID-NEXT:    [[TMP5:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 [[TMP4]])
// HYBRID-NEXT:    [[TMP6:%.*]] = zext i32 [[U]] to i64
// HYBRID-NEXT:    [[TMP7:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 [[TMP6]])
// HYBRID-NEXT:    [[TMP8:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 0)
// HYBRID-NEXT:    [[TMP9:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 0)
// HYBRID-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.from.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], i64 0)
// HYBRID-NEXT:    ret void
//
void test_cap_from_ptr(void *__capability authcap1, __uintcap_t authcap2, long l, int i, unsigned u) {
  void *__capability c1 = __builtin_cheri_cap_from_pointer(authcap1, l);
  void *__capability c2 = __builtin_cheri_cap_from_pointer(authcap2, l);
  void *__capability c3 = __builtin_cheri_cap_from_pointer(__builtin_cheri_global_data_get(), l);
  // Check int is extended to i64:
  void *__capability c4 = __builtin_cheri_cap_from_pointer(authcap1, i); // sign-extend
  void *__capability c5 = __builtin_cheri_cap_from_pointer(authcap1, u); // zero-extend
  // Zero argument
  void *__capability c6 = __builtin_cheri_cap_from_pointer(authcap1, 0);
#ifndef __CHERI_PURE_CAPABILITY__
  // pointer type argument
  void *__capability c7 = __builtin_cheri_cap_from_pointer(authcap1, (void *)0);
  // Check that we add a bitcast for the return value:
  long *__capability c8 = __builtin_cheri_cap_from_pointer(authcap1, (long *)0);
#endif
}

#ifndef __CHERI_PURE_CAPABILITY__
// HYBRID-LABEL: define {{[^@]+}}@test_cap_to_ptr
// HYBRID-SAME: (ptr addrspace(200) noundef [[AUTHCAP1:%.*]], ptr addrspace(200) noundef [[AUTHCAP2:%.*]], ptr addrspace(200) noundef [[VCAP:%.*]], ptr addrspace(200) noundef [[LCAP:%.*]], ptr addrspace(200) noundef [[ICAP:%.*]]) #[[ATTR0]] {
// HYBRID-NEXT:  entry:
// HYBRID-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.to.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], ptr addrspace(200) [[VCAP]])
// HYBRID-NEXT:    [[TMP1:%.*]] = inttoptr i64 [[TMP0]] to ptr
// HYBRID-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.to.pointer.i64(ptr addrspace(200) [[AUTHCAP2]], ptr addrspace(200) [[VCAP]])
// HYBRID-NEXT:    [[TMP3:%.*]] = inttoptr i64 [[TMP2]] to ptr
// HYBRID-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.ddc.get()
// HYBRID-NEXT:    [[TMP5:%.*]] = call i64 @llvm.cheri.cap.to.pointer.i64(ptr addrspace(200) [[TMP4]], ptr addrspace(200) [[VCAP]])
// HYBRID-NEXT:    [[TMP6:%.*]] = inttoptr i64 [[TMP5]] to ptr
// HYBRID-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.to.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], ptr addrspace(200) null)
// HYBRID-NEXT:    [[TMP8:%.*]] = inttoptr i64 [[TMP7]] to ptr
// HYBRID-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.to.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], ptr addrspace(200) [[LCAP]])
// HYBRID-NEXT:    [[TMP10:%.*]] = inttoptr i64 [[TMP9]] to ptr
// HYBRID-NEXT:    [[TMP11:%.*]] = call i64 @llvm.cheri.cap.to.pointer.i64(ptr addrspace(200) [[AUTHCAP1]], ptr addrspace(200) [[ICAP]])
// HYBRID-NEXT:    [[TMP12:%.*]] = inttoptr i64 [[TMP11]] to ptr
// HYBRID-NEXT:    ret void
//
void test_cap_to_ptr(void *__capability authcap1, __uintcap_t authcap2, void *__capability vcap,
                     long *__capability lcap, const int *__capability icap) {
  void *c1 = __builtin_cheri_cap_to_pointer(authcap1, vcap);
  void *c2 = __builtin_cheri_cap_to_pointer(authcap2, vcap);
  void *c3 = __builtin_cheri_cap_to_pointer(__builtin_cheri_global_data_get(), vcap);
  // Check zero argument is NULL
  void *c4 = __builtin_cheri_cap_to_pointer(authcap1, 0);
  // Check that we add a bitcast for the return value:
  long *c5 = __builtin_cheri_cap_to_pointer(authcap1, lcap);
  const int *c6 = __builtin_cheri_cap_to_pointer(authcap1, icap);
}
#endif

// Array-decay and function-to-pointer decay only works for purecap
#ifdef __CHERI_PURE_CAPABILITY__

static char global_buffer[16];
static char global_buffer2[32];

// PURECAP-LABEL: define {{[^@]+}}@test_array
// PURECAP-SAME: () addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) @global_buffer, i64 1)
// PURECAP-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) @global_buffer, i64 1)
// PURECAP-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) @global_buffer, i64 1)
// PURECAP-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) @global_buffer, ptr addrspace(200) @global_buffer2)
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// PURECAP-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) @global_buffer, i64 1)
// PURECAP-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) @global_buffer, i64 1)
// PURECAP-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) @global_buffer, i64 1)
// PURECAP-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) @global_buffer, ptr addrspace(200) @global_buffer2)
// PURECAP-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// PURECAP-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) @global_buffer, ptr addrspace(200) @global_buffer2)
// PURECAP-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// PURECAP-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// PURECAP-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) @global_buffer, ptr addrspace(200) @global_buffer2)
// PURECAP-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) @global_buffer, ptr addrspace(200) @global_buffer2)
// PURECAP-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) @global_buffer, ptr addrspace(200) @global_buffer2)
// PURECAP-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) @global_buffer, ptr addrspace(200) @global_buffer2)
// PURECAP-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) @global_buffer)
// PURECAP-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) @global_buffer, i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) @global_buffer, i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) @global_buffer, ptr addrspace(200) @global_buffer2)
// PURECAP-NEXT:    ret void
//
void test_array(void) {
  call_overloaded_builtins(const char *__capability, global_buffer, global_buffer2);
}

typedef void (*__capability fnptr_t)(void);

// PURECAP-LABEL: define {{[^@]+}}@test_function
// PURECAP-SAME: () addrspace(200) #[[ATTR0]] {
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[TMP0:%.*]] = call i64 @llvm.cheri.cap.address.get.i64(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.address.set.i64(ptr addrspace(200) @test_function, i64 1)
// PURECAP-NEXT:    [[TMP2:%.*]] = call i64 @llvm.cheri.cap.base.get.i64(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP3:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) @test_function, i64 1)
// PURECAP-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.exact.i64(ptr addrspace(200) @test_function, i64 1)
// PURECAP-NEXT:    [[TMP5:%.*]] = call i1 @llvm.cheri.cap.equal.exact(ptr addrspace(200) @test_function, ptr addrspace(200) @test_array)
// PURECAP-NEXT:    [[FROMBOOL:%.*]] = zext i1 [[TMP5]] to i8
// PURECAP-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.flags.set.i64(ptr addrspace(200) @test_function, i64 1)
// PURECAP-NEXT:    [[TMP7:%.*]] = call i64 @llvm.cheri.cap.flags.get.i64(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP9:%.*]] = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP10:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) @test_function, i64 1)
// PURECAP-NEXT:    [[TMP11:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) @test_function, i64 1)
// PURECAP-NEXT:    [[TMP12:%.*]] = call i64 @llvm.cheri.cap.perms.get.i64(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP13:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal(ptr addrspace(200) @test_function, ptr addrspace(200) @test_array)
// PURECAP-NEXT:    [[TMP14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.seal.entry(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP15:%.*]] = call i1 @llvm.cheri.cap.sealed.get(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[FROMBOOL1:%.*]] = zext i1 [[TMP15]] to i8
// PURECAP-NEXT:    [[TMP16:%.*]] = call i1 @llvm.cheri.cap.subset.test(ptr addrspace(200) @test_function, ptr addrspace(200) @test_array)
// PURECAP-NEXT:    [[FROMBOOL2:%.*]] = zext i1 [[TMP16]] to i8
// PURECAP-NEXT:    [[TMP17:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.tag.clear(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP18:%.*]] = call i1 @llvm.cheri.cap.tag.get(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[FROMBOOL3:%.*]] = zext i1 [[TMP18]] to i8
// PURECAP-NEXT:    [[TMP19:%.*]] = call i64 @llvm.cheri.cap.type.get.i64(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP20:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.unseal(ptr addrspace(200) @test_function, ptr addrspace(200) @test_array)
// PURECAP-NEXT:    [[TMP21:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.conditional.seal(ptr addrspace(200) @test_function, ptr addrspace(200) @test_array)
// PURECAP-NEXT:    [[TMP22:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.type.copy(ptr addrspace(200) @test_function, ptr addrspace(200) @test_array)
// PURECAP-NEXT:    [[TMP23:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.build(ptr addrspace(200) @test_function, ptr addrspace(200) @test_array)
// PURECAP-NEXT:    [[TMP24:%.*]] = call i64 @llvm.cheri.cap.high.get.i64(ptr addrspace(200) @test_function)
// PURECAP-NEXT:    [[TMP25:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.high.set.i64(ptr addrspace(200) @test_function, i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.perms.check.i64(ptr addrspace(200) @test_function, i64 1)
// PURECAP-NEXT:    call void @llvm.cheri.cap.type.check(ptr addrspace(200) @test_function, ptr addrspace(200) @test_array)
// PURECAP-NEXT:    ret void
//
void test_function(void) {
  call_overloaded_builtins(fnptr_t, test_function, test_array);
}

#endif
