// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// REQUIRES: mips-registered-target
// RUN: %cheri_purecap_cc1 -opaque-pointers -Wno-deprecated-non-prototype -Wno-implicit-int -o - -O0 -emit-llvm -disable-O0-optnone  %s | FileCheck %s -check-prefix OPAQUE
// RUN: %cheri_purecap_cc1 -no-opaque-pointers -Wno-deprecated-non-prototype -Wno-implicit-int -o - -O0 -emit-llvm -disable-O0-optnone  %s | FileCheck %s -check-prefix TYPED
// Also check that we can emit asm without crashing:
// RUN: %cheri_purecap_cc1 -Wno-deprecated-non-prototype -Wno-implicit-int -o /dev/null -O0 -S %s


// Calling a function with old-style prototypes would produce an invalid bitcast after commit 1f6d142a46bb24c067aacc50282388ee16065eed
// OPAQUE-LABEL: define {{[^@]+}}@a
// OPAQUE-SAME: (i32 noundef signext [[B:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// OPAQUE-NEXT:  entry:
// OPAQUE-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4, addrspace(200)
// OPAQUE-NEXT:    store i32 [[B]], ptr addrspace(200) [[B_ADDR]], align 4
// OPAQUE-NEXT:    call void @a()
// OPAQUE-NEXT:    ret void
//
// TYPED-LABEL: define {{[^@]+}}@a
// TYPED-SAME: (i32 noundef signext [[B:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// TYPED-NEXT:  entry:
// TYPED-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4, addrspace(200)
// TYPED-NEXT:    store i32 [[B]], i32 addrspace(200)* [[B_ADDR]], align 4
// TYPED-NEXT:    call void bitcast (void (i32) addrspace(200)* @a to void () addrspace(200)*)()
// TYPED-NEXT:    ret void
//
void a(b) {
   a();
}
