// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %cheri_cc1 %s -O2 -msoft-float -emit-llvm -o - | FileCheck %s
#pragma pointer_interpretation capability
struct test
{
	int *a,*b,*c;
};
#pragma pointer_interpretation default
struct test2
{
	int *a,*b,*c;
} t2;
#pragma pointer_interpretation integer
struct test3
{
	int *a,*b,*c;
} t3;
struct test t;

_Pragma("pointer_interpretation integer")
_Pragma("pointer_interpretation capability")
_Pragma("pointer_interpretation default")


// CHECK-LABEL: define {{[^@]+}}@x
// CHECK-SAME: () local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr @t, align 16, !tbaa [[TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr addrspace(200) [[TMP0]], align 4, !tbaa [[TBAA7:![0-9]+]]
// CHECK-NEXT:    ret i32 [[TMP1]]
//
int x(void)
{
	return *t.a;
}

// CHECK-LABEL: define {{[^@]+}}@y
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @t2, align 8, !tbaa [[TBAA9:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP0]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    ret i32 [[TMP1]]
//
int y(void)
{
	return *t2.a;
}
// CHECK-LABEL: define {{[^@]+}}@z
// CHECK-SAME: () local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @t3, align 8, !tbaa [[TBAA11:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[TMP0]], align 4, !tbaa [[TBAA7]]
// CHECK-NEXT:    ret i32 [[TMP1]]
//
int z(void)
{
	return *t3.a;
}

