// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// Check that when we enable -mllvm -cheri-subobject-bounds-clear-swperm that the given software permission is cleared
// RUN: %cheri_purecap_cc1 -cheri-bounds=subobject-safe -O2 -emit-llvm %s -o - -Rcheri-subobject-bounds \
// RUN:    -mllvm -cheri-subobject-bounds-clear-swperm=2 -verify | FileCheck %s -check-prefix CLEAR-PERM2

int global_int;

// CLEAR-PERM2-LABEL: define {{[^@]+}}@return_global_int
// CLEAR-PERM2-SAME: () local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
// CLEAR-PERM2-NEXT:  entry:
// CLEAR-PERM2-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull @global_int, i64 4)
// CLEAR-PERM2-NEXT:    [[CUR_LEN:%.*]] = tail call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) nonnull @global_int)
// CLEAR-PERM2-NEXT:    [[NEW_LEN:%.*]] = tail call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[TMP0]])
// CLEAR-PERM2-NEXT:    [[NEW_LEN1:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[TMP0]], i64 -131073)
// CLEAR-PERM2-NEXT:    [[NEW_BOUNDS_LESS:%.*]] = icmp ult i64 [[NEW_LEN]], [[CUR_LEN]]
// CLEAR-PERM2-NEXT:    [[RESULT:%.*]] = select i1 [[NEW_BOUNDS_LESS]], ptr addrspace(200) [[NEW_LEN1]], ptr addrspace(200) [[TMP0]]
// CLEAR-PERM2-NEXT:    ret ptr addrspace(200) [[RESULT]]
//
int *return_global_int() {
  return &global_int; // expected-remark{{setting bounds for pointer to 'int' to 4 bytes}}
}

struct foo {
  int a;
  int b;
} global_foo;

// CLEAR-PERM2-LABEL: define {{[^@]+}}@return_global_subobject
// CLEAR-PERM2-SAME: () local_unnamed_addr addrspace(200) #[[ATTR0]] {
// CLEAR-PERM2-NEXT:  entry:
// CLEAR-PERM2-NEXT:    [[TMP0:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull @global_foo, i64 4)
// CLEAR-PERM2-NEXT:    [[CUR_LEN:%.*]] = tail call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) nonnull @global_foo)
// CLEAR-PERM2-NEXT:    [[NEW_LEN:%.*]] = tail call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[TMP0]])
// CLEAR-PERM2-NEXT:    [[NEW_LEN1:%.*]] = tail call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[TMP0]], i64 -131073)
// CLEAR-PERM2-NEXT:    [[NEW_BOUNDS_LESS:%.*]] = icmp ult i64 [[NEW_LEN]], [[CUR_LEN]]
// CLEAR-PERM2-NEXT:    [[RESULT:%.*]] = select i1 [[NEW_BOUNDS_LESS]], ptr addrspace(200) [[NEW_LEN1]], ptr addrspace(200) [[TMP0]]
// CLEAR-PERM2-NEXT:    ret ptr addrspace(200) [[RESULT]]
//
int *return_global_subobject() {
  return &global_foo.a; // expected-remark{{setting sub-object bounds for field 'a' (pointer to 'int') to 4 bytes}}
}

extern int printf(const char*, ...);

// CLEAR-PERM2-LABEL: define {{[^@]+}}@main
// CLEAR-PERM2-SAME: (i32 noundef signext [[ARGC:%.*]], ptr addrspace(200) nocapture noundef readnone [[ARGV:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR2:[0-9]+]] {
// CLEAR-PERM2-NEXT:  entry:
// CLEAR-PERM2-NEXT:    [[F:%.*]] = alloca [[STRUCT_FOO_0:%.*]], align 4, addrspace(200)
// CLEAR-PERM2-NEXT:    call void @llvm.lifetime.start.p200(i64 2, ptr addrspace(200) nonnull [[F]]) #[[ATTR4:[0-9]+]]
// CLEAR-PERM2-NEXT:    store i8 97, ptr addrspace(200) [[F]], align 4
// CLEAR-PERM2-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i8, ptr addrspace(200) [[F]], i64 1
// CLEAR-PERM2-NEXT:    store i8 98, ptr addrspace(200) [[TMP0]], align 1
// CLEAR-PERM2-NEXT:    [[TMP1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull [[F]], i64 1)
// CLEAR-PERM2-NEXT:    [[CUR_LEN:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) nonnull [[F]])
// CLEAR-PERM2-NEXT:    [[NEW_LEN:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[TMP1]])
// CLEAR-PERM2-NEXT:    [[NEW_LEN1:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[TMP1]], i64 -131073)
// CLEAR-PERM2-NEXT:    [[NEW_BOUNDS_LESS:%.*]] = icmp ult i64 [[NEW_LEN]], [[CUR_LEN]]
// CLEAR-PERM2-NEXT:    [[RESULT:%.*]] = select i1 [[NEW_BOUNDS_LESS]], ptr addrspace(200) [[NEW_LEN1]], ptr addrspace(200) [[TMP1]]
// CLEAR-PERM2-NEXT:    [[TMP2:%.*]] = sext i32 [[ARGC]] to i64
// CLEAR-PERM2-NEXT:    [[TMP3:%.*]] = getelementptr i8, ptr addrspace(200) [[RESULT]], i64 [[TMP2]]
// CLEAR-PERM2-NEXT:    [[ADD_PTR:%.*]] = getelementptr i8, ptr addrspace(200) [[TMP3]], i64 -1
// CLEAR-PERM2-NEXT:    [[TMP4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull [[F]], i64 2)
// CLEAR-PERM2-NEXT:    [[NEW_LEN3:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[TMP4]])
// CLEAR-PERM2-NEXT:    [[NEW_LEN4:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[TMP4]], i64 -131073)
// CLEAR-PERM2-NEXT:    [[NEW_BOUNDS_LESS5:%.*]] = icmp ult i64 [[NEW_LEN3]], [[CUR_LEN]]
// CLEAR-PERM2-NEXT:    [[RESULT6:%.*]] = select i1 [[NEW_BOUNDS_LESS5]], ptr addrspace(200) [[NEW_LEN4]], ptr addrspace(200) [[TMP4]]
// CLEAR-PERM2-NEXT:    [[TMP5:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull @.str, i64 20)
// CLEAR-PERM2-NEXT:    [[CUR_LEN7:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) nonnull @.str)
// CLEAR-PERM2-NEXT:    [[NEW_LEN8:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[TMP5]])
// CLEAR-PERM2-NEXT:    [[NEW_LEN9:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[TMP5]], i64 -131073)
// CLEAR-PERM2-NEXT:    [[NEW_BOUNDS_LESS10:%.*]] = icmp ult i64 [[NEW_LEN8]], [[CUR_LEN7]]
// CLEAR-PERM2-NEXT:    [[RESULT11:%.*]] = select i1 [[NEW_BOUNDS_LESS10]], ptr addrspace(200) [[NEW_LEN9]], ptr addrspace(200) [[TMP5]]
// CLEAR-PERM2-NEXT:    [[CALL:%.*]] = call signext i32 (ptr addrspace(200), ...) @printf(ptr addrspace(200) noundef nonnull dereferenceable(1) [[RESULT11]], ptr addrspace(200) noundef [[ADD_PTR]])
// CLEAR-PERM2-NEXT:    [[TMP6:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.bounds.set.i64(ptr addrspace(200) nonnull @.str.1, i64 22)
// CLEAR-PERM2-NEXT:    [[CUR_LEN12:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) nonnull @.str.1)
// CLEAR-PERM2-NEXT:    [[NEW_LEN13:%.*]] = call i64 @llvm.cheri.cap.length.get.i64(ptr addrspace(200) [[TMP6]])
// CLEAR-PERM2-NEXT:    [[NEW_LEN14:%.*]] = call ptr addrspace(200) @llvm.cheri.cap.perms.and.i64(ptr addrspace(200) [[TMP6]], i64 -131073)
// CLEAR-PERM2-NEXT:    [[NEW_BOUNDS_LESS15:%.*]] = icmp ult i64 [[NEW_LEN13]], [[CUR_LEN12]]
// CLEAR-PERM2-NEXT:    [[RESULT16:%.*]] = select i1 [[NEW_BOUNDS_LESS15]], ptr addrspace(200) [[NEW_LEN14]], ptr addrspace(200) [[TMP6]]
// CLEAR-PERM2-NEXT:    [[CALL17:%.*]] = call signext i32 (ptr addrspace(200), ...) @printf(ptr addrspace(200) noundef nonnull dereferenceable(1) [[RESULT16]], ptr addrspace(200) noundef [[RESULT6]])
// CLEAR-PERM2-NEXT:    call void @llvm.lifetime.end.p200(i64 2, ptr addrspace(200) nonnull [[F]]) #[[ATTR4]]
// CLEAR-PERM2-NEXT:    ret i32 0
//
int main(int argc, char **argv) {
  struct foo {
    char a;
    char b;
  } f = {'a', 'b'};
  char *ptr = &f.a + (argc - 1); // expected-remark{{setting sub-object bounds for field 'a' (pointer to 'char') to 1 bytes}}
  void *full_struct = &f; // expected-remark{{setting bounds for pointer to 'struct foo' to 2 bytes}}
  printf("subobject ptr=%#p!\n", ptr); // should have uperm 2 cleared
  // expected-remark@-1{{setting sub-object bounds for array decay on 'char[20]' to 20 bytes}}
  printf("full struct ptr=%#p!\n", full_struct); // should not have uperm 2 cleared
  // expected-remark@-1{{setting sub-object bounds for array decay on 'char[22]' to 22 bytes}}
  return 0;
}
