; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
;; Since "PreIselIntrinsicLowering: Check RuntimeLibcalls instead of TLI for memory functions"
;; we no longer expand for targets that have a memcpy/memset libcall.
;; Check that we don't trigger assertions here. Issue: https://github.com/CTSRD-CHERI/llvm-project/issues/753
; RUN: opt -S -mtriple=riscv64 -pre-isel-intrinsic-lowering -mem-intrinsic-expand-size=0 < %s | FileCheck %s --check-prefixes=RISCV
; RUN: %riscv64_cheri_opt -S -mem-intrinsic-expand-size=0 -pre-isel-intrinsic-lowering < %s | FileCheck %s --check-prefixes=HYBRID
; RUN: sed 's/.p0/.p200/g' < %s | %riscv64_cheri_purecap_opt -S -mem-intrinsic-expand-size=0 -pre-isel-intrinsic-lowering | FileCheck %s --check-prefixes=PURECAP

declare void @llvm.memmove.p0.p0.i64(ptr addrspace("G") nocapture, ptr addrspace("G") nocapture readonly, i64, i1)
declare void @llvm.memset.p0.i64(ptr addrspace("G") nocapture, i8, i64, i1)
declare void @llvm.memcpy.p0.p0.i64(ptr addrspace("G") nocapture, ptr addrspace("G") nocapture readonly, i64, i1)

define void @call_memset(ptr addrspace("G") align 16 %dst) #0 {
; RISCV-LABEL: @call_memset(
; RISCV-NEXT:  entry:
; RISCV-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[DST:%.*]], i8 0, i64 40, i1 false)
; RISCV-NEXT:    ret void
;
; HYBRID-LABEL: @call_memset(
; HYBRID-NEXT:  entry:
; HYBRID-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[DST:%.*]], i8 0, i64 40, i1 false)
; HYBRID-NEXT:    ret void
;
; PURECAP-LABEL: @call_memset(
; PURECAP-NEXT:  entry:
; PURECAP-NEXT:    call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 [[DST:%.*]], i8 0, i64 40, i1 false)
; PURECAP-NEXT:    ret void
;
entry:
  call void @llvm.memset.p0.i64(ptr addrspace("G") align 16 %dst, i8 0, i64 40, i1 false)
  ret void
}

define void @call_memset_variable(ptr addrspace("G") align 16 %dst, i64 %len) #0 {
; RISCV-LABEL: @call_memset_variable(
; RISCV-NEXT:  entry:
; RISCV-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[DST:%.*]], i8 0, i64 [[LEN:%.*]], i1 false)
; RISCV-NEXT:    ret void
;
; HYBRID-LABEL: @call_memset_variable(
; HYBRID-NEXT:  entry:
; HYBRID-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[DST:%.*]], i8 0, i64 [[LEN:%.*]], i1 false)
; HYBRID-NEXT:    ret void
;
; PURECAP-LABEL: @call_memset_variable(
; PURECAP-NEXT:  entry:
; PURECAP-NEXT:    call void @llvm.memset.p200.i64(ptr addrspace(200) align 16 [[DST:%.*]], i8 0, i64 [[LEN:%.*]], i1 false)
; PURECAP-NEXT:    ret void
;
entry:
  call void @llvm.memset.p0.i64(ptr addrspace("G") align 16 %dst, i8 0, i64 %len, i1 false)
  ret void
}

define void @call_memcpy(ptr addrspace("G") align 16 %dst, ptr addrspace("G") align 16 %src) #0 {
; RISCV-LABEL: @call_memcpy(
; RISCV-NEXT:  entry:
; RISCV-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 16 [[DST:%.*]], ptr align 16 [[SRC:%.*]], i64 40, i1 false)
; RISCV-NEXT:    ret void
;
; HYBRID-LABEL: @call_memcpy(
; HYBRID-NEXT:  entry:
; HYBRID-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 16 [[DST:%.*]], ptr align 16 [[SRC:%.*]], i64 40, i1 false)
; HYBRID-NEXT:    ret void
;
; PURECAP-LABEL: @call_memcpy(
; PURECAP-NEXT:  entry:
; PURECAP-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 [[DST:%.*]], ptr addrspace(200) align 16 [[SRC:%.*]], i64 40, i1 false)
; PURECAP-NEXT:    ret void
;
entry:
  call void @llvm.memcpy.p0.p0.i64(ptr addrspace("G") align 16 %dst, ptr addrspace("G") align 16 %src, i64 40, i1 false)
  ret void
}

define void @call_memcpy_variable(ptr addrspace("G") align 16 %dst, ptr addrspace("G") align 16 %src, i64 %len) #0 {
; RISCV-LABEL: @call_memcpy_variable(
; RISCV-NEXT:  entry:
; RISCV-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 16 [[DST:%.*]], ptr align 16 [[SRC:%.*]], i64 [[LEN:%.*]], i1 false)
; RISCV-NEXT:    ret void
;
; HYBRID-LABEL: @call_memcpy_variable(
; HYBRID-NEXT:  entry:
; HYBRID-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 16 [[DST:%.*]], ptr align 16 [[SRC:%.*]], i64 [[LEN:%.*]], i1 false)
; HYBRID-NEXT:    ret void
;
; PURECAP-LABEL: @call_memcpy_variable(
; PURECAP-NEXT:  entry:
; PURECAP-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 16 [[DST:%.*]], ptr addrspace(200) align 16 [[SRC:%.*]], i64 [[LEN:%.*]], i1 false)
; PURECAP-NEXT:    ret void
;
entry:
  call void @llvm.memcpy.p0.p0.i64(ptr addrspace("G") align 16 %dst, ptr addrspace("G") align 16 %src, i64 %len, i1 false)
  ret void
}

define void @call_memmove(ptr addrspace("G") align 16 %dst, ptr addrspace("G") align 16 %src) #0 {
; RISCV-LABEL: @call_memmove(
; RISCV-NEXT:  entry:
; RISCV-NEXT:    call void @llvm.memmove.p0.p0.i64(ptr align 16 [[DST:%.*]], ptr align 16 [[SRC:%.*]], i64 40, i1 false)
; RISCV-NEXT:    ret void
;
; HYBRID-LABEL: @call_memmove(
; HYBRID-NEXT:  entry:
; HYBRID-NEXT:    call void @llvm.memmove.p0.p0.i64(ptr align 16 [[DST:%.*]], ptr align 16 [[SRC:%.*]], i64 40, i1 false)
; HYBRID-NEXT:    ret void
;
; PURECAP-LABEL: @call_memmove(
; PURECAP-NEXT:  entry:
; PURECAP-NEXT:    call void @llvm.memmove.p200.p200.i64(ptr addrspace(200) align 16 [[DST:%.*]], ptr addrspace(200) align 16 [[SRC:%.*]], i64 40, i1 false)
; PURECAP-NEXT:    ret void
;
entry:
  call void @llvm.memmove.p0.p0.i64(ptr addrspace("G") align 16 %dst, ptr addrspace("G") align 16 %src, i64 40, i1 false)
  ret void
}

define void @call_memmove_variable(ptr addrspace("G") align 16 %dst, ptr addrspace("G") align 16 %src, i64 %len) #0 {
; RISCV-LABEL: @call_memmove_variable(
; RISCV-NEXT:  entry:
; RISCV-NEXT:    call void @llvm.memmove.p0.p0.i64(ptr align 16 [[DST:%.*]], ptr align 16 [[SRC:%.*]], i64 [[LEN:%.*]], i1 false)
; RISCV-NEXT:    ret void
;
; HYBRID-LABEL: @call_memmove_variable(
; HYBRID-NEXT:  entry:
; HYBRID-NEXT:    call void @llvm.memmove.p0.p0.i64(ptr align 16 [[DST:%.*]], ptr align 16 [[SRC:%.*]], i64 [[LEN:%.*]], i1 false)
; HYBRID-NEXT:    ret void
;
; PURECAP-LABEL: @call_memmove_variable(
; PURECAP-NEXT:  entry:
; PURECAP-NEXT:    call void @llvm.memmove.p200.p200.i64(ptr addrspace(200) align 16 [[DST:%.*]], ptr addrspace(200) align 16 [[SRC:%.*]], i64 [[LEN:%.*]], i1 false)
; PURECAP-NEXT:    ret void
;
entry:
  call void @llvm.memmove.p0.p0.i64(ptr addrspace("G") align 16 %dst, ptr addrspace("G") align 16 %src, i64 %len, i1 false)
  ret void
}

;; We need the "no-builtins" attribute here otherwise the IR lowering pass will
;; be skipped since it assumes the libfunc can be called.
attributes #0 = { nounwind "no-builtins" }
