; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/setoffset-multiple-uses.ll
; RUN: opt -S -passes=instcombine -o - %s | FileCheck %s
; RUN: opt -S -passes=instcombine -o - %s | llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+y,+cap-mode,+f,+d -O1 - -o - | %cheri_FileCheck %s --check-prefix ASM

target datalayout = "e-m:e-pf200:128:128:128:64-p:64:64-i64:64-i128:128-n64-S128-A200-P200-G200"
; Reduced test case for a crash in the new optimization to fold multiple setoffset calls (orignally found when compiling libunwind)

declare i64 @check_fold(i64) addrspace(200)
declare void @check_fold_i8ptr(ptr addrspace(200)) addrspace(200)
declare i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200)) addrspace(200)
declare ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200), i64) addrspace(200)

define void @infer_values_from_null_set_offset() addrspace(200) nounwind {
; ASM-LABEL: infer_values_from_null_set_offset:
; ASM:       # %bb.0:
; ASM-NEXT:    addiy csp, csp, -16
; ASM-NEXT:    sy cra, 0(csp) # 16-byte Folded Spill
; ASM-NEXT:    lui a0, 30
; ASM-NEXT:    addiw a0, a0, 576
; ASM-NEXT:    call check_fold
; ASM-NEXT:    ly cra, 0(csp) # 16-byte Folded Reload
; ASM-NEXT:    addiy csp, csp, 16
; ASM-NEXT:    ret
; CHECK-LABEL: define void @infer_values_from_null_set_offset
; CHECK-SAME: () addrspace(200) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[OFFSET_CHECK:%.*]] = call i64 @check_fold(i64 123456)
; CHECK-NEXT:    ret void
;
  %with_offset = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) null, i64 123456)
  %offset = call i64 @llvm.cheri.cap.offset.get.i64(ptr addrspace(200) nonnull %with_offset)
  %offset_check = call i64 @check_fold(i64 %offset)
  ret void
}

define void @multiple_uses_big_constant() addrspace(200) nounwind {
; ASM-LABEL: multiple_uses_big_constant:
; ASM:       # %bb.0:
; ASM-NEXT:    addiy csp, csp, -32
; ASM-NEXT:    sy cra, 16(csp) # 16-byte Folded Spill
; ASM-NEXT:    sy cs0, 0(csp) # 16-byte Folded Spill
; ASM-NEXT:    lui a0, 30
; ASM-NEXT:    addiw a0, a0, 576
; ASM-NEXT:    addy cs0, cnull, a0
; ASM-NEXT:    ymv ca0, cs0
; ASM-NEXT:    call check_fold_i8ptr
; ASM-NEXT:    ymv ca0, cs0
; ASM-NEXT:    call check_fold_i8ptr
; ASM-NEXT:    ymv ca0, cs0
; ASM-NEXT:    call check_fold_i8ptr
; ASM-NEXT:    ly cra, 16(csp) # 16-byte Folded Reload
; ASM-NEXT:    ly cs0, 0(csp) # 16-byte Folded Reload
; ASM-NEXT:    addiy csp, csp, 32
; ASM-NEXT:    ret
; CHECK-LABEL: define void @multiple_uses_big_constant
; CHECK-SAME: () addrspace(200) #[[ATTR1]] {
; CHECK-NEXT:    call void @check_fold_i8ptr(ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 123456))
; CHECK-NEXT:    call void @check_fold_i8ptr(ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 123456))
; CHECK-NEXT:    call void @check_fold_i8ptr(ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 123456))
; CHECK-NEXT:    ret void
;
  %with_offset = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) null, i64 123456)
  call void @check_fold_i8ptr(ptr addrspace(200) %with_offset)
  call void @check_fold_i8ptr(ptr addrspace(200) %with_offset)
  call void @check_fold_i8ptr(ptr addrspace(200) %with_offset)
  ret void
}

; Here we should use an immediate cincoffset:
define void @multiple_uses_small_constant() addrspace(200) nounwind {
; ASM-LABEL: multiple_uses_small_constant:
; ASM:       # %bb.0:
; ASM-NEXT:    addiy csp, csp, -16
; ASM-NEXT:    sy cra, 0(csp) # 16-byte Folded Spill
; ASM-NEXT:    addiy ca0, cnull, 123
; ASM-NEXT:    call check_fold_i8ptr
; ASM-NEXT:    addiy ca0, cnull, 123
; ASM-NEXT:    call check_fold_i8ptr
; ASM-NEXT:    addiy ca0, cnull, 123
; ASM-NEXT:    call check_fold_i8ptr
; ASM-NEXT:    ly cra, 0(csp) # 16-byte Folded Reload
; ASM-NEXT:    addiy csp, csp, 16
; ASM-NEXT:    ret
; CHECK-LABEL: define void @multiple_uses_small_constant
; CHECK-SAME: () addrspace(200) #[[ATTR1]] {
; CHECK-NEXT:    call void @check_fold_i8ptr(ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 123))
; CHECK-NEXT:    call void @check_fold_i8ptr(ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 123))
; CHECK-NEXT:    call void @check_fold_i8ptr(ptr addrspace(200) getelementptr (i8, ptr addrspace(200) null, i64 123))
; CHECK-NEXT:    ret void
;
  %with_offset = call ptr addrspace(200) @llvm.cheri.cap.offset.set.i64(ptr addrspace(200) null, i64 123)
  call void @check_fold_i8ptr(ptr addrspace(200) %with_offset)
  call void @check_fold_i8ptr(ptr addrspace(200) %with_offset)
  call void @check_fold_i8ptr(ptr addrspace(200) %with_offset)
  ret void
}
