; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/stack-spill-unnecessary.c.ll
; The new CheriBoundedStackPseudo instruction lets us pretend that the incoffset+csetbounds
; is a single trivially rematerizable instruction so it can freely move it around to avoid stack spills.
; Previously we were moving the allocation of the register that is only used later to the beginning of
; the function and saving+restoring it instead of materializing it just before

; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+y,+cap-mode,+f -O2 --cheri-stack-bounds-single-intrinsic-threshold=0 < %s | %cheri_FileCheck %s --check-prefixes=CHECK
; Always use a single intrinsic for the calls (should result in same codegen)
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+y,+cap-mode,+f -O2 --cheri-stack-bounds-single-intrinsic-threshold=0 < %s | %cheri_FileCheck %s --check-prefixes=CHECK
; RUN: sed 's/addrspace(200)/addrspace(0)/g' %s | llc -mtriple=riscv32 --relocation-model=pic -target-abi ilp32f -mattr=+y,+zyhybrid,+f | FileCheck --check-prefix HYBRID %s


declare void @foo() addrspace(200)
declare void @one_arg(i32 addrspace(200)*) addrspace(200)
declare void @multi_arg(i32 addrspace(200)* %start, i32 addrspace(200)* %end, i8 addrspace(200)* %buf) addrspace(200)

define void @use_after_call() addrspace(200) nounwind {
; CHECK-LABEL: use_after_call:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiy csp, csp, -32
; CHECK-NEXT:    sy cra, 24(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sy cs0, 16(csp) # 8-byte Folded Spill
; CHECK-NEXT:    addiy ca0, csp, 12
; CHECK-NEXT:    ybndsiw cs0, ca0, 4
; CHECK-NEXT:    li a0, 123
; CHECK-NEXT:    sw a0, 12(csp)
; CHECK-NEXT:    call foo
; CHECK-NEXT:    ymv ca0, cs0
; CHECK-NEXT:    call one_arg
; CHECK-NEXT:    ly cra, 24(csp) # 8-byte Folded Reload
; CHECK-NEXT:    ly cs0, 16(csp) # 8-byte Folded Reload
; CHECK-NEXT:    addiy csp, csp, 32
; CHECK-NEXT:    ret
;
; HYBRID-LABEL: use_after_call:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; HYBRID-NEXT:    li a0, 123
; HYBRID-NEXT:    sw a0, 8(sp)
; HYBRID-NEXT:    call foo@plt
; HYBRID-NEXT:    addi a0, sp, 8
; HYBRID-NEXT:    call one_arg@plt
; HYBRID-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %x = alloca i32, align 4, addrspace(200)
  store i32 123, i32 addrspace(200)* %x, align 4
  call void @foo()
  call void @one_arg(i32 addrspace(200)* %x)
  ret void
}

define void @use_after_call_no_store() addrspace(200) nounwind {
; CHECK-LABEL: use_after_call_no_store:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiy csp, csp, -32
; CHECK-NEXT:    sy cra, 24(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sy cs0, 16(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sy cs1, 8(csp) # 8-byte Folded Spill
; CHECK-NEXT:    addiy ca0, csp, 4
; CHECK-NEXT:    ybndsiw cs0, ca0, 4
; CHECK-NEXT:    addiy ca0, csp, 0
; CHECK-NEXT:    ybndsiw cs1, ca0, 4
; CHECK-NEXT:    call foo
; CHECK-NEXT:    ymv ca0, cs0
; CHECK-NEXT:    call one_arg
; CHECK-NEXT:    ymv ca0, cs1
; CHECK-NEXT:    call one_arg
; CHECK-NEXT:    ly cra, 24(csp) # 8-byte Folded Reload
; CHECK-NEXT:    ly cs0, 16(csp) # 8-byte Folded Reload
; CHECK-NEXT:    ly cs1, 8(csp) # 8-byte Folded Reload
; CHECK-NEXT:    addiy csp, csp, 32
; CHECK-NEXT:    ret
;
; HYBRID-LABEL: use_after_call_no_store:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; HYBRID-NEXT:    call foo@plt
; HYBRID-NEXT:    addi a0, sp, 8
; HYBRID-NEXT:    call one_arg@plt
; HYBRID-NEXT:    addi a0, sp, 4
; HYBRID-NEXT:    call one_arg@plt
; HYBRID-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %x = alloca i32, align 4, addrspace(200)
  %y = alloca i32, align 4, addrspace(200)
  call void @foo()
  call void @one_arg(i32 addrspace(200)* %x)
  call void @one_arg(i32 addrspace(200)* %y)
  ret void
}

define void @multi_use() addrspace(200) nounwind {
; CHECK-LABEL: multi_use:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addiy csp, csp, -32
; CHECK-NEXT:    sy cra, 24(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sy cs0, 16(csp) # 8-byte Folded Spill
; CHECK-NEXT:    sy cs1, 8(csp) # 8-byte Folded Spill
; CHECK-NEXT:    addiy ca0, csp, 4
; CHECK-NEXT:    ybndsiw cs0, ca0, 4
; CHECK-NEXT:    addiy ca0, csp, 0
; CHECK-NEXT:    ybndsiw cs1, ca0, 4
; CHECK-NEXT:    call foo
; CHECK-NEXT:    addiy ca1, cs1, 4
; CHECK-NEXT:    addiy ca2, cs1, 1
; CHECK-NEXT:    ymv ca0, cs1
; CHECK-NEXT:    call multi_arg
; CHECK-NEXT:    ymv ca0, cs0
; CHECK-NEXT:    call one_arg
; CHECK-NEXT:    ymv ca0, cs1
; CHECK-NEXT:    call one_arg
; CHECK-NEXT:    ly cra, 24(csp) # 8-byte Folded Reload
; CHECK-NEXT:    ly cs0, 16(csp) # 8-byte Folded Reload
; CHECK-NEXT:    ly cs1, 8(csp) # 8-byte Folded Reload
; CHECK-NEXT:    addiy csp, csp, 32
; CHECK-NEXT:    ret
;
; HYBRID-LABEL: multi_use:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sw ra, 12(sp) # 4-byte Folded Spill
; HYBRID-NEXT:    call foo@plt
; HYBRID-NEXT:    addi a1, sp, 8
; HYBRID-NEXT:    addi a2, sp, 5
; HYBRID-NEXT:    addi a0, sp, 4
; HYBRID-NEXT:    call multi_arg@plt
; HYBRID-NEXT:    addi a0, sp, 8
; HYBRID-NEXT:    call one_arg@plt
; HYBRID-NEXT:    addi a0, sp, 4
; HYBRID-NEXT:    call one_arg@plt
; HYBRID-NEXT:    lw ra, 12(sp) # 4-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %y = alloca i32, align 4, addrspace(200)
  %x = alloca i32, align 4, addrspace(200)
  call void @foo()
  %x_plus0 = getelementptr inbounds i32, i32 addrspace(200)* %x, i32 0
  %x_plus1 = getelementptr i32, i32 addrspace(200)* %x, i32 1
  %x_i8 = bitcast i32 addrspace(200)* %x to i8 addrspace(200)*
  %x_i8_plus_1 = getelementptr inbounds i8, i8 addrspace(200)* %x_i8, i32 1
  call void @multi_arg(i32 addrspace(200)* %x_plus0, i32 addrspace(200)* %x_plus1, i8 addrspace(200)* %x_i8_plus_1)
  call void @one_arg(i32 addrspace(200)* %y)
  call void @one_arg(i32 addrspace(200)* %x)
  ret void
}
